using Appizza.Table.Core;

namespace Appizza.Table;

public sealed class CartPage : ContentPage
{
    private readonly VerticalStackLayout _layout = new() { Padding = 24, Spacing = 10 };
    public CartPage() { Title = "Carrinho"; Content = new ScrollView { Content = _layout }; }
    protected override async void OnAppearing() { base.OnAppearing(); _layout.Clear(); if (TableRuntime.Context is not LocalContext context || TableRuntime.Menu is not MenuPresentation menu) return; var cart = await TableRuntime.Database.GetOrCreateCartAsync(context, menu.CatalogVersion, menu.AvailabilityVersion, DateTime.UtcNow); var items = await TableRuntime.Database.GetCartItemsAsync(Guid.ParseExact(cart.Id, "N")); _layout.Add(new Label { Text = "Carrinho desta sessão", FontSize = 26, FontAttributes = FontAttributes.Bold }); foreach (var item in items) _layout.Add(new Label { Text = $"{item.ProductType} · {item.Quantity:N0} × R$ {item.EstimatedUnitAmount:N2} = R$ {item.EstimatedTotalAmount:N2} · {item.ValidationState}" }); _layout.Add(new Label { Text = "Valores locais são estimativas; o servidor recalcula antes do envio.", FontAttributes = FontAttributes.Italic }); var status = new Label { Text = $"Estado: {cart.Status}" }; _layout.Add(status); var simulate = new Button { Text = "Revisar valores" }; simulate.Clicked += async (_, _) => { try { using var result = await TableRuntime.SimulateCartAsync(cart, items); var review = result.RootElement.GetProperty("requiresReview").GetBoolean(); status.Text = review ? "Revise as mudanças autoritativas antes de enviar." : "Valores autoritativos conferidos."; } catch (Exception ex) { status.Text = $"Não foi possível simular: {ex.Message}"; } }; _layout.Add(simulate); var submit = new Button { Text = "Enviar pedido" }; submit.Clicked += async (_, _) => { try { using var result = await TableRuntime.SubmitCartAsync(cart, acceptedReview: true); status.Text = $"Pedido {result.RootElement.GetProperty("order").GetProperty("number")} confirmado; intake da cozinha pendente."; } catch (HttpRequestException) { status.Text = "Confirmação desconhecida. Reconcilie online antes de tentar novamente."; } }; _layout.Add(submit); if (cart.Status == "submission_unknown") { var reconcile = new Button { Text = "Reconciliar envio" }; reconcile.Clicked += async (_, _) => { try { using var result = await TableRuntime.ReconcileSubmissionAsync(Guid.ParseExact(cart.Id, "N")); status.Text = $"Pedido {result.RootElement.GetProperty("order").GetProperty("number")} recuperado."; } catch (Exception ex) { status.Text = $"Reconciliação pendente: {ex.Message}"; } }; _layout.Add(reconcile); } }
}
