using System.Security.Claims;
using System.Text.Json;
using Appizza.Modules.Devices;
using Appizza.Modules.Identity;
using Appizza.Modules.Kitchen;
using Appizza.Modules.Ordering;
using Appizza.Modules.Tables;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api;

public sealed record CreateCancellationRequest(string ReasonCode, string? CustomerNote, long? ExpectedOrderItemVersion);
public sealed record WithdrawCancellationRequest(long? ExpectedVersion);
public sealed record DecideCancellationRequest(string Decision, string? ProductionAction, string Reason, long? ExpectedVersion);

public static class Phase5CancellationEndpoints
{
    public static IEndpointRouteBuilder MapPhase5CancellationEndpoints(this IEndpointRouteBuilder app)
    {
        var device = app.MapGroup("/api/v1/table-device").RequireAuthorization();
        device.MapPost("/order-items/{id:guid}/cancellation-requests", Create);
        device.MapPost("/order-item-requests/{id:guid}/withdraw", Withdraw);
        var operations = app.MapGroup("/api/v1/operations").RequireAuthorization();
        operations.MapGet("/order-item-requests", List);
        operations.MapPost("/order-item-requests/{id:guid}/decide", Decide);
        return app;
    }

    private static async Task<IResult> Create(Guid id, CreateCancellationRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(request.ReasonCode)) return Error(400, "REASON_REQUIRED", "Motivo é obrigatório.");
        if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório.");
        var deviceContext = await Device(principal, db, ct); if (deviceContext.Error is not null) return deviceContext.Error;
        var tenant = deviceContext.Device!.EstablishmentId!.Value; const string operation = "ordering.cancellation.create"; var hash = Hash(new { id, request });
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return await Replay(tx, replay, ct);
        var located = await db.Set<OrderItem>().AsNoTracking().Where(x => x.Id == id).Join(db.Set<Order>(), x => x.OrderId, x => x.Id, (item, order) => new { item, order }).SingleOrDefaultAsync(ct);
        if (located is null || located.order.EstablishmentId != tenant) return Results.NotFound();
        var binding = await db.Set<DeviceTableBinding>().AsNoTracking().SingleOrDefaultAsync(x => x.DeviceId == deviceContext.Device.Id && x.UnboundAt == null, ct); if (binding is null) return Results.NotFound();
        var session = await db.Set<TableSession>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == located.order.TableSessionId && x.EstablishmentId == tenant && x.DiningTableId == binding.DiningTableId, ct); if (session is null || session.Status != "open") return Error(409, "SESSION_NOT_ACTIVE", "Sessão não está ativa.");
        await LockCommercial(db, session.Id, located.order.Id, id, ct); db.ChangeTracker.Clear();
        var order = await db.Set<Order>().SingleAsync(x => x.Id == located.order.Id && x.EstablishmentId == tenant, ct); var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == id && x.OrderId == order.Id, ct); var lockedSession = await db.Set<TableSession>().SingleAsync(x => x.Id == session.Id, ct);
        if (item.CommercialStatus == "cancelled") return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_ALREADY_CANCELLED", "Item já cancelado.", ct);
        if (request.ExpectedOrderItemVersion is long expected && expected != item.Version) return await Conflict(db, tx, tenant, operation, key, hash, "CONCURRENCY_CONFLICT", "Versão desatualizada.", ct);
        if (await db.Set<OrderItemRequest>().AnyAsync(x => x.OrderItemId == id && new[] { "pending_validation", "pending_customer_confirmation", "pending_operational_decision" }.Contains(x.Status), ct)) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_ALREADY_PENDING", "Já existe solicitação pendente.", ct);
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE order_item_id = {id} AND establishment_id = {tenant} FOR UPDATE", ct); var production = await db.Set<ProductionItem>().SingleOrDefaultAsync(x => x.OrderItemId == id && x.EstablishmentId == tenant, ct); var disposition = CancellationPolicy.For(production?.Status); if (disposition == CancellationDisposition.Forbidden) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CANCELLATION_NOT_ALLOWED", "Cancelamento não permitido no estado atual.", ct);
        var now = DateTimeOffset.UtcNow; var row = new OrderItemRequest { Id = Guid.NewGuid(), EstablishmentId = tenant, OrderId = order.Id, OrderItemId = item.Id, ReasonCode = request.ReasonCode, CustomerNote = request.CustomerNote, RequestedByDeviceId = deviceContext.Device.Id, RequestedAt = now, Source = "customer", Status = disposition == CancellationDisposition.Automatic ? "approved" : "pending_operational_decision", RequiredApprovalLevel = disposition == CancellationDisposition.KitchenDecision ? "kitchen" : disposition == CancellationDisposition.ManagerDecision ? "manager" : null, DecidedAt = disposition == CancellationDisposition.Automatic ? now : null, DecidedByDeviceId = disposition == CancellationDisposition.Automatic ? deviceContext.Device.Id : null };
        db.Add(row); if (disposition == CancellationDisposition.Automatic) await ApplyCancellation(db, lockedSession, order, item, row, now, ct); else AddEvent(db, tenant, "order-item-cancellation-requested.v1", "OrderItemCancellationRequested", row, item, order, now);
        await db.SaveChangesAsync(ct); var payload = Response(row, item, order, lockedSession, disposition == CancellationDisposition.Automatic); await Record(db, tenant, operation, key, hash, 201, payload, now, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json", statusCode: 201);
    }

    private static async Task<IResult> Withdraw(Guid id, WithdrawCancellationRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, Appizza.Api.IPhase5ChangeHook changeHook, CancellationToken ct)
    {
        if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório."); var device = await Device(principal, db, ct); if (device.Error is not null) return device.Error; var tenant = device.Device!.EstablishmentId!.Value;
        var found = await db.Set<OrderItemRequest>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (found is null || found.RequestedByDeviceId != device.Device.Id) return Results.NotFound(); var operation = found.RequestType == "change" ? "ordering.change.withdraw" : "ordering.cancellation.withdraw"; var hash = Hash(new { id, request });
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return await Replay(tx, replay, ct);
        await LockCommercial(db, (await db.Set<Order>().Where(x => x.Id == found.OrderId).Select(x => x.TableSessionId).SingleAsync(ct)), found.OrderId, found.OrderItemId, ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item_request WHERE id = {id} FOR UPDATE", ct); db.ChangeTracker.Clear(); device = await Device(principal, db, ct); if (device.Error is not null) return device.Error; var row = await db.Set<OrderItemRequest>().SingleAsync(x => x.Id == id && x.EstablishmentId == tenant, ct);
        if (row.RequestedByDeviceId != device.Device!.Id) return Results.NotFound(); if (request.ExpectedVersion is long expected && expected != row.Version) return await Conflict(db, tx, tenant, operation, key, hash, "CONCURRENCY_CONFLICT", "Versão desatualizada.", ct); if (row.Status is not ("pending_customer_confirmation" or "pending_operational_decision")) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_NOT_WITHDRAWABLE", "Solicitação não pode ser retirada.", ct);
        row.Status = "withdrawn"; row.WithdrawnAt = DateTimeOffset.UtcNow; row.DecidedByDeviceId = device.Device.Id; var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == row.OrderItemId, ct); var order = await db.Set<Order>().SingleAsync(x => x.Id == row.OrderId, ct); AddEvent(db, tenant, "order-item-request-withdrawn.v1", "OrderItemRequestWithdrawn", row, item, order, row.WithdrawnAt.Value); await db.SaveChangesAsync(ct); var payload = JsonSerializer.Serialize(new { requestId = row.Id, requestVersion = row.RequestVersion, status = row.Status, version = row.Version }); await Record(db, tenant, operation, key, hash, 200, payload, row.WithdrawnAt.Value, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    private static async Task<IResult> Decide(Guid id, DecideCancellationRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, Appizza.Api.IPhase5ChangeHook changeHook, CancellationToken ct)
    {
        if (request.Decision is not ("approve" or "reject")) return Error(400, "INVALID_DECISION", "Decisão inválida."); if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório."); if (!principal.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var tenant = principal.RequiredGuid("establishment_id"); var user = principal.RequiredGuid("sub"); const string operation = "ordering.cancellation.decide"; var hash = Hash(new { id, request });
        var preview = await db.Set<OrderItemRequest>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (preview is null) return Results.NotFound(); var permission = preview.RequiredApprovalLevel == "manager" ? "ordering.order_item.cancel_ready" : "kitchen.order_item_request.decide"; var denied = await Authorize(principal, db, permission, ct); if (denied is not null) return denied;
        if (preview.RequestType == "change") { var delegated = await Phase5ChangeEndpoints.Decide(preview, request, http, principal, db, changeHook, ct); return delegated.Result; }
        if (request.ProductionAction is not null) return Error(409, "PRODUCTION_ACTION_NOT_ALLOWED", "Ação de produção não se aplica ao cancelamento.");
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return await Replay(tx, replay, ct); var sessionId = await db.Set<Order>().Where(x => x.Id == preview.OrderId).Select(x => x.TableSessionId).SingleAsync(ct); await LockCommercial(db, sessionId, preview.OrderId, preview.OrderItemId, ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item_request WHERE id = {id} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE order_item_id = {preview.OrderItemId} AND establishment_id = {tenant} FOR UPDATE", ct); db.ChangeTracker.Clear(); denied = await Authorize(principal, db, permission, ct); if (denied is not null) return denied;
        var row = await db.Set<OrderItemRequest>().SingleAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (row.Status != "pending_operational_decision") return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_ALREADY_DECIDED", "Solicitação já decidida.", ct); if (request.ExpectedVersion is long expected && expected != row.Version) return await Conflict(db, tx, tenant, operation, key, hash, "CONCURRENCY_CONFLICT", "Versão desatualizada.", ct);
        var production = await db.Set<ProductionItem>().SingleOrDefaultAsync(x => x.OrderItemId == row.OrderItemId && x.EstablishmentId == tenant, ct); var expectedDisposition = CancellationPolicy.For(production?.Status); if ((row.RequiredApprovalLevel == "kitchen" && expectedDisposition != CancellationDisposition.KitchenDecision) || (row.RequiredApprovalLevel == "manager" && expectedDisposition != CancellationDisposition.ManagerDecision)) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CANCELLATION_NOT_ALLOWED", "Estado operacional mudou.", ct);
        var now = DateTimeOffset.UtcNow; row.Status = request.Decision == "approve" ? "approved" : "rejected"; row.DecidedAt = now; row.DecidedByUserId = user; row.DecisionReason = request.Reason; var order = await db.Set<Order>().SingleAsync(x => x.Id == row.OrderId, ct); var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == row.OrderItemId, ct); var session = await db.Set<TableSession>().SingleAsync(x => x.Id == sessionId, ct); if (request.Decision == "approve") await ApplyCancellation(db, session, order, item, row, now, ct); else AddEvent(db, tenant, "order-item-cancellation-rejected.v1", "OrderItemCancellationRejected", row, item, order, now);
        await db.SaveChangesAsync(ct); var payload = Response(row, item, order, session, false); await Record(db, tenant, operation, key, hash, 200, payload, now, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    private static async Task<IResult> List(string? status, string? type, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) { var denied = await AuthorizeAny(principal, db, ["ordering.order_item_request.view", "kitchen.order_item_request.decide"], ct); if (denied is not null) return denied; var tenant = principal.RequiredGuid("establishment_id"); var query = db.Set<OrderItemRequest>().AsNoTracking().Where(x => x.EstablishmentId == tenant); if (!string.IsNullOrWhiteSpace(status)) query = query.Where(x => x.Status == status); if (!string.IsNullOrWhiteSpace(type)) query = query.Where(x => x.RequestType == type); return Results.Ok(await query.OrderBy(x => x.RequestedAt).Select(x => new { x.Id, x.OrderId, x.OrderItemId, x.RequestType, x.Status, x.ReasonCode, x.RequiredApprovalLevel, x.RequestedAt, x.Version }).ToListAsync(ct)); }

    private static async Task ApplyCancellation(AppizzaDbContext db, TableSession session, Order order, OrderItem item, OrderItemRequest request, DateTimeOffset now, CancellationToken ct) { item.CommercialStatus = "cancelled"; item.UpdatedAt = now; order.SubtotalAmount -= item.TotalAmount; order.TotalAmount -= item.TotalAmount; order.UpdatedAt = now; session.SubtotalAmount -= item.TotalAmount; session.TotalAmount -= item.TotalAmount; session.RemainingAmount = Math.Max(0, session.RemainingAmount - item.TotalAmount); session.UpdatedAt = now; var total = await db.Set<OrderItem>().CountAsync(x => x.OrderId == order.Id, ct); var already = await db.Set<OrderItem>().CountAsync(x => x.OrderId == order.Id && x.CommercialStatus == "cancelled", ct); var previous = order.Status; order.Status = CancellationPolicy.OrderStatus(already + 1, total); db.Add(new OrderStatusHistory { Id = Guid.NewGuid(), OrderId = order.Id, PreviousStatus = previous, NewStatus = order.Status, Reason = request.ReasonCode, ChangedAt = now }); AddEvent(db, request.EstablishmentId, "order-item-cancellation-approved.v1", "OrderItemCancellationApproved", request, item, order, now); AddEvent(db, request.EstablishmentId, "order-item-cancelled.v1", "OrderItemCancelled", request, item, order, now); }
    private static void AddEvent(AppizzaDbContext db, Guid tenant, string eventType, string eventName, OrderItemRequest request, OrderItem item, Order order, DateTimeOffset now) { var eventId = Guid.NewGuid(); db.Add(new OutboxMessage { Id = eventId, EstablishmentId = tenant, EventType = eventType, SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId, eventType = eventName, schemaVersion = 1, occurredAtUtc = now, establishmentId = tenant, data = new { requestId = request.Id, requestVersion = request.RequestVersion, orderId = order.Id, orderItemId = item.Id, orderStatus = order.Status, orderItemStatus = item.CommercialStatus } }), OccurredAt = now }); }
    private static string Response(OrderItemRequest request, OrderItem item, Order order, TableSession session, bool automatic) => JsonSerializer.Serialize(new { requestId = request.Id, requestVersion = request.RequestVersion, status = request.Status, automatic, orderItemStatus = item.CommercialStatus, orderStatus = order.Status, totals = new { subtotalAmount = order.SubtotalAmount, totalAmount = order.TotalAmount, sessionTotalAmount = session.TotalAmount, sessionRemainingAmount = session.RemainingAmount }, version = request.Version });
    private static async Task LockCommercial(AppizzaDbContext db, Guid session, Guid order, Guid item, CancellationToken ct) { await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM tables.table_session WHERE id = {session} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.customer_order WHERE id = {order} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item WHERE id = {item} FOR UPDATE", ct); }
    private static async Task<IdempotencyRecord?> Begin(AppizzaDbContext db, Guid tenant, string op, Guid key, string hash, CancellationToken ct) { await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({tenant.ToString("N") + "|" + op + "|" + key.ToString("N")}, 0))", ct); var replay = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == op && x.IdempotencyKey == key.ToString(), ct); if (replay is not null && replay.RequestHash != hash) return new IdempotencyRecord { IdempotencyKey = key.ToString(), OperationType = op, RequestHash = hash, ResponseStatus = 409, ResponsePayload = JsonSerializer.Serialize(new { type = "about:blank", title = "A chave foi usada com outro request.", status = 409, detail = "A chave foi usada com outro request.", errorCode = "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST" }) }; return replay; }
    private static async Task<IResult> Replay(Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction tx, IdempotencyRecord row, CancellationToken ct) { await tx.CommitAsync(ct); return Results.Content(row.ResponsePayload!, row.ResponseStatus == 409 ? "application/problem+json" : "application/json", statusCode: row.ResponseStatus); }
    private static async Task Record(AppizzaDbContext db, Guid tenant, string op, Guid key, string hash, int status, string payload, DateTimeOffset now, CancellationToken ct) { db.Add(new IdempotencyRecord { EstablishmentId = tenant, OperationType = op, IdempotencyKey = key.ToString(), RequestHash = hash, ResponseStatus = status, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); }
    private static async Task<IResult> Conflict(AppizzaDbContext db, Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction tx, Guid tenant, string op, Guid key, string hash, string code, string detail, CancellationToken ct) { var payload = JsonSerializer.Serialize(new { type = "about:blank", title = detail, status = 409, detail, errorCode = code }); await Record(db, tenant, op, key, hash, 409, payload, DateTimeOffset.UtcNow, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/problem+json", statusCode: 409); }
    private static string Hash(object value) => Phase4Pricing.Hash(JsonSerializer.Serialize(value));
    private static async Task<(Device? Device, IResult? Error)> Device(ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) { if (!p.IsTokenType("device")) return (null, Error(403, "INVALID_TOKEN_TYPE", "Token de dispositivo necessário.")); var tenant = p.RequiredGuid("establishment_id"); var id = p.RequiredGuid("sub"); var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (device is null) return (null, Results.NotFound()); if (device.Status == "blocked") return (null, Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.")); if (device.Status != "active" || device.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != p.FindFirstValue("credential_version")) return (null, Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.")); return (device, null); }
    private static async Task<IResult?> Authorize(ClaimsPrincipal p, AppizzaDbContext db, string permission, CancellationToken ct) => await AuthorizeAny(p, db, [permission], ct);
    private static async Task<IResult?> AuthorizeAny(ClaimsPrincipal p, AppizzaDbContext db, string[] permissions, CancellationToken ct) { if (!p.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var user = p.RequiredGuid("sub"); var tenant = p.RequiredGuid("establishment_id"); if (!await db.Set<User>().AnyAsync(x => x.Id == user && x.EstablishmentId == tenant && x.Status == "active", ct)) return Results.NotFound(); var resolved = await PermissionResolver.ResolveAsync(db, user, DateTimeOffset.UtcNow, ct); return permissions.Any(resolved.Contains) ? null : Error(403, "INSUFFICIENT_PERMISSION", "Permissão insuficiente."); }
    private static IResult Error(int status, string code, string detail) => Results.Problem(statusCode: status, title: detail, detail: detail, extensions: new Dictionary<string, object?> { ["errorCode"] = code });
}
