using System.Security.Claims;
using System.Text.Json;
using Appizza.Modules.Catalog;
using Appizza.Modules.Devices;
using Appizza.Modules.Establishments;
using Appizza.Modules.Kitchen;
using Appizza.Modules.Ordering;
using Appizza.Modules.Tables;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api;

public interface IPhase4OrderingHook { Task ReachAsync(string stage, Guid tenant, Guid sessionId, Guid deviceId, CancellationToken cancellationToken); }
public sealed class Phase4OrderingHook : IPhase4OrderingHook { public Task ReachAsync(string stage, Guid tenant, Guid sessionId, Guid deviceId, CancellationToken cancellationToken) => Task.CompletedTask; }

#pragma warning disable CA1826

public static class Phase4Endpoints
{
    public static IEndpointRouteBuilder MapPhase4Endpoints(this IEndpointRouteBuilder app)
    {
        var device = app.MapGroup("/api/v1/table-device").RequireAuthorization();
        device.MapPost("/cart/simulate", Simulate);
        device.MapPost("/orders", Submit);
        device.MapGet("/orders/submissions/{idempotencyKey}", Reconcile);
        var kitchen = app.MapGroup("/api/v1/operations/kitchen").RequireAuthorization();
        kitchen.MapGet("/stations", Stations);
        kitchen.MapGet("/production-items", Queue);
        kitchen.MapGet("/production-items/{id:guid}", Detail);
        kitchen.MapPost("/production-items/{id:guid}/accept", AcceptRecorded);
        return app;
    }

    private static async Task<IResult> Simulate(CartSimulationRequest request, ClaimsPrincipal principal, AppizzaDbContext db, IPhase4OrderingHook hook, CancellationToken ct)
    {
        var context = await DeviceContext(principal, request.SessionId, db, ct); if (context.Error is not null) return context.Error; var tenant = context.Device!.EstablishmentId!.Value; await hook.ReachAsync("simulation-before-read", tenant, request.SessionId, context.Device.Id, ct); await using var tx = await db.Database.BeginTransactionAsync(ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM catalog.catalog_state WHERE establishment_id = {tenant} FOR SHARE", ct); await hook.ReachAsync("simulation-catalog-locked", tenant, request.SessionId, context.Device.Id, ct);
        var state = await db.Set<CatalogState>().AsNoTracking().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct); if (state?.CurrentPublishedRevisionId is not Guid revisionId) return Error(409, "CATALOG_NOT_PUBLISHED", "Não existe catálogo publicado.");
        var revision = await db.Set<CatalogRevision>().AsNoTracking().SingleAsync(x => x.Id == revisionId && x.EstablishmentId == tenant && x.Status == "published", ct); using var catalog = JsonDocument.Parse(revision.Snapshot);
        var unavailableProducts = await db.Set<ProductAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductId).ToHashSetAsync(ct); var unavailableVariants = await db.Set<ProductVariantAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductVariantId).ToHashSetAsync(ct); var unavailableIngredients = await db.Set<IngredientAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.IngredientId).ToHashSetAsync(ct);
        var result = Phase4Pricing.Simulate(catalog.RootElement, request, unavailableProducts, unavailableVariants, unavailableIngredients); var intentJson = JsonSerializer.Serialize(request); var resultJson = JsonSerializer.Serialize(result); var requestHash = Phase4Pricing.Hash(intentJson); var simulationVersion = $"sha256-v1:{Phase4Pricing.MaterialHash(result)}"; var validity = await SimulationValidity(db, tenant, ct); var now = DateTimeOffset.UtcNow;
        var simulation = new CartSimulation { Id = Guid.NewGuid(), EstablishmentId = tenant, SourceDeviceId = context.Device.Id, TableSessionId = request.SessionId, LocalCartId = request.LocalCartId, CatalogRevisionId = revision.Id, CatalogVersion = state.CatalogVersion, AvailabilityVersion = state.AvailabilityVersion, RequestHash = requestHash, SimulationVersion = simulationVersion, RequiresReview = result.RequiresReview, CanSubmit = result.CanSubmit, IntentSnapshot = intentJson, ResultSnapshot = resultJson, CreatedAt = now, ValidUntil = now.AddSeconds(validity) }; db.Add(simulation); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct);
        return Results.Ok(new { simulationId = simulation.Id, simulation.SimulationVersion, simulation.ValidUntil, catalogVersion = state.CatalogVersion, availabilityVersion = state.AvailabilityVersion, result.Items, totals = new { result.SubtotalAmount, result.DiscountAmount, result.TotalAmount }, result.Issues, result.RequiresReview, result.CanSubmit });
    }

    private static async Task<IResult> Submit(SubmitOrderRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, IPhase4OrderingHook hook, CancellationToken ct)
    {
        if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório.");
        var context = await DeviceContext(principal, request.SessionId, db, ct); if (context.Error is not null) return context.Error; var tenant = context.Device!.EstablishmentId!.Value; var requestJson = JsonSerializer.Serialize(request); var requestHash = Phase4Pricing.Hash(requestJson); const string operation = "ordering.submit";
        await using var tx = await db.Database.BeginTransactionAsync(ct); await hook.ReachAsync("submission-before-locks", tenant, request.SessionId, context.Device.Id, ct); await AdvisoryLock(db, $"{tenant:N}|{operation}|{key:N}", ct);
        var replay = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == operation && x.IdempotencyKey == key.ToString(), ct); if (replay is not null) { if (replay.RequestHash != requestHash) return Error(409, "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST", "A chave foi usada com outro request."); await tx.CommitAsync(ct); return Results.Content(replay.ResponsePayload!, "application/json", statusCode: replay.ResponseStatus ?? 201); }
        await AdvisoryLock(db, $"{tenant:N}|ordering.client-submission|{context.Device.Id:N}|{request.ClientSubmissionId:N}", ct);
        var existing = await db.Set<Order>().AsNoTracking().SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.SourceDeviceId == context.Device.Id && x.ClientSubmissionId == request.ClientSubmissionId, ct); if (existing is not null) { var existingPayload = await OrderPayload(db, existing, ct); db.Add(new IdempotencyRecord { EstablishmentId = tenant, IdempotencyKey = key.ToString(), OperationType = operation, RequestHash = requestHash, ResponseStatus = 201, ResponsePayload = existingPayload, CreatedAt = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(existingPayload, "application/json", statusCode: 201); }
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM tables.table_session WHERE id = {request.SessionId} AND establishment_id = {tenant} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM devices.device WHERE id = {context.Device.Id} AND establishment_id = {tenant} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM catalog.catalog_state WHERE establishment_id = {tenant} FOR SHARE", ct); await hook.ReachAsync("submission-locks-acquired", tenant, request.SessionId, context.Device.Id, ct); await db.Entry(context.Device).ReloadAsync(ct);
        var session = await db.Set<TableSession>().SingleOrDefaultAsync(x => x.Id == request.SessionId && x.EstablishmentId == tenant, ct); if (session?.Status != "open") return Error(409, "SESSION_NOT_OPEN", "A sessão não permite novos pedidos."); var currentDevice = await db.Set<Device>().SingleAsync(x => x.Id == context.Device.Id && x.EstablishmentId == tenant, ct); if (currentDevice.Status != "active" || currentDevice.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != principal.FindFirstValue("credential_version")) return Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.");
        var simulation = await db.Set<CartSimulation>().SingleOrDefaultAsync(x => x.Id == request.SimulationId && x.EstablishmentId == tenant && x.SourceDeviceId == currentDevice.Id && x.TableSessionId == request.SessionId && x.LocalCartId == request.LocalCartId, ct); if (simulation is null) return Error(404, "SIMULATION_NOT_FOUND", "Simulação não encontrada."); if (simulation.ValidUntil <= DateTimeOffset.UtcNow) return Error(409, "SIMULATION_EXPIRED", "Simulação expirada."); if (simulation.SimulationVersion != request.SimulationVersion) return Error(409, "SIMULATION_VERSION_MISMATCH", "Versão da simulação diverge."); if (simulation.RequiresReview && !request.AcceptedReview) return Error(409, "REVIEW_CONFIRMATION_REQUIRED", "Confirme a revisão exata.");
        var intent = JsonSerializer.Deserialize<CartSimulationRequest>(simulation.IntentSnapshot)!; var state = await db.Set<CatalogState>().SingleAsync(x => x.EstablishmentId == tenant, ct); var revision = await db.Set<CatalogRevision>().AsNoTracking().SingleAsync(x => x.Id == state.CurrentPublishedRevisionId && x.EstablishmentId == tenant && x.Status == "published", ct); using var catalog = JsonDocument.Parse(revision.Snapshot); var unavailableProducts = await db.Set<ProductAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductId).ToHashSetAsync(ct); var unavailableVariants = await db.Set<ProductVariantAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductVariantId).ToHashSetAsync(ct); var unavailableIngredients = await db.Set<IngredientAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.IngredientId).ToHashSetAsync(ct); var definitive = Phase4Pricing.Simulate(catalog.RootElement, intent, unavailableProducts, unavailableVariants, unavailableIngredients); if (!definitive.CanSubmit) return Error(409, definitive.Issues.First().ErrorCode, definitive.Issues.First().Message); var simulatedResult = JsonSerializer.Deserialize<AuthoritativeCartResult>(simulation.ResultSnapshot)!; if (!Phase4Pricing.MateriallyEquivalent(simulatedResult, definitive)) return Error(409, "ORDER_REQUIRES_REVIEW", "A configuração autoritativa mudou; simule novamente.");
        var stationIds = definitive.Items.Where(x => x.PreparationStationId is not null).Select(x => x.PreparationStationId!.Value).Distinct().ToArray(); var validStations = await db.Set<Station>().Where(x => x.EstablishmentId == tenant && x.Status == "active" && stationIds.Contains(x.Id)).Select(x => x.Id).ToHashSetAsync(ct); var defaultStation = await db.Set<Station>().SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.Status == "active" && x.IsDefault, ct); if (definitive.Items.Any(x => x.PreparationStationId is null || !validStations.Contains(x.PreparationStationId.Value)) && defaultStation is null) return Error(409, "NO_ACTIVE_PRODUCTION_STATION", "Não existe estação ativa para o intake.");
        var now = DateTimeOffset.UtcNow; var order = new Order { Id = Guid.NewGuid(), EstablishmentId = tenant, TableSessionId = session.Id, SourceDeviceId = currentDevice.Id, ClientSubmissionId = request.ClientSubmissionId, Status = "submitted", SubtotalAmount = definitive.SubtotalAmount, DiscountAmount = 0, TotalAmount = definitive.TotalAmount, SubmittedAt = now, CreatedAt = now, UpdatedAt = now }; db.Add(order);
        foreach (var item in definitive.Items) { var row = new OrderItem { Id = Guid.NewGuid(), OrderId = order.Id, LocalCartItemId = item.LocalCartItemId, ProductId = item.ProductId, ProductVariantId = item.ProductVariantId, ProductType = item.ProductType, ProductName = item.ProductName, VariantName = item.VariantName, Quantity = item.Quantity, UnitAmount = item.UnitAmount, TotalAmount = item.TotalAmount, ConfigurationVersion = item.ConfigurationVersion, CatalogRevisionId = revision.Id, CatalogVersion = state.CatalogVersion, AvailabilityVersion = state.AvailabilityVersion, Snapshot = JsonSerializer.Serialize(new { snapshotSchemaVersion = 1, item.Snapshot, catalogRevisionId = revision.Id, catalogVersion = state.CatalogVersion, availabilityVersion = state.AvailabilityVersion, item.ConfigurationVersion }), CreatedAt = now, UpdatedAt = now }; db.Add(row); AddStructured(db, row.Id, item.Configuration, item.Snapshot); }
        session.SubtotalAmount += order.SubtotalAmount; session.TotalAmount += order.TotalAmount; session.RemainingAmount += order.TotalAmount; session.UpdatedAt = now; var eventId = Guid.NewGuid(); db.Add(new OutboxMessage { Id = eventId, EstablishmentId = tenant, EventType = "order-submitted.v1", SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId, eventType = "OrderSubmitted", schemaVersion = 1, occurredAtUtc = now, establishmentId = tenant, data = new { orderId = order.Id, tableSessionId = session.Id, sourceDeviceId = currentDevice.Id, order.SubtotalAmount, order.DiscountAmount, order.TotalAmount, itemCount = definitive.Items.Count } }), OccurredAt = now });
        await db.SaveChangesAsync(ct); var payload = JsonSerializer.Serialize(new { order = new { id = order.Id, number = order.OrderNumber, status = order.Status, submittedAt = order.SubmittedAt, totalAmount = order.TotalAmount, kitchenIntakeStatus = "pendingKitchenIntake" }, session = new { id = session.Id, totalAmount = session.TotalAmount, remainingAmount = session.RemainingAmount, version = session.Version }, nextStep = "orderStatus" }); db.Add(new IdempotencyRecord { EstablishmentId = tenant, IdempotencyKey = key.ToString(), OperationType = operation, RequestHash = requestHash, ResponseStatus = 201, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json", statusCode: 201);
    }

    private static async Task<IResult> Reconcile(string idempotencyKey, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        if (!principal.IsTokenType("device") || !Guid.TryParse(idempotencyKey, out _)) return Results.NotFound(); var tenant = principal.RequiredGuid("establishment_id"); var device = principal.RequiredGuid("sub"); var record = await db.IdempotencyRecords.AsNoTracking().SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == "ordering.submit" && x.IdempotencyKey == idempotencyKey, ct); if (record?.ResponsePayload is null) return Results.NotFound(); using var payload = JsonDocument.Parse(record.ResponsePayload); var orderId = payload.RootElement.GetProperty("order").GetProperty("id").GetGuid(); if (!await db.Set<Order>().AnyAsync(x => x.Id == orderId && x.EstablishmentId == tenant && x.SourceDeviceId == device, ct)) return Results.NotFound(); return Results.Content(record.ResponsePayload, "application/json", statusCode: record.ResponseStatus ?? 201);
    }
    private static async Task<IResult> Stations(ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) { var denied = await Authorize(p, db, "kitchen.queue.view", ct); if (denied is not null) return denied; var tenant = p.RequiredGuid("establishment_id"); return Results.Ok(await db.Set<Station>().AsNoTracking().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.DisplayOrder).Select(x => new { x.Id, x.Name, x.IsDefault }).ToListAsync(ct)); }
    private static async Task<IResult> Queue(Guid? stationId, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) { var denied = await Authorize(p, db, "kitchen.queue.view", ct); if (denied is not null) return denied; var tenant = p.RequiredGuid("establishment_id"); if (stationId is Guid station && !await db.Set<Station>().AnyAsync(x => x.Id == station && x.EstablishmentId == tenant, ct)) return Results.NotFound(); var query = db.Set<ProductionItem>().AsNoTracking().Where(x => x.EstablishmentId == tenant); if (stationId is not null) query = query.Where(x => x.StationId == stationId); return Results.Ok(await query.OrderBy(x => x.QueuePosition).Select(x => new { x.Id, x.OrderItemId, x.StationId, x.Status, x.QueuePosition, x.RequiresProduction, x.ReceivedAt, x.PreparationStartedAt, x.CurrentAttemptNumber, x.Version }).ToListAsync(ct)); }
    private static async Task<IResult> Detail(Guid id, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) { var denied = await Authorize(p, db, "kitchen.production.view", ct); if (denied is not null) return denied; var tenant = p.RequiredGuid("establishment_id"); var row = await (from production in db.Set<ProductionItem>() join item in db.Set<OrderItem>() on production.OrderItemId equals item.Id where production.Id == id && production.EstablishmentId == tenant select new { production.Id, production.Status, production.StationId, production.QueuePosition, production.PreparationStartedAt, production.ReadyAt, production.CurrentAttemptNumber, production.Version, item.ProductName, item.VariantName, item.Quantity, item.Snapshot }).SingleOrDefaultAsync(ct); if (row is null) return Results.NotFound(); var attempts = await db.Set<ProductionAttempt>().AsNoTracking().Where(x => x.ProductionItemId == id).OrderBy(x => x.AttemptNumber).ToListAsync(ct); var pauses = await db.Set<ProductionPause>().AsNoTracking().Where(x => x.ProductionItemId == id).OrderBy(x => x.PausedAt).ToListAsync(ct); var history = await db.Set<ProductionStatusHistory>().AsNoTracking().Where(x => x.ProductionItemId == id).OrderBy(x => x.ChangedAt).ToListAsync(ct); return Results.Ok(new { item = row, attempts, pauses, history }); }
    private static async Task<IResult> Accept(Guid id, HttpRequest http, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(p, db, "kitchen.production.accept", ct); if (denied is not null) return denied; if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório."); var tenant = p.RequiredGuid("establishment_id"); var user = p.RequiredGuid("sub"); const string op = "kitchen.accept"; var hash = Phase4Pricing.Hash(id.ToString("N")); await using var tx = await db.Database.BeginTransactionAsync(ct); await AdvisoryLock(db, $"{tenant:N}|{op}|{key:N}", ct); var replay = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == op && x.IdempotencyKey == key.ToString(), ct); if (replay is not null) { if (replay.RequestHash != hash) return Error(409, "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST", "Chave reutilizada."); await tx.CommitAsync(ct); return Results.Content(replay.ResponsePayload!, "application/json"); }
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE id = {id} AND establishment_id = {tenant} FOR UPDATE", ct); var item = await db.Set<ProductionItem>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (item is null) return Results.NotFound(); if (item.Status != "awaiting_acceptance") return Error(409, "PRODUCTION_ITEM_ALREADY_ACCEPTED", "Item já aceito."); var now = DateTimeOffset.UtcNow; db.Add(new ProductionStatusHistory { Id = Guid.NewGuid(), ProductionItemId = id, PreviousStatus = "awaiting_acceptance", NewStatus = "accepted", UserId = user, ChangedAt = now }); db.Add(new ProductionStatusHistory { Id = Guid.NewGuid(), ProductionItemId = id, PreviousStatus = "accepted", NewStatus = "awaiting_preparation", UserId = user, ChangedAt = now }); item.Status = "awaiting_preparation"; item.AcceptedAt = now; item.AcceptedByUserId = user; item.UpdatedAt = now; var eventId = Guid.NewGuid(); db.Add(new OutboxMessage { Id = eventId, EstablishmentId = tenant, EventType = "production-item-accepted.v1", SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId, eventType = "ProductionItemAccepted", schemaVersion = 1, occurredAtUtc = now, establishmentId = tenant, data = new { productionItemId = id, resultingStatus = item.Status } }), OccurredAt = now }); var payload = JsonSerializer.Serialize(new { item.Id, item.Status, item.AcceptedAt }); db.Add(new IdempotencyRecord { EstablishmentId = tenant, IdempotencyKey = key.ToString(), OperationType = op, RequestHash = hash, ResponseStatus = 200, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    private static async Task<(Device? Device, IResult? Error)> DeviceContext(ClaimsPrincipal principal, Guid sessionId, AppizzaDbContext db, CancellationToken ct) { if (!principal.IsTokenType("device")) return (null, Error(403, "INVALID_TOKEN_TYPE", "Token de dispositivo necessário.")); var id = principal.RequiredGuid("sub"); var tenant = principal.RequiredGuid("establishment_id"); var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (device is null) return (null, Results.NotFound()); if (device.Status == "blocked") return (null, Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.")); if (device.Status != "active" || device.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != principal.FindFirstValue("credential_version")) return (null, Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.")); var binding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == id && x.UnboundAt == null, ct); var session = await db.Set<TableSession>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == sessionId && x.EstablishmentId == tenant, ct); if (binding is null || session is null || binding.DiningTableId != session.DiningTableId) return (null, Results.NotFound()); if (session.Status != "open") return (null, Error(409, "SESSION_NOT_OPEN", "A sessão não permite pedidos.")); return (device, null); }
    private static async Task<int> SimulationValidity(AppizzaDbContext db, Guid tenant, CancellationToken ct) { var value = await db.Set<EstablishmentSetting>().Where(x => x.EstablishmentId == tenant && x.SettingKey == Phase4Ordering.SimulationValiditySetting).Select(x => x.SettingValue).SingleOrDefaultAsync(ct); return int.TryParse(value, out var seconds) && seconds > 0 ? seconds : Phase4Ordering.DefaultSimulationValiditySeconds; }
    private static async Task<IResult?> Authorize(ClaimsPrincipal p, AppizzaDbContext db, string permission, CancellationToken ct) { if (!p.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var user = p.RequiredGuid("sub"); var tenant = p.RequiredGuid("establishment_id"); if (!await db.Set<Appizza.Modules.Identity.User>().AnyAsync(x => x.Id == user && x.EstablishmentId == tenant && x.Status == "active", ct)) return Results.NotFound(); var permissions = await PermissionResolver.ResolveAsync(db, user, DateTimeOffset.UtcNow, ct); return permissions.Contains(permission) ? null : Error(403, "INSUFFICIENT_PERMISSION", "Permissão insuficiente."); }
    private static Task<int> AdvisoryLock(AppizzaDbContext db, string identity, CancellationToken ct) => db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({identity}, 0))", ct);
    private static async Task<string> OrderPayload(AppizzaDbContext db, Order order, CancellationToken ct) { var session = await db.Set<TableSession>().AsNoTracking().SingleAsync(x => x.Id == order.TableSessionId, ct); return JsonSerializer.Serialize(new { order = new { id = order.Id, number = order.OrderNumber, status = order.Status, submittedAt = order.SubmittedAt, totalAmount = order.TotalAmount, kitchenIntakeStatus = "pendingKitchenIntake" }, session = new { id = session.Id, totalAmount = session.TotalAmount, remainingAmount = session.RemainingAmount, version = session.Version }, nextStep = "orderStatus" }); }
    private static void AddStructured(AppizzaDbContext db, Guid itemId, JsonElement configuration, JsonElement snapshot)
    {
        var published = Value(snapshot, "publishedConfiguration") ?? default;
        if (Try(configuration, "notes", out var notes)) { var position = 0; foreach (var note in notes.EnumerateArray()) db.Add(new OrderItemNote { Id = Guid.NewGuid(), OrderItemId = itemId, Position = ++position, Note = note.GetString() ?? "" }); }
        if (Try(configuration, "ingredients", out var ingredients)) foreach (var value in ingredients.EnumerateArray())
        {
            var id = Guid.Parse(Value(value, "ingredientId")!.Value.GetString()!); var action = Value(value, "action")!.Value.GetString()!; var quantity = Value(value, "quantity")?.GetDecimal() ?? 1;
            var definition = FindIn(published, "ingredients", id); var link = FindIn(published, "productIngredients", id, "ingredientId");
            db.Add(new OrderItemIngredient { Id = Guid.NewGuid(), OrderItemId = itemId, IngredientId = id, Name = Text(definition, "name") ?? "Ingrediente", Action = action, Quantity = quantity, AdditionalAmount = action == "add" ? Number(link, "additionalPrice") * quantity : 0 });
        }
        if (Try(configuration, "selectedOptions", out var options)) foreach (var value in options.EnumerateArray())
        {
            var id = Guid.Parse(Value(value, "optionId")!.Value.GetString()!); var quantity = Value(value, "quantity")?.GetInt32() ?? 1; var definition = FindNested(published, "customization", "options", id);
            db.Add(new OrderItemOption { Id = Guid.NewGuid(), OrderItemId = itemId, OptionId = id, Name = Text(definition, "name") ?? "Opção", Quantity = quantity, AdditionalAmount = Number(definition, "baseAdditionalPrice") * quantity });
        }
        if (Try(configuration, "pizza", out var pizza))
        {
            var sizeId = Guid.Parse(Value(pizza, "sizeId")!.Value.GetString()!); var size = FindNested(published, "pizza", "sizes", sizeId); var doughId = GuidText(pizza, "doughId"); var crustId = GuidText(pizza, "crustId"); var fractions = Value(pizza, "fractions")!.Value;
            db.Add(new OrderItemPizzaConfiguration { OrderItemId = itemId, SizeId = sizeId, SizeName = Text(size, "name") ?? "Tamanho", DoughId = doughId, DoughName = Text(FindNested(published, "pizza", "doughs", doughId), "name"), CrustId = crustId, CrustName = Text(FindNested(published, "pizza", "crusts", crustId), "name"), FractionCount = fractions.GetArrayLength() });
            var position = 0; foreach (var fraction in fractions.EnumerateArray()) { var flavorId = GuidText(fraction, "flavorId"); var flavor = FindNested(published, "pizza", "flavors", flavorId); var flavorProductId = GuidText(flavor, "productId"); var flavorProduct = FindIn(published, "products", flavorProductId); var price = FindNestedPair(published, "pizza", "flavorPrices", "pizzaFlavorId", flavorId, "pizzaSizeId", sizeId); var customPrice = FindNestedPair(published, "pizza", "customBasePrices", "customPizzaProductId", GuidText(Value(published, "product"), "id"), "pizzaSizeId", sizeId); db.Add(new OrderItemPizzaFraction { Id = Guid.NewGuid(), OrderItemId = itemId, Position = ++position, FlavorId = flavorId, FlavorName = Text(flavorProduct, "name"), IsCustom = flavorId is null, FractionDenominator = fractions.GetArrayLength(), ReferenceAmount = flavorId is null ? Number(customPrice, "basePrice") : Number(price, "price"), Configuration = fraction.GetRawText() }); }
        }
        if (Try(configuration, "combo", out var combo) && Try(combo, "groups", out var groups)) foreach (var group in groups.EnumerateArray()) if (Try(group, "selections", out var selections)) foreach (var value in selections.EnumerateArray())
        {
            var itemDefinition = FindNested(published, "combos", "items", Guid.Parse(Value(value, "comboGroupItemId")!.Value.GetString()!)); var quantity = Value(value, "quantity")?.GetInt32() ?? 1; var selectedVariant = GuidText(itemDefinition, "productVariantId"); var variant = FindIn(published, "allVariants", selectedVariant); var selectedProduct = GuidText(itemDefinition, "productId") ?? GuidText(variant, "productId");
            db.Add(new OrderItemComboSelection { Id = Guid.NewGuid(), OrderItemId = itemId, ComboGroupId = Guid.Parse(Value(group, "groupId")!.Value.GetString()!), ComboGroupItemId = Guid.Parse(Value(value, "comboGroupItemId")!.Value.GetString()!), SelectedProductId = selectedProduct, SelectedVariantId = selectedVariant, Quantity = quantity, ComponentAmount = (Number(variant, "basePrice") + Number(itemDefinition, "additionalPrice")) * quantity, Configuration = Value(value, "configuration")?.GetRawText() ?? "{}" });
        }
    }

    private static JsonElement? FindIn(JsonElement? root, string collection, Guid? id, string key = "id") => id is null || root is null || !Try(root.Value, collection, out var rows) ? null : rows.EnumerateArray().Cast<JsonElement?>().FirstOrDefault(x => GuidText(x, key) == id);
    private static JsonElement? FindNested(JsonElement? root, string parent, string collection, Guid? id) => root is null || !Try(root.Value, parent, out var nested) ? null : FindIn(nested, collection, id);
    private static JsonElement? FindNestedPair(JsonElement? root, string parent, string collection, string firstKey, Guid? first, string secondKey, Guid? second) => root is null || !Try(root.Value, parent, out var nested) || !Try(nested, collection, out var rows) ? null : rows.EnumerateArray().Cast<JsonElement?>().FirstOrDefault(x => GuidText(x, firstKey) == first && GuidText(x, secondKey) == second);
    private static Guid? GuidText(JsonElement? value, string name) => value is not null && Value(value.Value, name) is JsonElement result && result.ValueKind != JsonValueKind.Null && Guid.TryParse(result.GetString(), out var id) ? id : null;
    private static string? Text(JsonElement? value, string name) => value is not null && Value(value.Value, name) is JsonElement result && result.ValueKind != JsonValueKind.Null ? result.GetString() : null;
    private static decimal Number(JsonElement? value, string name) => value is not null && Value(value.Value, name) is JsonElement result && result.TryGetDecimal(out var number) ? number : 0;
    private static bool Try(JsonElement element, string name, out JsonElement value) { var found = Value(element, name); value = found ?? default; return found is not null; }
    private static JsonElement? Value(JsonElement element, string name) { if (element.ValueKind == JsonValueKind.Object) foreach (var p in element.EnumerateObject()) if (p.Name.Equals(name, StringComparison.OrdinalIgnoreCase)) return p.Value; return null; }
    private static async Task<IResult> AcceptRecorded(Guid id, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "kitchen.production.accept", ct);
        if (denied is not null) return denied;
        if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório.");
        var tenant = principal.RequiredGuid("establishment_id"); var user = principal.RequiredGuid("sub"); const string operation = "kitchen.accept"; var hash = Phase4Pricing.Hash(id.ToString("N"));
        await using var tx = await db.Database.BeginTransactionAsync(ct); await AdvisoryLock(db, $"{tenant:N}|{operation}|{key:N}", ct);
        var replay = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == operation && x.IdempotencyKey == key.ToString(), ct);
        if (replay is not null) { if (replay.RequestHash != hash) return Error(409, "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST", "Chave reutilizada."); await tx.CommitAsync(ct); return Results.Content(replay.ResponsePayload!, replay.ResponseStatus == 409 ? "application/problem+json" : "application/json", statusCode: replay.ResponseStatus); }
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE id = {id} AND establishment_id = {tenant} FOR UPDATE", ct);
        var item = await db.Set<ProductionItem>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (item is null) return Results.NotFound();
        if (item.Status != "awaiting_acceptance") { var conflict = JsonSerializer.Serialize(new { type = "about:blank", title = "Item já aceito.", status = 409, detail = "Item já aceito.", errorCode = "PRODUCTION_ITEM_ALREADY_ACCEPTED" }); db.Add(new IdempotencyRecord { EstablishmentId = tenant, IdempotencyKey = key.ToString(), OperationType = operation, RequestHash = hash, ResponseStatus = 409, ResponsePayload = conflict, CreatedAt = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(conflict, "application/problem+json", statusCode: 409); }
        var now = DateTimeOffset.UtcNow; db.Add(new ProductionStatusHistory { Id = Guid.NewGuid(), ProductionItemId = id, PreviousStatus = "awaiting_acceptance", NewStatus = "accepted", UserId = user, ChangedAt = now }); db.Add(new ProductionStatusHistory { Id = Guid.NewGuid(), ProductionItemId = id, PreviousStatus = "accepted", NewStatus = "awaiting_preparation", UserId = user, ChangedAt = now }); item.Status = "awaiting_preparation"; item.AcceptedAt = now; item.AcceptedByUserId = user; item.UpdatedAt = now; var eventId = Guid.NewGuid(); db.Add(new OutboxMessage { Id = eventId, EstablishmentId = tenant, EventType = "production-item-accepted.v1", SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId, eventType = "ProductionItemAccepted", schemaVersion = 1, occurredAtUtc = now, establishmentId = tenant, data = new { productionItemId = id, resultingStatus = item.Status } }), OccurredAt = now }); var payload = JsonSerializer.Serialize(new { id = item.Id, status = item.Status, acceptedAt = item.AcceptedAt }); db.Add(new IdempotencyRecord { EstablishmentId = tenant, IdempotencyKey = key.ToString(), OperationType = operation, RequestHash = hash, ResponseStatus = 200, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    private static IResult Error(int status, string code, string detail) => Results.Problem(statusCode: status, title: detail, detail: detail, extensions: new Dictionary<string, object?> { ["errorCode"] = code });
}
