using System.Text.Json;
using Appizza.Modules.Catalog;
using Appizza.Modules.Kitchen;
using Appizza.Modules.Ordering;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api.IntegrationTests;

/// <summary>Prepares complex orders through the public HTTP workflow; assertions stay in the tests.</summary>
internal sealed class ComplexOrderFixtureBuilder(Phase1ApiFixture fixture)
{
    internal async Task<NestedComboCatalogScenario> BuildNestedComboCatalogOnlyAsync()
    {
        var tenant = await fixture.CreateTenantAsync(2, 1);
        var component = await CreateProduct(tenant.AccessToken, "simple", "Nested component", null, false);
        var componentVariant = await CreateVariant(tenant.AccessToken, component, "Standard", 5m);
        var child = await CreateProduct(tenant.AccessToken, "combo", "Nested child", null, false);
        await CreateVariant(tenant.AccessToken, child, "Standard", 0m);
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{child}/combo-configuration", new { pricingMode = "fixed_price", fixedPrice = 5m, groups = new[] { new { name = "Child", minimumSelections = 1, maximumSelections = 1, displayOrder = 1, items = new[] { new { productId = component, productVariantId = (Guid?)componentVariant, additionalPrice = 0m, displayOrder = 1 } } } } }, tenant.AccessToken)).EnsureSuccessStatusCode();
        (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        var parent = await CreateProduct(tenant.AccessToken, "combo", "Nested parent", null, false);
        await CreateVariant(tenant.AccessToken, parent, "Standard", 0m);
        var alternative = await CreateProduct(tenant.AccessToken, "simple", "Alternative", null, false);
        var alternativeVariant = await CreateVariant(tenant.AccessToken, alternative, "Standard", 20m);
        var put = await fixture.PutAsync($"api/v1/operations/catalog/products/{parent}/combo-configuration", new { pricingMode = "fixed_price", fixedPrice = 25m, groups = new object[] { new { name = "Main", minimumSelections = 1, maximumSelections = 1, displayOrder = 1, items = new object[] { new { productId = alternative, productVariantId = (Guid?)alternativeVariant, additionalPrice = 1m, displayOrder = 1 }, new { productId = child, productVariantId = (Guid?)null, additionalPrice = 1m, displayOrder = 2 } } } } }, tenant.AccessToken);
        put.EnsureSuccessStatusCode();
        Guid groupId, itemId, normalId, parentVariant;
        await using (var db = fixture.CreateDbContext()) { var comboId = await db.Set<Combo>().Where(x => x.ProductId == parent).Select(x => x.Id).SingleAsync(); groupId = await db.Set<ComboGroup>().Where(x => x.ComboId == comboId).Select(x => x.Id).SingleAsync(); itemId = await db.Set<ComboGroupItem>().Where(x => x.ComboGroupId == groupId && x.ProductId == child).Select(x => x.Id).SingleAsync(); normalId = await db.Set<ComboGroupItem>().Where(x => x.ComboGroupId == groupId && x.ProductVariantId == alternativeVariant).Select(x => x.Id).SingleAsync(); parentVariant = await db.Set<ProductVariant>().Where(x => x.ProductId == parent).Select(x => x.Id).SingleAsync(); }
        (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        return new(tenant.EstablishmentId, child, parent, groupId, itemId, normalId, alternativeVariant, parentVariant, tenant.TableIds[0], tenant.AccessToken);
    }
    internal async Task<BuildYourOwnPizzaScenario> BuildYourOwnPizzaAsync()
    {
        var tenant = await fixture.CreateTenantAsync(2, 1); var custom = await CreateProduct(tenant.AccessToken, "custom_pizza", "Build Your Own", "Historical base", true); var variant = await CreateVariant(tenant.AccessToken, custom, "Grande", 0m); var flavorProduct = await CreateProduct(tenant.AccessToken, "simple", "Portuguesa", "Published flavor", false); await CreateVariant(tenant.AccessToken, flavorProduct, "Integral", 0m);
        var size = await PostId(tenant.AccessToken, "api/v1/operations/catalog/pizza-sizes", new { name = "Grande", shortName = "G", sliceCount = 8, diameterCm = 35m, displayOrder = 1 }); var dough = await PostId(tenant.AccessToken, "api/v1/operations/catalog/doughs", new { name = "Fina", description = "Fina", isDefault = true }); var crust = await PostId(tenant.AccessToken, "api/v1/operations/catalog/crusts", new { name = "Cheddar", description = "Cheddar", imageMediaId = (Guid?)null });
        var ingredient = await PostId(tenant.AccessToken, "api/v1/operations/catalog/ingredients", new { name = "Tomate seco", kitchenName = "Tomate seco", description = "Historical", defaultAdditionalPrice = 2m, unitOfMeasure = "unit", imageMediaId = (Guid?)null }); var secondIngredient = await PostId(tenant.AccessToken, "api/v1/operations/catalog/ingredients", new { name = "Azeitona", kitchenName = "Azeitona", description = "Historical", defaultAdditionalPrice = 3m, unitOfMeasure = "unit", imageMediaId = (Guid?)null });
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{custom}/ingredients", new { items = new[] { new { ingredientId = ingredient, includedByDefault = false, requiredForRecipe = false, canBeRemoved = false, canBeAdded = true, maximumAdditionalQuantity = (decimal?)2m, additionalPrice = 2m, applicationScope = "fraction" }, new { ingredientId = secondIngredient, includedByDefault = false, requiredForRecipe = false, canBeRemoved = false, canBeAdded = true, maximumAdditionalQuantity = (decimal?)2m, additionalPrice = 3m, applicationScope = "fraction" } } }, tenant.AccessToken)).EnsureSuccessStatusCode();
        var flavor = Guid.NewGuid(); await using (var db = fixture.CreateDbContext()) { var now = DateTimeOffset.UtcNow; db.AddRange(new PizzaFlavor { Id = flavor, ProductId = flavorProduct, CreatedAt = now, UpdatedAt = now }, new PizzaFlavorPrice { Id = Guid.NewGuid(), PizzaFlavorId = flavor, PizzaSizeId = size, Price = 30m, CreatedAt = now, UpdatedAt = now }, new DoughSizePrice { DoughId = dough, PizzaSizeId = size, AdditionalPrice = 1m }, new CrustSizePrice { CrustId = crust, PizzaSizeId = size, AdditionalPrice = 2m }); await db.SaveChangesAsync(); }
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{custom}/pizza-configuration", new { sizes = new[] { new { pizzaSizeId = size, maximumFlavors = 4, displayOrder = 1, customBasePrice = (decimal?)40m, flavorPrice = (decimal?)null } }, doughIds = new[] { dough }, crustIds = new[] { crust } }, tenant.AccessToken)).EnsureSuccessStatusCode(); (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        await using (var stationDb = fixture.CreateDbContext()) { stationDb.Add(new Station { Id = Guid.NewGuid(), EstablishmentId = tenant.EstablishmentId, Name = "Kitchen", IsDefault = true, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }); await stationDb.SaveChangesAsync(); }
        var device = await fixture.RegisterAndBindAsync(tenant.AccessToken, tenant.TableIds[0]); var session = await fixture.OpenSessionAsync(device.AccessToken); using var detail = await fixture.GetJsonAsync($"api/v1/table-device/menu/products/{custom}", device.AccessToken); var version = detail.RootElement.GetProperty("configurationVersion").GetString()!; var configuration = new { ingredients = new[] { new { ingredientId = ingredient, action = "add", quantity = 1m } }, pizza = new { sizeId = size, doughId = dough, crustId = crust, fractions = new object[] { new { flavorId = flavor }, new { custom = new { ingredients = new[] { new { ingredientId = ingredient, quantity = 1m } } } } } } };
        long catalogVersion, availabilityVersion; await using (var stateDb = fixture.CreateDbContext()) { var state = await stateDb.Set<CatalogState>().SingleAsync(x => x.EstablishmentId == tenant.EstablishmentId); catalogVersion = state.CatalogVersion; availabilityVersion = state.AvailabilityVersion; }
        var cart = Guid.NewGuid(); var simulation = await fixture.PostAsync("api/v1/table-device/cart/simulate", new { sessionId = session, localCartId = cart, catalogVersion, availabilityVersion, items = new[] { new { localCartItemId = Guid.NewGuid(), productId = custom, productVariantId = variant, quantity = 1, configurationVersion = version, estimatedUnitAmount = 40m, configuration } } }, device.AccessToken); var simulationBody = await simulation.Content.ReadAsStringAsync(); if (!simulation.IsSuccessStatusCode) throw new InvalidOperationException($"Pizza simulation failed ({simulation.StatusCode}): {simulationBody}"); using var sim = JsonDocument.Parse(simulationBody); var submit = await fixture.PostWithIdempotencyAsync("api/v1/table-device/orders", new { sessionId = session, localCartId = cart, clientSubmissionId = Guid.NewGuid(), simulationId = sim.RootElement.GetProperty("simulationId").GetGuid(), simulationVersion = sim.RootElement.GetProperty("simulationVersion").GetString(), acceptedReview = sim.RootElement.GetProperty("requiresReview").GetBoolean() }, device.AccessToken, Guid.NewGuid()); submit.EnsureSuccessStatusCode(); using var submitted = JsonDocument.Parse(await submit.Content.ReadAsStringAsync()); var orderId = submitted.RootElement.GetProperty("order").GetProperty("id").GetGuid(); await using var orderDb = fixture.CreateDbContext(); var item = await orderDb.Set<OrderItem>().SingleAsync(x => x.OrderId == orderId); return new(tenant.EstablishmentId, session, device.AccessToken, orderId, item.Id, custom, variant, size, flavor, ingredient, secondIngredient, dough, crust, configuration, version, 40m, item.Snapshot);
    }
    internal Task<ComboScenario> BuildComboAsync(string strategy, decimal fixedPrice) => BuildComboCoreAsync(strategy, fixedPrice);
    internal async Task<NestedComboScenario> BuildNestedComboAsync()
    {
        var tenant = await fixture.CreateTenantAsync(2, 1);
        var component = await CreateProduct(tenant.AccessToken, "simple", "Component", null, false);
        var componentVariant = await CreateVariant(tenant.AccessToken, component, "Standard", 5m);
        var child = await CreateProduct(tenant.AccessToken, "combo", "Nested child", null, false);
        var childVariant = await CreateVariant(tenant.AccessToken, child, "Standard", 0m);
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{child}/combo-configuration", new { pricingMode = "fixed_price", fixedPrice = 5m, groups = new[] { new { name = "Child", minimumSelections = 1, maximumSelections = 1, displayOrder = 1, items = new[] { new { productId = component, productVariantId = (Guid?)componentVariant, additionalPrice = 0m, displayOrder = 1 } } } } }, tenant.AccessToken)).EnsureSuccessStatusCode();
        (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        var alternative = await CreateProduct(tenant.AccessToken, "simple", "Alternative", null, false); var alternativeVariant = await CreateVariant(tenant.AccessToken, alternative, "Standard", 20m);
        var drink = await CreateProduct(tenant.AccessToken, "simple", "Drink", null, false); var drinkVariant = await CreateVariant(tenant.AccessToken, drink, "500ml", 10m);
        var parent = await CreateProduct(tenant.AccessToken, "combo", "Parent combo", null, true); var parentVariant = await CreateVariant(tenant.AccessToken, parent, "Standard", 0m);
        var groupsBody = new object[] { new { name = "Main", minimumSelections = 1, maximumSelections = 1, displayOrder = 1, items = new object[] { new { productId = alternative, productVariantId = (Guid?)alternativeVariant, additionalPrice = 1m, displayOrder = 1 }, new { productId = child, productVariantId = (Guid?)null, additionalPrice = 1m, displayOrder = 2 } } }, new { name = "Drink", minimumSelections = 1, maximumSelections = 1, displayOrder = 2, items = new[] { new { productId = drink, productVariantId = (Guid?)drinkVariant, additionalPrice = 3m, displayOrder = 1 } } } };
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{parent}/combo-configuration", new { pricingMode = "fixed_price", fixedPrice = 25m, groups = groupsBody }, tenant.AccessToken)).EnsureSuccessStatusCode();
        (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        Guid parentGroup; Guid validSelection; Guid nestedSelection; Guid drinkGroup; Guid drinkSelection;
        await using (var lookup = fixture.CreateDbContext()) { var comboId = await lookup.Set<Combo>().Where(x => x.ProductId == parent).Select(x => x.Id).SingleAsync(); var gs = await lookup.Set<ComboGroup>().Where(x => x.ComboId == comboId).OrderBy(x => x.DisplayOrder).Select(x => x.Id).ToArrayAsync(); parentGroup = gs[0]; drinkGroup = gs[1]; var main = await lookup.Set<ComboGroupItem>().Where(x => x.ComboGroupId == parentGroup).OrderBy(x => x.Id).ToListAsync(); validSelection = main.Single(x => x.ProductId == alternative).Id; nestedSelection = main.SingleOrDefault(x => x.ProductId == child)?.Id ?? throw new InvalidOperationException($"Nested option was not persisted. parent={parent} child={child} main={string.Join(',', main.Select(x => x.ProductId))}"); drinkSelection = (await lookup.Set<ComboGroupItem>().SingleAsync(x => x.ComboGroupId == drinkGroup)).Id; }
        await using (var station = fixture.CreateDbContext()) { station.Add(new Station { Id = Guid.NewGuid(), EstablishmentId = tenant.EstablishmentId, Name = "Kitchen", IsDefault = true, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }); await station.SaveChangesAsync(); }
        var device = await fixture.RegisterAndBindAsync(tenant.AccessToken, tenant.TableIds[0]); var session = await fixture.OpenSessionAsync(device.AccessToken); using var detail = await fixture.GetJsonAsync($"api/v1/table-device/menu/products/{parent}", device.AccessToken); var version = detail.RootElement.GetProperty("configurationVersion").GetString()!; long catalogVersion, availabilityVersion; await using (var state = fixture.CreateDbContext()) { var s = await state.Set<CatalogState>().SingleAsync(x => x.EstablishmentId == tenant.EstablishmentId); catalogVersion = s.CatalogVersion; availabilityVersion = s.AvailabilityVersion; }
        var originalConfiguration = new { combo = new { groups = new object[] { new { groupId = parentGroup, selections = new[] { new { comboGroupItemId = validSelection, quantity = 1, configuration = new { variantId = alternativeVariant } } } }, new { groupId = drinkGroup, selections = new[] { new { comboGroupItemId = drinkSelection, quantity = 1, configuration = new { variantId = drinkVariant } } } } } } };
        var cart = Guid.NewGuid(); var simulation = await fixture.PostAsync("api/v1/table-device/cart/simulate", new { sessionId = session, localCartId = cart, catalogVersion, availabilityVersion, items = new[] { new { localCartItemId = Guid.NewGuid(), productId = parent, productVariantId = parentVariant, quantity = 1, configurationVersion = version, estimatedUnitAmount = 29m, configuration = originalConfiguration } } }, device.AccessToken); simulation.EnsureSuccessStatusCode(); using var sim = JsonDocument.Parse(await simulation.Content.ReadAsStringAsync()); var submit = await fixture.PostWithIdempotencyAsync("api/v1/table-device/orders", new { sessionId = session, localCartId = cart, clientSubmissionId = Guid.NewGuid(), simulationId = sim.RootElement.GetProperty("simulationId").GetGuid(), simulationVersion = sim.RootElement.GetProperty("simulationVersion").GetString(), acceptedReview = sim.RootElement.GetProperty("requiresReview").GetBoolean() }, device.AccessToken, Guid.NewGuid()); submit.EnsureSuccessStatusCode(); using var submitted = JsonDocument.Parse(await submit.Content.ReadAsStringAsync()); var orderId = submitted.RootElement.GetProperty("order").GetProperty("id").GetGuid(); await using var orderDb = fixture.CreateDbContext(); var item = await orderDb.Set<OrderItem>().SingleAsync(x => x.OrderId == orderId);
        return new(tenant.EstablishmentId, session, device.AccessToken, orderId, item.Id, parent, child, childVariant, parentGroup, validSelection, nestedSelection, drinkGroup, drinkSelection, originalConfiguration, item.Snapshot, item.UnitAmount, catalogVersion, availabilityVersion, tenant.AccessToken, parentVariant, alternativeVariant, drinkVariant);
    }
    private async Task<ComboScenario> BuildComboCoreAsync(string strategy, decimal fixedPrice)
    {
        var tenant = await fixture.CreateTenantAsync(2, 1); var first = await CreateProduct(tenant.AccessToken, "simple", "Sandwich", (string?)null, false); var firstVariant = await CreateVariant(tenant.AccessToken, first, "Large", 20m); var second = await CreateProduct(tenant.AccessToken, "simple", "Juice", (string?)null, false); var secondVariant = await CreateVariant(tenant.AccessToken, second, "500ml", 10m); var combo = await CreateProduct(tenant.AccessToken, "combo", $"Combo {strategy}", "Combo historical", true); var comboVariant = await CreateVariant(tenant.AccessToken, combo, "Standard", 0m);
        var groupsBody = new object[] { new { name = "Main", minimumSelections = 1, maximumSelections = 1, displayOrder = 1, items = new[] { new { productId = first, productVariantId = (Guid?)firstVariant, additionalPrice = 1m, displayOrder = 1 } } }, new { name = "Drink", minimumSelections = 1, maximumSelections = 1, displayOrder = 2, items = new[] { new { productId = second, productVariantId = (Guid?)secondVariant, additionalPrice = 3m, displayOrder = 1 } } } };
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{combo}/combo-configuration", new { pricingMode = strategy, fixedPrice = strategy == "fixed_price" ? fixedPrice : (decimal?)null, groups = groupsBody }, tenant.AccessToken)).EnsureSuccessStatusCode(); (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();
        Guid[] groups; Guid[] selections; await using (var lookup = fixture.CreateDbContext()) { var comboId = await lookup.Set<Combo>().Where(x => x.ProductId == combo).Select(x => x.Id).SingleAsync(); groups = await lookup.Set<ComboGroup>().Where(x => x.ComboId == comboId).OrderBy(x => x.DisplayOrder).Select(x => x.Id).ToArrayAsync(); selections = new[] { await lookup.Set<ComboGroupItem>().Where(x => x.ComboGroupId == groups[0]).Select(x => x.Id).SingleAsync(), await lookup.Set<ComboGroupItem>().Where(x => x.ComboGroupId == groups[1]).Select(x => x.Id).SingleAsync() }; }
        await using (var db = fixture.CreateDbContext()) { db.Add(new Station { Id = Guid.NewGuid(), EstablishmentId = tenant.EstablishmentId, Name = "Kitchen", IsDefault = true, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(); }
        var device = await fixture.RegisterAndBindAsync(tenant.AccessToken, tenant.TableIds[0]); var session = await fixture.OpenSessionAsync(device.AccessToken); using var detail = await fixture.GetJsonAsync($"api/v1/table-device/menu/products/{combo}", device.AccessToken); var version = detail.RootElement.GetProperty("configurationVersion").GetString()!; var configuration = new { combo = new { groups = new object[] { new { groupId = groups[0], selections = new[] { new { comboGroupItemId = selections[0], quantity = 1, configuration = new { variantId = firstVariant } } } }, new { groupId = groups[1], selections = new[] { new { comboGroupItemId = selections[1], quantity = 1, configuration = new { variantId = secondVariant } } } } } } };
        long catalogVersion, availabilityVersion; await using (var stateDb = fixture.CreateDbContext()) { var state = await stateDb.Set<CatalogState>().SingleAsync(x => x.EstablishmentId == tenant.EstablishmentId); catalogVersion = state.CatalogVersion; availabilityVersion = state.AvailabilityVersion; }
        var localCart = Guid.NewGuid(); var simulation = await fixture.PostAsync("api/v1/table-device/cart/simulate", new { sessionId = session, localCartId = localCart, catalogVersion, availabilityVersion, items = new[] { new { localCartItemId = Guid.NewGuid(), productId = combo, productVariantId = comboVariant, quantity = 1, configurationVersion = version, estimatedUnitAmount = strategy == "fixed_price" ? fixedPrice + 4m : 34m, configuration } } }, device.AccessToken); var simulationBody = await simulation.Content.ReadAsStringAsync(); if (!simulation.IsSuccessStatusCode) throw new InvalidOperationException($"Combo {strategy} simulation failed ({simulation.StatusCode}): {simulationBody}"); using var sim = JsonDocument.Parse(simulationBody); var submit = await fixture.PostWithIdempotencyAsync("api/v1/table-device/orders", new { sessionId = session, localCartId = localCart, clientSubmissionId = Guid.NewGuid(), simulationId = sim.RootElement.GetProperty("simulationId").GetGuid(), simulationVersion = sim.RootElement.GetProperty("simulationVersion").GetString(), acceptedReview = sim.RootElement.GetProperty("requiresReview").GetBoolean() }, device.AccessToken, Guid.NewGuid()); submit.EnsureSuccessStatusCode(); using var submitted = JsonDocument.Parse(await submit.Content.ReadAsStringAsync()); var orderId = submitted.RootElement.GetProperty("order").GetProperty("id").GetGuid(); await using var orderDb = fixture.CreateDbContext(); var item = await orderDb.Set<OrderItem>().SingleAsync(x => x.OrderId == orderId); var original = strategy == "fixed_price" ? fixedPrice + 4m : 34m; return new(tenant.EstablishmentId, session, tenant.AccessToken, device.AccessToken, orderId, item.Id, combo, comboVariant, first, firstVariant, second, secondVariant, groups, selections, configuration, version, original, item.Snapshot);
    }
    internal async Task<MultiFlavorPizzaScenario> BuildMultiFlavorPizzaAsync()
    {
        var tenant = await fixture.CreateTenantAsync(2, 1);
        var pizza = await CreateProduct(tenant.AccessToken, "pizza", "Pizza Especial", "Pizza historica", true);
        var variant = await CreateVariant(tenant.AccessToken, pizza, "Grande", 0m);
        var flavorAProduct = await CreateProduct(tenant.AccessToken, "simple", "Calabresa", "Sabor A", false);
        var flavorBProduct = await CreateProduct(tenant.AccessToken, "simple", "Marguerita", "Sabor B", false);
        var flavorCProduct = await CreateProduct(tenant.AccessToken, "simple", "Frango", "Sabor C", false);
        await CreateVariant(tenant.AccessToken, flavorAProduct, "Integral", 0m);
        await CreateVariant(tenant.AccessToken, flavorBProduct, "Integral", 0m);
        await CreateVariant(tenant.AccessToken, flavorCProduct, "Integral", 0m);

        var size = await PostId(tenant.AccessToken, "api/v1/operations/catalog/pizza-sizes", new { name = "Grande", shortName = "G", sliceCount = 8, diameterCm = 35m, displayOrder = 1 });
        var dough = await PostId(tenant.AccessToken, "api/v1/operations/catalog/doughs", new { name = "Tradicional", description = "Massa historica", isDefault = true });
        var crust = await PostId(tenant.AccessToken, "api/v1/operations/catalog/crusts", new { name = "Catupiry", description = "Borda historica", imageMediaId = (Guid?)null });
        var flavorA = Guid.NewGuid(); var flavorB = Guid.NewGuid(); var flavorC = Guid.NewGuid();
        await using (var db = fixture.CreateDbContext())
        {
            var now = DateTimeOffset.UtcNow;
            db.AddRange(
                new PizzaFlavor { Id = flavorA, ProductId = flavorAProduct, CreatedAt = now, UpdatedAt = now },
                new PizzaFlavor { Id = flavorB, ProductId = flavorBProduct, CreatedAt = now, UpdatedAt = now },
                new PizzaFlavor { Id = flavorC, ProductId = flavorCProduct, CreatedAt = now, UpdatedAt = now },
                new PizzaFlavorPrice { Id = Guid.NewGuid(), PizzaFlavorId = flavorA, PizzaSizeId = size, Price = 31.01m, CreatedAt = now, UpdatedAt = now },
                new PizzaFlavorPrice { Id = Guid.NewGuid(), PizzaFlavorId = flavorB, PizzaSizeId = size, Price = 32m, CreatedAt = now, UpdatedAt = now },
                new PizzaFlavorPrice { Id = Guid.NewGuid(), PizzaFlavorId = flavorC, PizzaSizeId = size, Price = 20m, CreatedAt = now, UpdatedAt = now },
                new DoughSizePrice { DoughId = dough, PizzaSizeId = size, AdditionalPrice = 1m },
                new CrustSizePrice { CrustId = crust, PizzaSizeId = size, AdditionalPrice = 2m });
            await db.SaveChangesAsync();
        }
        (await fixture.PutAsync($"api/v1/operations/catalog/products/{pizza}/pizza-configuration", new { sizes = new[] { new { pizzaSizeId = size, maximumFlavors = 4, displayOrder = 1, customBasePrice = (decimal?)null, flavorPrice = (decimal?)null } }, doughIds = new[] { dough }, crustIds = new[] { crust } }, tenant.AccessToken)).EnsureSuccessStatusCode();
        (await fixture.PostAsync("api/v1/operations/catalog/publish", null, tenant.AccessToken, true)).EnsureSuccessStatusCode();

        await using (var stationDb = fixture.CreateDbContext()) { stationDb.Add(new Station { Id = Guid.NewGuid(), EstablishmentId = tenant.EstablishmentId, Name = "Kitchen", IsDefault = true, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }); await stationDb.SaveChangesAsync(); }
        var device = await fixture.RegisterAndBindAsync(tenant.AccessToken, tenant.TableIds[0]);
        var session = await fixture.OpenSessionAsync(device.AccessToken);
        var configuration = new { pizza = new { sizeId = size, doughId = dough, crustId = crust, fractions = new[] { new { flavorId = flavorA }, new { flavorId = flavorB } } }, notes = new[] { "Cut eight" } };
        using var detail = await fixture.GetJsonAsync($"api/v1/table-device/menu/products/{pizza}", device.AccessToken);
        var configurationVersion = detail.RootElement.GetProperty("configurationVersion").GetString()!;
        long catalogVersion; long availabilityVersion;
        await using (var db = fixture.CreateDbContext()) { var state = await db.Set<CatalogState>().SingleAsync(x => x.EstablishmentId == tenant.EstablishmentId); catalogVersion = state.CatalogVersion; availabilityVersion = state.AvailabilityVersion; }
        var localCart = Guid.NewGuid();
        var simulation = await fixture.PostAsync("api/v1/table-device/cart/simulate", new { sessionId = session, localCartId = localCart, catalogVersion, availabilityVersion, items = new[] { new { localCartItemId = Guid.NewGuid(), productId = pizza, productVariantId = variant, quantity = 1, configurationVersion, estimatedUnitAmount = 34.51m, configuration } } }, device.AccessToken);
 var simulationBody = await simulation.Content.ReadAsStringAsync(); if (!simulation.IsSuccessStatusCode) throw new InvalidOperationException($"Pizza simulation failed ({simulation.StatusCode}): {simulationBody}"); using var sim = JsonDocument.Parse(simulationBody);
        var submission = await fixture.PostWithIdempotencyAsync("api/v1/table-device/orders", new { sessionId = session, localCartId = localCart, clientSubmissionId = Guid.NewGuid(), simulationId = sim.RootElement.GetProperty("simulationId").GetGuid(), simulationVersion = sim.RootElement.GetProperty("simulationVersion").GetString(), acceptedReview = sim.RootElement.GetProperty("requiresReview").GetBoolean() }, device.AccessToken, Guid.NewGuid());
        var submissionBody = await submission.Content.ReadAsStringAsync(); if (!submission.IsSuccessStatusCode) throw new InvalidOperationException($"Pizza submission failed ({submission.StatusCode}): {submissionBody}"); using var submitted = JsonDocument.Parse(submissionBody); var orderId = submitted.RootElement.GetProperty("order").GetProperty("id").GetGuid();
        await using var orderDb = fixture.CreateDbContext(); var item = await orderDb.Set<OrderItem>().SingleAsync(x => x.OrderId == orderId);
        return new(tenant.EstablishmentId, session, device.DeviceId, tenant.AccessToken, device.AccessToken, orderId, item.Id, pizza, variant, size, new[] { flavorA, flavorB }, flavorC, dough, crust, configuration, configurationVersion, catalogVersion, availabilityVersion, 34.51m, item.Snapshot);
    }

    private async Task<Guid> CreateProduct(string token, string type, string name, string? description, bool notes) => await PostId(token, "api/v1/operations/catalog/products", new { productType = type, name, description, internalCode = Guid.NewGuid().ToString("N"), displayOrder = 1, requiresProduction = true, allowsNotes = notes, maximumNoteLength = notes ? 200 : (int?)null });
    private async Task<Guid> CreateVariant(string token, Guid product, string name, decimal price) => await PostId(token, $"api/v1/operations/catalog/products/{product}/variants", new { name, internalCode = Guid.NewGuid().ToString("N"), basePrice = price, displayOrder = 1 });
    private async Task<Guid> PostId(string token, string path, object body) { var response = await fixture.PostAsync(path, body, token); response.EnsureSuccessStatusCode(); using var json = JsonDocument.Parse(await response.Content.ReadAsStringAsync()); return json.RootElement.GetProperty("id").GetGuid(); }
}

internal sealed record MultiFlavorPizzaScenario(Guid EstablishmentId, Guid SessionId, Guid DeviceId, string UserToken, string DeviceToken, Guid OrderId, Guid OrderItemId, Guid ProductId, Guid VariantId, Guid SizeId, Guid[] FlavorIds, Guid AlternateFlavorId, Guid DoughId, Guid CrustId, object OriginalConfiguration, string ConfigurationVersion, long CatalogVersion, long AvailabilityVersion, decimal OriginalUnitAmount, string OriginalSnapshot);
internal sealed record BuildYourOwnPizzaScenario(Guid EstablishmentId, Guid SessionId, string DeviceToken, Guid OrderId, Guid OrderItemId, Guid ProductId, Guid VariantId, Guid SizeId, Guid FlavorId, Guid IngredientId, Guid SecondIngredientId, Guid DoughId, Guid CrustId, object OriginalConfiguration, string ConfigurationVersion, decimal OriginalUnitAmount, string OriginalSnapshot);
internal sealed record ComboScenario(Guid EstablishmentId, Guid SessionId, string UserToken, string DeviceToken, Guid OrderId, Guid OrderItemId, Guid ComboProductId, Guid ComboVariantId, Guid FirstProductId, Guid FirstVariantId, Guid SecondProductId, Guid SecondVariantId, Guid[] GroupIds, Guid[] SelectionIds, object OriginalConfiguration, string ConfigurationVersion, decimal OriginalUnitAmount, string OriginalSnapshot);
internal sealed record NestedComboScenario(Guid EstablishmentId, Guid SessionId, string DeviceToken, Guid OrderId, Guid OrderItemId, Guid ParentComboProductId, Guid ChildComboProductId, Guid ChildVariantId, Guid ParentGroupId, Guid ValidSelectionId, Guid NestedSelectionId, Guid DrinkGroupId, Guid DrinkSelectionId, object OriginalConfiguration, string OriginalSnapshot, decimal OriginalUnitAmount, long CatalogVersion, long AvailabilityVersion, string UserToken, Guid ParentVariantId, Guid AlternativeVariantId, Guid DrinkVariantId);
internal sealed record NestedComboCatalogScenario(Guid EstablishmentId, Guid ChildComboId, Guid ParentComboId, Guid ParentGroupId, Guid NestedGroupItemId, Guid NormalGroupItemId, Guid NormalVariantId, Guid ParentVariantId, Guid TableId, string UserToken);
