using System.Net;
using System.Text.Json;
using Appizza.Modules.Payments;
using Appizza.Modules.Tables;
using Appizza.Modules.Auditing;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api.IntegrationTests;

[Collection(Phase1ApiCollection.Name)]
public sealed class Phase7PaymentLifecycleApiTests(Phase1ApiFixture fixture)
{
    [Fact] public async Task FailureReleasesReservationWithoutPaying() { var x=await CreateAttempt(); var before=await Financial(x.SessionId); await fixture.CreatePaymentLifecycleService().FailAsync(x.Tenant,x.AttemptId); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Declined,after.Status); Assert.Equal(before.Paid,after.Paid); Assert.Equal(before.Reserved-x.Amount,after.Reserved); }
    [Fact] public async Task CancellationReleasesReservationWithoutPaying() { var x=await CreateAttempt(); var before=await Financial(x.SessionId); await fixture.CreatePaymentLifecycleService().CancelAsync(x.Tenant,x.AttemptId); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Cancelled,after.Status); Assert.Equal(before.Paid,after.Paid); Assert.Equal(before.Reserved-x.Amount,after.Reserved); }
    [Fact] public async Task ExpirationReleasesReservationWithoutPaying() { var x=await CreateAttempt(); var before=await Financial(x.SessionId); await fixture.CreatePaymentLifecycleService().ExpireAsync(x.Tenant,x.AttemptId); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Expired,after.Status); Assert.Equal(before.Paid,after.Paid); Assert.Equal(before.Reserved-x.Amount,after.Reserved); }
    [Fact] public async Task UnknownKeepsReservationAndResolvesToApproved() { var x=await CreateAttempt(); var before=await Financial(x.SessionId); var svc=fixture.CreatePaymentLifecycleService(); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); var unknown=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Unknown,unknown.Status); Assert.Equal(before.Reserved,unknown.Reserved); await svc.ResolveUnknownSuccessAsync(x.Tenant,x.AttemptId); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Approved,after.Status); Assert.Equal(before.Reserved-x.Amount,after.Reserved); Assert.Equal(before.Paid+x.Amount,after.Paid); }
    [Fact] public async Task UnknownCanResolveToDeclinedAndReleaseReservation() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); var before=await Financial(x.SessionId); await svc.ResolveUnknownFailureAsync(x.Tenant,x.AttemptId); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Declined,after.Status); Assert.Equal(before.Reserved-x.Amount,after.Reserved); Assert.Equal(before.Paid,after.Paid); }
    [Fact] public async Task RepeatedFailureReleasesReservationOnce() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.FailAsync(x.Tenant,x.AttemptId); var first=await Financial(x.SessionId); await svc.FailAsync(x.Tenant,x.AttemptId); var second=await Financial(x.SessionId); Assert.Equal(first,second); Assert.Equal(0m,second.Reserved); }
    [Fact] public async Task EmployeeWithoutConfirmCashPermissionIsRejected() { var x=await CreateAttempt(); var token=await fixture.CreateUserTokenAsync(x.Tenant); var r=await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{x.AttemptId}/confirm-cash",new{},token,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Forbidden,r.StatusCode); var after=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Created,after.Status); Assert.Equal(x.Amount,after.Reserved); Assert.Equal(0m,after.Paid); }
    [Fact] public async Task ApprovedAttemptCannotBeCancelled() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.SucceedAsync(x.Tenant,x.AttemptId); var before=await Detailed(x); await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.CancelAsync(x.Tenant,x.AttemptId)); var after=await Detailed(x); Assert.Equal(before,after); }
    [Fact] public async Task RepeatedCancellationReleasesReservationOnce() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.CancelAsync(x.Tenant,x.AttemptId); var first=await Financial(x.SessionId); await svc.CancelAsync(x.Tenant,x.AttemptId); var second=await Financial(x.SessionId); Assert.Equal(first,second); }
    [Fact] public async Task RepeatedExpirationReleasesReservationOnce() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.ExpireAsync(x.Tenant,x.AttemptId); var first=await Financial(x.SessionId); await svc.ExpireAsync(x.Tenant,x.AttemptId); var second=await Financial(x.SessionId); Assert.Equal(first,second); }
    [Fact] public async Task RepeatedMarkUnknownKeepsReservation() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); var first=await Financial(x.SessionId); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); var second=await Financial(x.SessionId); Assert.Equal(first,second); Assert.Equal(PaymentAttemptStatus.Unknown,second.Status); }
    [Fact] public async Task UnknownAllocationCannotBeReservedAgain() { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,10m); var p=await CreatePlan(c); var created=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p.PlanId,allocationIds=new[]{p.AllocationId},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); using var j=JsonDocument.Parse(await created.Content.ReadAsStringAsync()); var id=j.RootElement.GetProperty("attemptId").GetGuid(); var tenant=await TenantId(c.SessionId); await fixture.CreatePaymentLifecycleService().MarkUnknownAsync(tenant,id); var retry=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p.PlanId,allocationIds=new[]{p.AllocationId},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Conflict,retry.StatusCode); }
    [Fact] public async Task ApprovedAttemptRejectsFailExpireAndUnknown() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.SucceedAsync(x.Tenant,x.AttemptId); var before=await Financial(x.SessionId); await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.FailAsync(x.Tenant,x.AttemptId)); await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.ExpireAsync(x.Tenant,x.AttemptId)); await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.MarkUnknownAsync(x.Tenant,x.AttemptId)); Assert.Equal(before,await Financial(x.SessionId)); }
    [Fact] public async Task PartialSettlementDoesNotMarkSessionPaid() { var x=await CreatePartialAttempt(); await using(var beforeDb=fixture.CreateDbContext()){ var before=await beforeDb.Set<TableSession>().AsNoTracking().SingleAsync(a=>a.Id==x.SessionId); var allocation=await beforeDb.Set<PaymentPlanAllocation>().AsNoTracking().SingleAsync(a=>a.Id==x.AllocationId); Assert.Equal(100m,before.TotalAmount); Assert.Equal(0m,before.PaidAmount); Assert.Equal(40m,before.ReservedAmount); Assert.Equal(40m,allocation.Amount); Assert.Equal(40m,x.Amount); } var svc=fixture.CreatePaymentLifecycleService(); await svc.SucceedAsync(x.Tenant,x.AttemptId); await using var db=fixture.CreateDbContext(); var s=await db.Set<TableSession>().AsNoTracking().SingleAsync(a=>a.Id==x.SessionId); var attempt=await db.Set<PaymentAttempt>().AsNoTracking().SingleAsync(a=>a.Id==x.AttemptId); Assert.Equal(PaymentAttemptStatus.Approved,attempt.Status); Assert.Equal(100m,s.TotalAmount); Assert.Equal(40m,s.PaidAmount); Assert.Equal(0m,s.ReservedAmount); Assert.Equal("partially_paid",s.Status); Assert.NotEqual("paid",s.Status); Assert.NotEqual("closed",s.Status); }
    [Fact] public async Task ReservationDoesNotCountAsPaid() { var x=await CreateAttempt(); await using var db=fixture.CreateDbContext(); var s=await db.Set<TableSession>().AsNoTracking().SingleAsync(a=>a.Id==x.SessionId); Assert.Equal(s.TotalAmount,s.PaidAmount+s.ReservedAmount); Assert.Equal(0m,s.PaidAmount); Assert.NotEqual("paid",s.Status); Assert.NotEqual("closed",s.Status); }
    [Fact] public async Task MultipleAttemptsSettleIndependently() { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,100m); var r=await fixture.PostWithIdempotencyAsync("api/v1/table-device/session/payment-plan",new{sessionId=c.SessionId,mode="equal_split",partCount=2},c.Device.AccessToken,Guid.NewGuid()); r.EnsureSuccessStatusCode(); using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync()); var a=j.RootElement.GetProperty("allocations")[0].GetProperty("allocationId").GetGuid(); var b=j.RootElement.GetProperty("allocations")[1].GetProperty("allocationId").GetGuid(); var pa=j.RootElement.GetProperty("planId").GetGuid(); var ra=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=pa,allocationIds=new[]{a},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); var rb=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=pa,allocationIds=new[]{b},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); ra.EnsureSuccessStatusCode(); rb.EnsureSuccessStatusCode(); using var ja=JsonDocument.Parse(await ra.Content.ReadAsStringAsync()); using var jb=JsonDocument.Parse(await rb.Content.ReadAsStringAsync()); var svc=fixture.CreatePaymentLifecycleService(); var tenant=await TenantId(c.SessionId); await svc.SucceedAsync(tenant,ja.RootElement.GetProperty("attemptId").GetGuid()); var mid=await Financial(c.SessionId); Assert.Equal(50m,mid.Paid); Assert.Equal(50m,mid.Reserved); await svc.SucceedAsync(tenant,jb.RootElement.GetProperty("attemptId").GetGuid()); var end=await Financial(c.SessionId); Assert.Equal(100m,end.Paid); Assert.Equal(0m,end.Reserved); }
    [Fact] public async Task UnknownThenDeclinedAllocationCanBeReservedAgain() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); await svc.ResolveUnknownFailureAsync(x.Tenant,x.AttemptId); var retry=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=x.SessionId,paymentPlanId=x.PlanId,allocationIds=new[]{x.AllocationId},paymentMethod="cash"},x.AccessToken,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Created,retry.StatusCode); await using var db=fixture.CreateDbContext(); Assert.Equal(2,await db.Set<PaymentAttemptAllocation>().CountAsync(a=>a.PaymentPlanAllocationId==x.AllocationId)); }
    [Theory]
    [InlineData("declined")]
    [InlineData("cancelled")]
    [InlineData("expired")]
    public async Task ReleasedTerminalAttemptsRejectSuccess(string state) { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); if(state=="declined") await svc.FailAsync(x.Tenant,x.AttemptId); else if(state=="cancelled") await svc.CancelAsync(x.Tenant,x.AttemptId); else await svc.ExpireAsync(x.Tenant,x.AttemptId); await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.SucceedAsync(x.Tenant,x.AttemptId)); }
    [Fact]
    public async Task AuthorizedEmployeeCanConfirmCashAndMoveReservationToPaid()
    {
        var context = await fixture.CreateOpenSessionAsync();
        await SetTotal(context.SessionId, 10m);
        var plan = await CreatePlan(context);
        var created = await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts", new { tableSessionId = context.SessionId, paymentPlanId = plan.PlanId, allocationIds = new[] { plan.AllocationId }, paymentMethod = "cash" }, context.Device.AccessToken, Guid.NewGuid());
        Assert.Equal(HttpStatusCode.Created, created.StatusCode);
        using var body = JsonDocument.Parse(await created.Content.ReadAsStringAsync()); var attemptId = body.RootElement.GetProperty("attemptId").GetGuid();
        var employee = await fixture.CreateUserTokenAsync(await TenantId(context.SessionId), "payments.confirm_cash");
        var confirmed = await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{attemptId}/confirm-cash", new { }, employee, Guid.NewGuid());
        Assert.Equal(HttpStatusCode.OK, confirmed.StatusCode);
        await using var db = fixture.CreateDbContext();
        var attempt = await db.Set<PaymentAttempt>().SingleAsync(x => x.Id == attemptId); var session = await db.Set<TableSession>().SingleAsync(x => x.Id == context.SessionId);
        Assert.Equal(PaymentAttemptStatus.Approved, attempt.Status); Assert.Equal(10m, session.PaidAmount); Assert.Equal(0m, session.ReservedAmount); Assert.Equal("paid", session.Status);
    }

    [Fact]
    public async Task DuplicateCashConfirmationIsIdempotent()
    {
        var context = await fixture.CreateOpenSessionAsync(); await SetTotal(context.SessionId, 10m); var plan = await CreatePlan(context);
        var created = await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts", new { tableSessionId = context.SessionId, paymentPlanId = plan.PlanId, allocationIds = new[] { plan.AllocationId }, paymentMethod = "cash" }, context.Device.AccessToken, Guid.NewGuid());
        using var body = JsonDocument.Parse(await created.Content.ReadAsStringAsync()); var attemptId = body.RootElement.GetProperty("attemptId").GetGuid(); var employee = await fixture.CreateUserTokenAsync(await TenantId(context.SessionId), "payments.confirm_cash");
        var first = await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{attemptId}/confirm-cash", new { }, employee, Guid.NewGuid()); var second = await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{attemptId}/confirm-cash", new { }, employee, Guid.NewGuid());
        Assert.Equal(HttpStatusCode.OK, first.StatusCode); Assert.Equal(HttpStatusCode.OK, second.StatusCode);
        await using var db = fixture.CreateDbContext(); var session = await db.Set<TableSession>().SingleAsync(x => x.Id == context.SessionId); Assert.Equal(10m, session.PaidAmount); Assert.Equal(0m, session.ReservedAmount);
    }

    [Fact]
    public async Task TableDeviceCannotConfirmCash()
    {
        var context = await fixture.CreateOpenSessionAsync(); await SetTotal(context.SessionId, 10m); var plan = await CreatePlan(context);
        var created = await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts", new { tableSessionId = context.SessionId, paymentPlanId = plan.PlanId, allocationIds = new[] { plan.AllocationId }, paymentMethod = "cash" }, context.Device.AccessToken, Guid.NewGuid()); using var body = JsonDocument.Parse(await created.Content.ReadAsStringAsync()); var id = body.RootElement.GetProperty("attemptId").GetGuid();
        var rejected = await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{id}/confirm-cash", new { }, context.Device.AccessToken, Guid.NewGuid()); Assert.Equal(HttpStatusCode.Forbidden, rejected.StatusCode);
    }
    [Fact]
    public async Task InactiveEmployeeAfterAuthenticationIsRejected()
    {
        var x=await CreateAttempt(); var token=await fixture.CreateUserTokenAsync(x.Tenant,"payments.confirm_cash");
        await using (var db=fixture.CreateDbContext()) { var user=await db.Set<Appizza.Modules.Identity.User>().Where(u=>u.EstablishmentId==x.Tenant).OrderByDescending(u=>u.CreatedAt).FirstAsync(); user.Status="inactive"; await db.SaveChangesAsync(); }
        var before=await Financial(x.SessionId); var r=await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{x.AttemptId}/confirm-cash",new{},token,Guid.NewGuid()); Assert.Equal(HttpStatusCode.NotFound,r.StatusCode); Assert.Equal(before,await Financial(x.SessionId));
    }
    [Theory]
    [InlineData("declined")]
    [InlineData("cancelled")]
    [InlineData("expired")]
    public async Task ReleasedCashAttemptCannotBeConfirmed(string state)
    {
        var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); if(state=="declined") await svc.FailAsync(x.Tenant,x.AttemptId); else if(state=="cancelled") await svc.CancelAsync(x.Tenant,x.AttemptId); else await svc.ExpireAsync(x.Tenant,x.AttemptId); var before=await Financial(x.SessionId); var token=await fixture.CreateUserTokenAsync(x.Tenant,"payments.confirm_cash"); var r=await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{x.AttemptId}/confirm-cash",new{},token,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Conflict,r.StatusCode); Assert.Equal(before,await Financial(x.SessionId));
    }

    [Fact] public async Task FailureReleasesOnlyItsOwnReservation() { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,100m); var r=await fixture.PostWithIdempotencyAsync("api/v1/table-device/session/payment-plan",new{sessionId=c.SessionId,mode="equal_split",partCount=2},c.Device.AccessToken,Guid.NewGuid()); using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync()); var ids=j.RootElement.GetProperty("allocations").EnumerateArray().Select(x=>x.GetProperty("allocationId").GetGuid()).ToArray(); var p=j.RootElement.GetProperty("planId").GetGuid(); var a=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p,allocationIds=new[]{ids[0]},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); var b=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p,allocationIds=new[]{ids[1]},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); using var ja=JsonDocument.Parse(await a.Content.ReadAsStringAsync()); var svc=fixture.CreatePaymentLifecycleService(); await svc.FailAsync(await TenantId(c.SessionId),ja.RootElement.GetProperty("attemptId").GetGuid()); var f=await Financial(c.SessionId); Assert.Equal(50m,f.Reserved); }
    [Fact] public async Task InvalidLifecycleTransitionsPreservePersistedState() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.SucceedAsync(x.Tenant,x.AttemptId); var before=await Detailed(x); foreach(var action in new Func<Task>[] { ()=>svc.FailAsync(x.Tenant,x.AttemptId), ()=>svc.ExpireAsync(x.Tenant,x.AttemptId), ()=>svc.MarkUnknownAsync(x.Tenant,x.AttemptId), ()=>svc.CancelAsync(x.Tenant,x.AttemptId) }) await Assert.ThrowsAsync<InvalidOperationException>(action); Assert.Equal(before,await Detailed(x)); }
    [Fact] public async Task ForeignTenantCashAttemptIsNotDisclosed() { var a=await fixture.CreateOpenSessionAsync(); var b=await CreateAttempt(); var employee=await fixture.CreateUserTokenAsync(await TenantId(a.SessionId),"payments.confirm_cash"); var before=await Financial(b.SessionId); var r=await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{b.AttemptId}/confirm-cash",new{},employee,Guid.NewGuid()); Assert.Equal(HttpStatusCode.NotFound,r.StatusCode); Assert.Equal(before,await Financial(b.SessionId)); }
    [Fact] public async Task ConcurrentSuccessSameAttemptAppliesFinancialEffectOnce() { var x=await CreateAttempt(); var tenant=x.Tenant; var tasks=Enumerable.Range(0,2).Select(_=>Task.Run(async()=>{ await using var db=fixture.CreateDbContext(); await new PaymentAttemptLifecycleService(db).SucceedAsync(tenant,x.AttemptId); })).ToArray(); await Task.WhenAll(tasks); var f=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Approved,f.Status); Assert.Equal(x.Amount,f.Paid); Assert.Equal(0m,f.Reserved); }
    [Fact] public async Task ConcurrentSuccessVsFailureHasSingleTerminalOutcome() { var x=await CreateAttempt(); var tenant=x.Tenant; var tasks=new[]{Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).SucceedAsync(tenant,x.AttemptId);}catch(InvalidOperationException){}}),Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).FailAsync(tenant,x.AttemptId);}catch(InvalidOperationException){}})}; await Task.WhenAll(tasks); var f=await Financial(x.SessionId); Assert.Contains(f.Status,new[]{PaymentAttemptStatus.Approved,PaymentAttemptStatus.Declined}); Assert.True(f.Reserved>=0); Assert.True(f.Paid==0m||f.Paid==x.Amount); if(f.Status==PaymentAttemptStatus.Approved) Assert.Equal(x.Amount,f.Paid); else Assert.Equal(0m,f.Paid); Assert.Equal(0m,f.Reserved); }
    [Fact] public async Task ConcurrentSuccessVsCancelHasSingleTerminalOutcome() { var x=await CreateAttempt(); var tenant=x.Tenant; var tasks=new[]{Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).SucceedAsync(tenant,x.AttemptId);}catch(InvalidOperationException){}}),Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).CancelAsync(tenant,x.AttemptId);}catch(InvalidOperationException){}})}; await Task.WhenAll(tasks); var f=await Financial(x.SessionId); Assert.Contains(f.Status,new[]{PaymentAttemptStatus.Approved,PaymentAttemptStatus.Cancelled}); Assert.Equal(0m,f.Reserved); Assert.Equal(f.Status==PaymentAttemptStatus.Approved?x.Amount:0m,f.Paid); }
    [Fact] public async Task ConcurrentDuplicateCashConfirmationPaysOnce() { var x=await CreateAttempt(); var token=await fixture.CreateUserTokenAsync(x.Tenant,"payments.confirm_cash"); var tasks=Enumerable.Range(0,2).Select(_=>fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{x.AttemptId}/confirm-cash",new{},token,Guid.NewGuid())).ToArray(); var responses=await Task.WhenAll(tasks); Assert.All(responses,r=>Assert.True(r.IsSuccessStatusCode||r.StatusCode==HttpStatusCode.Conflict)); var f=await Financial(x.SessionId); Assert.Equal(PaymentAttemptStatus.Approved,f.Status); Assert.Equal(x.Amount,f.Paid); Assert.Equal(0m,f.Reserved); }
    [Fact] public async Task ConcurrentUnknownResolutionHasSingleFinalOutcome() { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); await svc.MarkUnknownAsync(x.Tenant,x.AttemptId); var tasks=new[]{Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).ResolveUnknownSuccessAsync(x.Tenant,x.AttemptId);}catch(InvalidOperationException){}}),Task.Run(async()=>{await using var db=fixture.CreateDbContext(); try{await new PaymentAttemptLifecycleService(db).ResolveUnknownFailureAsync(x.Tenant,x.AttemptId);}catch(InvalidOperationException){}})}; await Task.WhenAll(tasks); var f=await Financial(x.SessionId); Assert.Contains(f.Status,new[]{PaymentAttemptStatus.Approved,PaymentAttemptStatus.Declined}); Assert.Equal(0m,f.Reserved); Assert.Equal(f.Status==PaymentAttemptStatus.Approved?x.Amount:0m,f.Paid); }
    [Fact] public async Task PaymentLifecycleWritesSingleAuditAndOutboxPerTransition() { var x=await CreateAttempt(); await using(var before=fixture.CreateDbContext()){ var created=await before.OutboxMessages.AsNoTracking().Where(e=>e.EstablishmentId==x.Tenant&&e.EventType=="payment-attempt-created.v1").ToListAsync(); Assert.Single(created,e=>PayloadTargetsAttempt(e.Payload,x.AttemptId)); Assert.Single(await before.Set<AuditEntry>().Where(e=>e.AggregateId==x.AttemptId&&e.Action=="payment_attempt.created").ToListAsync()); } var svc=fixture.CreatePaymentLifecycleService(); await svc.SucceedAsync(x.Tenant,x.AttemptId); await svc.SucceedAsync(x.Tenant,x.AttemptId); await using var db=fixture.CreateDbContext(); var approved=await db.OutboxMessages.AsNoTracking().Where(e=>e.EstablishmentId==x.Tenant&&e.EventType=="payment-attempt-approved.v1").ToListAsync(); Assert.Single(approved,e=>PayloadTargetsAttempt(e.Payload,x.AttemptId)); Assert.Single(await db.Set<AuditEntry>().Where(e=>e.AggregateId==x.AttemptId&&e.Action=="payment_attempt.approved").ToListAsync()); }
    private static bool PayloadTargetsAttempt(string payload, Guid id) { using var json=JsonDocument.Parse(payload); return json.RootElement.TryGetProperty("paymentAttemptId",out var value)&&value.GetGuid()==id; }
    private async Task SetTotal(Guid id, decimal total) { await using var db = fixture.CreateDbContext(); var s = await db.Set<TableSession>().SingleAsync(x => x.Id == id); s.TotalAmount = total; s.RemainingAmount = total; await db.SaveChangesAsync(); }
    private sealed record AttemptData(Guid Tenant,Guid SessionId,Guid AttemptId,decimal Amount,Guid PlanId,Guid AllocationId,string AccessToken);
    private async Task<(decimal Reserved, decimal Paid, PaymentAttemptStatus Status)> Financial(Guid id) { await using var db=fixture.CreateDbContext(); var s=await db.Set<TableSession>().AsNoTracking().SingleAsync(x=>x.Id==id); var a=await db.Set<PaymentAttempt>().AsNoTracking().Where(x=>x.TableSessionId==id).OrderByDescending(x=>x.CreatedAt).FirstAsync(); return (s.ReservedAmount,s.PaidAmount,a.Status); }
    private sealed record DetailedSnapshot(PaymentAttemptStatus Status, decimal Amount, decimal Paid, decimal Reserved, string SessionStatus, int Ownership);
    private async Task<DetailedSnapshot> Detailed(AttemptData x) { await using var db=fixture.CreateDbContext(); var s=await db.Set<TableSession>().AsNoTracking().SingleAsync(a=>a.Id==x.SessionId); var a=await db.Set<PaymentAttempt>().AsNoTracking().SingleAsync(a=>a.Id==x.AttemptId); var own=await db.Set<PaymentAttemptAllocation>().AsNoTracking().CountAsync(a=>a.PaymentAttemptId==x.AttemptId); return new(a.Status,a.Amount,s.PaidAmount,s.ReservedAmount,s.Status,own); }
    [Theory]
    [InlineData("pix")]
    [InlineData("credit")]
    [InlineData("debit")]
    public async Task NonCashAttemptCannotUseConfirmCash(string method) { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,10m); var p=await CreatePlan(c); var created=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p.PlanId,allocationIds=new[]{p.AllocationId},paymentMethod=method},c.Device.AccessToken,Guid.NewGuid()); using var j=JsonDocument.Parse(await created.Content.ReadAsStringAsync()); var id=j.RootElement.GetProperty("attemptId").GetGuid(); var before=await Financial(c.SessionId); var token=await fixture.CreateUserTokenAsync(await TenantId(c.SessionId),"payments.confirm_cash"); var r=await fixture.PostWithIdempotencyAsync($"api/v1/payments/attempts/{id}/confirm-cash",new{},token,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Conflict,r.StatusCode); Assert.Equal(before,await Financial(c.SessionId)); }
    [Theory]
    [InlineData("declined")]
    [InlineData("cancelled")]
    [InlineData("expired")]
    public async Task ReleasedAllocationCanBeReservedAgain(string state) { var x=await CreateAttempt(); var svc=fixture.CreatePaymentLifecycleService(); if(state=="declined") await svc.FailAsync(x.Tenant,x.AttemptId); else if(state=="cancelled") await svc.CancelAsync(x.Tenant,x.AttemptId); else await svc.ExpireAsync(x.Tenant,x.AttemptId); var retry=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=x.SessionId,paymentPlanId=x.PlanId,allocationIds=new[]{x.AllocationId},paymentMethod="cash"},x.AccessToken,Guid.NewGuid()); Assert.Equal(HttpStatusCode.Created,retry.StatusCode); }
    private async Task<AttemptData> CreateAttempt() { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,10m); var p=await CreatePlan(c); var r=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new{tableSessionId=c.SessionId,paymentPlanId=p.PlanId,allocationIds=new[]{p.AllocationId},paymentMethod="cash"},c.Device.AccessToken,Guid.NewGuid()); r.EnsureSuccessStatusCode(); using var j=JsonDocument.Parse(await r.Content.ReadAsStringAsync()); var id=j.RootElement.GetProperty("attemptId").GetGuid(); return new(await TenantId(c.SessionId),c.SessionId,id,j.RootElement.GetProperty("amount").GetDecimal(),p.PlanId,p.AllocationId,c.Device.AccessToken); }
    private async Task<AttemptData> CreatePartialAttempt() { var c=await fixture.CreateOpenSessionAsync(); await SetTotal(c.SessionId,100m); var r=await fixture.PostWithIdempotencyAsync("api/v1/table-device/session/payment-plan",new { sessionId=c.SessionId, mode="custom_amount", amount=40m }, c.Device.AccessToken, Guid.NewGuid()); r.EnsureSuccessStatusCode(); using var p=JsonDocument.Parse(await r.Content.ReadAsStringAsync()); var planId=p.RootElement.GetProperty("planId").GetGuid(); var allocationId=p.RootElement.GetProperty("allocations")[0].GetProperty("allocationId").GetGuid(); var a=await fixture.PostWithIdempotencyAsync("api/v1/table-device/payments/attempts",new { tableSessionId=c.SessionId, paymentPlanId=planId, allocationIds=new[]{allocationId}, paymentMethod="cash" }, c.Device.AccessToken, Guid.NewGuid()); a.EnsureSuccessStatusCode(); using var j=JsonDocument.Parse(await a.Content.ReadAsStringAsync()); var id=j.RootElement.GetProperty("attemptId").GetGuid(); return new(await TenantId(c.SessionId),c.SessionId,id,j.RootElement.GetProperty("amount").GetDecimal(),planId,allocationId,c.Device.AccessToken); }
    private async Task<Guid> TenantId(Guid id) { await using var db = fixture.CreateDbContext(); return await db.Set<TableSession>().Where(x => x.Id == id).Select(x => x.EstablishmentId).SingleAsync(); }
    private async Task<(Guid PlanId, Guid AllocationId)> CreatePlan(Phase1ApiFixture.OpenSessionContext c) { var r = await fixture.PostWithIdempotencyAsync("api/v1/table-device/session/payment-plan", new { sessionId = c.SessionId, mode = "total" }, c.Device.AccessToken, Guid.NewGuid()); r.EnsureSuccessStatusCode(); using var j = JsonDocument.Parse(await r.Content.ReadAsStringAsync()); return (j.RootElement.GetProperty("planId").GetGuid(), j.RootElement.GetProperty("allocations")[0].GetProperty("allocationId").GetGuid()); }
}
