<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Appizza.BuildingBlocks\Appizza.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Media\Appizza.Modules.Media.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Establishments\Appizza.Modules.Establishments.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Identity\Appizza.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Devices\Appizza.Modules.Devices.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Tables\Appizza.Modules.Tables.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Catalog\Appizza.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Ordering\Appizza.Modules.Ordering.csproj" />
    <ProjectReference Include="..\..\Modules\Appizza.Modules.Kitchen\Appizza.Modules.Kitchen.csproj" />
  </ItemGroup>

</Project>
