using System.Security.Claims;
using System.Text.Json;
using Appizza.Modules.Catalog;
using Appizza.Modules.Devices;
using Appizza.Modules.Integration;
using Appizza.Modules.Kitchen;
using Appizza.Modules.Ordering;
using Appizza.Modules.Tables;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api;

public sealed record CreateChangeRequest(JsonElement Configuration, string? ReasonCode, string? CustomerNote, long? ExpectedOrderItemVersion);
public sealed record ConfirmChangeReview(int RequestVersion, string ReviewHash, bool Accepted);
public interface IPhase5ChangeHook
{
    Task ReachAsync(string stage, CancellationToken cancellationToken);
}

public sealed record Phase5ReviewDiagnostic(string Stage, string Configuration, string ReviewHash, string ConfigurationVersion, decimal UnitAmount, long CatalogVersion, long AvailabilityVersion);
public interface IPhase5ReviewDiagnostics { void Capture(Phase5ReviewDiagnostic diagnostic); }
public sealed class Phase5ReviewDiagnostics : IPhase5ReviewDiagnostics { public void Capture(Phase5ReviewDiagnostic diagnostic) { } }

public sealed class Phase5ChangeHook : IPhase5ChangeHook
{
    public Task ReachAsync(string stage, CancellationToken cancellationToken) => Task.CompletedTask;
}

public static class Phase5ChangeEndpoints
{
    private static readonly string[] Pending = ["pending_validation", "pending_customer_confirmation", "pending_operational_decision"];

    public static IEndpointRouteBuilder MapPhase5ChangeEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/table-device").RequireAuthorization();
        group.MapPost("/order-items/{id:guid}/change-requests", Create);
        group.MapPost("/order-item-requests/{id:guid}/confirm-review", ConfirmReview);
        return app;
    }

    private static async Task<IResult> Create(Guid id, CreateChangeRequest body, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, IPhase5ChangeHook hook, IPhase5ReviewDiagnostics diagnostics, CancellationToken ct)
    {
        if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório.");
        var device = await Device(principal, db, ct); if (device.Error is not null) return device.Error;
        var tenant = device.Device!.EstablishmentId!.Value; const string operation = "ordering.change.create"; var hash = Hash(new { id, body });
        var located = await db.Set<OrderItem>().AsNoTracking().Where(x => x.Id == id).Join(db.Set<Order>(), x => x.OrderId, x => x.Id, (item, order) => new { item, order }).SingleOrDefaultAsync(ct);
        if (located is null || located.order.EstablishmentId != tenant) return Results.NotFound();
        var binding = await db.Set<DeviceTableBinding>().AsNoTracking().SingleOrDefaultAsync(x => x.DeviceId == device.Device.Id && x.UnboundAt == null, ct); if (binding is null) return Results.NotFound();
        var session = await db.Set<TableSession>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == located.order.TableSessionId && x.EstablishmentId == tenant && x.DiningTableId == binding.DiningTableId && x.Status == "open", ct); if (session is null) return Error(409, "SESSION_NOT_ACTIVE", "Sessão não está ativa.");

        var priced = await Price(db, tenant, located.item, body.Configuration, ct); if (priced.Error is not null) return priced.Error; diagnostics.Capture(Diagnostic("create", priced));
        await hook.ReachAsync("change-before-locks", ct);
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return await Replay(tx, replay, ct);
        await LockCommercial(db, session.Id, located.order.Id, id, ct); db.ChangeTracker.Clear();
        var currentDevice = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == device.Device.Id && x.EstablishmentId == tenant, ct);
        if (currentDevice is null || currentDevice.Status != "active" || currentDevice.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != principal.FindFirstValue("credential_version"))
            return currentDevice?.Status == "blocked" ? Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.") : Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.");
        var order = await db.Set<Order>().SingleAsync(x => x.Id == located.order.Id && x.EstablishmentId == tenant, ct); var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == id && x.OrderId == order.Id, ct); var lockedSession = await db.Set<TableSession>().SingleAsync(x => x.Id == session.Id, ct);
        if (item.CommercialStatus == "cancelled") return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CHANGE_NOT_ALLOWED", "Item cancelado não pode ser alterado.", ct);
        if (body.ExpectedOrderItemVersion is long expected && expected != item.Version) return await Conflict(db, tx, tenant, operation, key, hash, "CONCURRENCY_CONFLICT", "Versão desatualizada.", ct);
        if (await db.Set<OrderItemRequest>().AnyAsync(x => x.OrderItemId == id && Pending.Contains(x.Status), ct)) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_ALREADY_PENDING", "Já existe solicitação pendente.", ct);
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE order_item_id = {id} AND establishment_id = {tenant} FOR UPDATE", ct);
        await hook.ReachAsync("change-after-locks", ct);
        var production = await db.Set<ProductionItem>().AsNoTracking().SingleOrDefaultAsync(x => x.OrderItemId == id && x.EstablishmentId == tenant, ct); var authority = Authority(production?.Status); if (authority == ChangeAuthority.Forbidden) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CHANGE_NOT_ALLOWED", "Alteração não permitida no estado atual.", ct);
        var definitive = await Price(db, tenant, item, body.Configuration, ct); if (definitive.Error is not null) return definitive.Error;
        var oldUnit = await EffectiveUnit(db, item, ct); var difference = definitive.Item!.UnitAmount - oldUnit; var requiresReview = difference > 0; var now = DateTimeOffset.UtcNow;
        var status = requiresReview ? "pending_customer_confirmation" : authority == ChangeAuthority.Kitchen ? "pending_operational_decision" : "approved";
        var request = new OrderItemRequest { Id = Guid.NewGuid(), EstablishmentId = tenant, OrderId = order.Id, OrderItemId = item.Id, RequestType = "change", RequestedConfiguration = body.Configuration.GetRawText(), ReviewedSnapshot = JsonSerializer.Serialize(definitive.Item), ReviewHash = definitive.ReviewHash, ReasonCode = body.ReasonCode ?? "CUSTOMER_CHANGE", CustomerNote = body.CustomerNote, Status = status, RequiredApprovalLevel = authority == ChangeAuthority.Kitchen ? "kitchen" : null, PriceDifference = difference, Source = "customer", OriginalRevisionNumber = item.CurrentRevisionNumber, RequestedByDeviceId = currentDevice.Id, RequestedAt = now, DecidedAt = status == "approved" ? now : null, DecidedByDeviceId = status == "approved" ? currentDevice.Id : null };
        db.Add(request); OrderItemRevision? revision = null; if (status == "approved") revision = await Apply(db, lockedSession, order, item, request, definitive, device.Device.Id, null, now, ct); else AddEvent(db, tenant, "order-item-change-requested.v1", "OrderItemChangeRequested", request, item, now, null);
        await db.SaveChangesAsync(ct); var payload = Response(request, definitive, revision, order, lockedSession); await Record(db, tenant, operation, key, hash, 201, payload, now, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json", statusCode: 201);
    }

    private static async Task<IResult> ConfirmReview(Guid id, ConfirmChangeReview body, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, IPhase5ChangeHook hook, IPhase5ReviewDiagnostics diagnostics, CancellationToken ct)
    {
        if (!body.Accepted) return Error(400, "CUSTOMER_REVIEW_REQUIRED", "A confirmação deve ser explícita."); if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório.");
        var device = await Device(principal, db, ct); if (device.Error is not null) return device.Error; var tenant = device.Device!.EstablishmentId!.Value; const string operation = "ordering.change.confirm-review"; var hash = Hash(new { id, body });
        var preview = await db.Set<OrderItemRequest>().AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant && x.RequestType == "change", ct); if (preview is null || preview.RequestedByDeviceId != device.Device.Id) return Results.NotFound();
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return await Replay(tx, replay, ct); var sessionId = await db.Set<Order>().Where(x => x.Id == preview.OrderId).Select(x => x.TableSessionId).SingleAsync(ct); await LockCommercial(db, sessionId, preview.OrderId, preview.OrderItemId, ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item_request WHERE id = {id} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE order_item_id = {preview.OrderItemId} AND establishment_id = {tenant} FOR UPDATE", ct); db.ChangeTracker.Clear();
        var currentDevice = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == device.Device.Id && x.EstablishmentId == tenant, ct);
        if (currentDevice is null || currentDevice.Status != "active" || currentDevice.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != principal.FindFirstValue("credential_version"))
            return currentDevice?.Status == "blocked" ? Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.") : Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.");
        var request = await db.Set<OrderItemRequest>().SingleAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (request.Status != "pending_customer_confirmation") return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_REVIEW_ALREADY_CONFIRMED", "Review já confirmado ou indisponível.", ct); if (request.RequestVersion != body.RequestVersion || request.ReviewHash != body.ReviewHash) return await Conflict(db, tx, tenant, operation, key, hash, "CUSTOMER_REVIEW_OBSOLETE", "Review não corresponde à versão atual.", ct);
        var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == request.OrderItemId, ct); using var configuration = JsonDocument.Parse(request.RequestedConfiguration!); var definitive = await Price(db, tenant, item, configuration.RootElement, ct); if (definitive.Error is not null) return await Conflict(db, tx, tenant, operation, key, hash, "CUSTOMER_REVIEW_OBSOLETE", "Estado autoritativo mudou; solicite nova avaliação.", ct); diagnostics.Capture(Diagnostic("confirm", definitive)); if (definitive.ReviewHash != request.ReviewHash) return await Conflict(db, tx, tenant, operation, key, hash, "CUSTOMER_REVIEW_OBSOLETE", "Estado autoritativo mudou; solicite nova avaliação.", ct);
        var production = await db.Set<ProductionItem>().AsNoTracking().SingleOrDefaultAsync(x => x.OrderItemId == item.Id && x.EstablishmentId == tenant, ct); var authority = Authority(production?.Status); if (authority == ChangeAuthority.Forbidden) return await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CHANGE_NOT_ALLOWED", "Alteração não permitida no estado atual.", ct);
        var now = DateTimeOffset.UtcNow; request.CustomerConfirmedVersion = body.RequestVersion; request.CustomerConfirmedAt = now; var order = await db.Set<Order>().SingleAsync(x => x.Id == request.OrderId, ct); var session = await db.Set<TableSession>().SingleAsync(x => x.Id == sessionId, ct); OrderItemRevision? revision = null; if (authority == ChangeAuthority.Kitchen && request.ProductionAction is null) request.Status = "pending_operational_decision"; else { request.Status = "approved"; request.DecidedAt ??= now; request.DecidedByDeviceId ??= device.Device.Id; revision = await Apply(db, session, order, item, request, definitive, device.Device.Id, null, now, ct); }
        AddEvent(db, tenant, "order-item-change-review-confirmed.v1", "OrderItemChangeReviewConfirmed", request, item, now, null); await db.SaveChangesAsync(ct); var payload = Response(request, definitive, revision, order, session); await Record(db, tenant, operation, key, hash, 200, payload, now, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    internal static async Task<(bool Handled, IResult Result)> Decide(OrderItemRequest requestPreview, DecideCancellationRequest body, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, IPhase5ChangeHook hook, CancellationToken ct)
    {
        if (requestPreview.RequestType != "change") return (false, Results.Empty); if (body.Decision is not ("approve" or "reject")) return (true, Error(400, "INVALID_DECISION", "Decisão inválida.")); if (!principal.IsTokenType("user")) return (true, Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."));
        if (body.Decision == "approve" && body.ProductionAction is not ("continue" or "restart")) return (true, Error(409, "PRODUCTION_ACTION_REQUIRED", "Escolha continue ou restart.")); if (body.Decision == "reject" && body.ProductionAction is not (null or "reject")) return (true, Error(409, "PRODUCTION_ACTION_NOT_ALLOWED", "Ação inválida para rejeição.")); if (!Guid.TryParse(http.Headers["Idempotency-Key"], out var key)) return (true, Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key UUID é obrigatório."));
        var tenant = principal.RequiredGuid("establishment_id"); var user = principal.RequiredGuid("sub"); var denied = await Authorize(principal, db, "kitchen.order_item_request.decide", ct); if (denied is not null) return (true, denied); const string operation = "ordering.change.decide"; var hash = Hash(new { requestPreview.Id, body });
        await using var tx = await db.Database.BeginTransactionAsync(ct); var replay = await Begin(db, tenant, operation, key, hash, ct); if (replay is not null) return (true, await Replay(tx, replay, ct)); var sessionId = await db.Set<Order>().Where(x => x.Id == requestPreview.OrderId).Select(x => x.TableSessionId).SingleAsync(ct); await LockCommercial(db, sessionId, requestPreview.OrderId, requestPreview.OrderItemId, ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item_request WHERE id = {requestPreview.Id} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM kitchen.production_item WHERE order_item_id = {requestPreview.OrderItemId} AND establishment_id = {tenant} FOR UPDATE", ct); db.ChangeTracker.Clear();
        var request = await db.Set<OrderItemRequest>().SingleAsync(x => x.Id == requestPreview.Id && x.EstablishmentId == tenant, ct); if (request.Status is not ("pending_operational_decision" or "pending_customer_confirmation")) return (true, await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_REQUEST_ALREADY_DECIDED", "Solicitação já decidida.", ct)); if (body.ExpectedVersion is long expected && expected != request.Version) return (true, await Conflict(db, tx, tenant, operation, key, hash, "CONCURRENCY_CONFLICT", "Versão desatualizada.", ct));
        var production = await db.Set<ProductionItem>().SingleOrDefaultAsync(x => x.OrderItemId == request.OrderItemId && x.EstablishmentId == tenant, ct); if (Authority(production?.Status) != ChangeAuthority.Kitchen) return (true, await Conflict(db, tx, tenant, operation, key, hash, "ORDER_ITEM_CHANGE_NOT_ALLOWED", "Estado operacional mudou.", ct));
        var now = DateTimeOffset.UtcNow; request.DecidedAt = now; request.DecidedByUserId = user; request.DecisionReason = body.Reason; request.ProductionAction = body.Decision == "approve" ? body.ProductionAction : "reject"; var item = await db.Set<OrderItem>().SingleAsync(x => x.Id == request.OrderItemId, ct); var order = await db.Set<Order>().SingleAsync(x => x.Id == request.OrderId, ct); var session = await db.Set<TableSession>().SingleAsync(x => x.Id == sessionId, ct); OrderItemRevision? revision = null;
        if (body.Decision == "reject") { request.Status = "rejected"; AddEvent(db, tenant, "order-item-change-rejected.v1", "OrderItemChangeRejected", request, item, now, "reject"); }
        else { request.DecidedAt = now; request.DecidedByUserId = user; request.DecisionReason = body.Reason; request.ProductionAction = body.ProductionAction; if (request.Status == "pending_customer_confirmation") { request.Status = "pending_customer_confirmation"; } else { using var configuration = JsonDocument.Parse(request.RequestedConfiguration!); var definitive = await Price(db, tenant, item, configuration.RootElement, ct); if (definitive.Error is not null || definitive.ReviewHash != request.ReviewHash) return (true, await Conflict(db, tx, tenant, operation, key, hash, "CUSTOMER_REVIEW_OBSOLETE", "Estado autoritativo mudou.", ct)); request.Status = "approved"; revision = await Apply(db, session, order, item, request, definitive, null, user, now, ct); } }
        await db.SaveChangesAsync(ct); var priced = request.ReviewedSnapshot is null ? null : JsonSerializer.Deserialize<AuthoritativeCartItem>(request.ReviewedSnapshot); var response = JsonSerializer.Serialize(new { requestId = request.Id, requestVersion = request.RequestVersion, status = request.Status, productionAction = request.ProductionAction, revisionNumber = revision?.RevisionNumber, orderItemStatus = item.CommercialStatus, totals = new { order.TotalAmount, sessionTotalAmount = session.TotalAmount } }); await Record(db, tenant, operation, key, hash, 200, response, now, ct); await tx.CommitAsync(ct); return (true, Results.Content(response, "application/json"));
    }

    private static async Task<OrderItemRevision> Apply(AppizzaDbContext db, TableSession session, Order order, OrderItem item, OrderItemRequest request, PricedChange priced, Guid? device, Guid? user, DateTimeOffset now, CancellationToken ct)
    {
        var next = item.CurrentRevisionNumber + 1; var previousUnit = await EffectiveUnit(db, item, ct); var previousTotal = item.TotalAmount; var delta = priced.Item!.TotalAmount - previousTotal;
        var revision = new OrderItemRevision { Id = Guid.NewGuid(), EstablishmentId = request.EstablishmentId, OrderItemId = item.Id, RevisionNumber = next, SourceRequestId = request.Id, Snapshot = priced.Item.Snapshot.GetRawText(), SnapshotSchemaVersion = 1, Configuration = priced.Item.Configuration.GetRawText(), PreviousUnitAmount = previousUnit, UnitAmount = priced.Item.UnitAmount, PreviousTotalAmount = previousTotal, TotalAmount = priced.Item.TotalAmount, PriceDifference = priced.Item.UnitAmount - previousUnit, CatalogRevisionId = priced.CatalogRevisionId, CatalogVersion = priced.CatalogVersion, AvailabilityVersion = priced.AvailabilityVersion, ConfigurationVersion = priced.Item.ConfigurationVersion, EffectiveAt = now, EffectiveByDeviceId = device, EffectiveByUserId = user, Origin = request.Source, CreatedAt = now };
        db.Add(revision); await SyncProjections(db, item, priced.Item.Configuration, ct); item.CurrentRevisionNumber = next; item.ProductVariantId = priced.Item.ProductVariantId; item.ProductName = priced.Item.ProductName; item.VariantName = priced.Item.VariantName; item.UnitAmount = priced.Item.UnitAmount; item.TotalAmount = priced.Item.TotalAmount; item.ConfigurationVersion = priced.Item.ConfigurationVersion; item.CatalogRevisionId = priced.CatalogRevisionId; item.CatalogVersion = priced.CatalogVersion; item.AvailabilityVersion = priced.AvailabilityVersion; item.UpdatedAt = now; order.SubtotalAmount += delta; order.TotalAmount += delta; order.UpdatedAt = now; session.SubtotalAmount += delta; session.TotalAmount += delta; session.RemainingAmount = Math.Max(0, session.RemainingAmount + delta); session.UpdatedAt = now;
        AddEvent(db, request.EstablishmentId, "order-item-change-approved.v1", "OrderItemChangeApproved", request, item, now, request.ProductionAction); AddEvent(db, request.EstablishmentId, "order-item-changed.v1", "OrderItemChanged", request, item, now, request.ProductionAction); return revision;
    }

    private static async Task SyncProjections(AppizzaDbContext db, OrderItem item, JsonElement configuration, CancellationToken ct)
    {
        if (Try(configuration, "ingredients", out var selected) && selected.ValueKind == JsonValueKind.Array)
            foreach (var row in selected.EnumerateArray())
            {
                if (!Try(row, "ingredientId", out var idNode) || !Guid.TryParse(idNode.GetString(), out var ingredientId)) continue;
                if (await db.Set<OrderItemIngredient>().AnyAsync(x => x.OrderItemId == item.Id && x.IngredientId == ingredientId && x.Action == "add", ct)) continue;
                var ingredient = await db.Set<Ingredient>().AsNoTracking().SingleAsync(x => x.Id == ingredientId, ct);
                var link = await db.Set<ProductIngredient>().AsNoTracking().SingleAsync(x => x.ProductId == item.ProductId && x.IngredientId == ingredientId, ct);
                db.Add(new OrderItemIngredient { Id = Guid.NewGuid(), OrderItemId = item.Id, IngredientId = ingredientId, Name = ingredient.Name, Action = "add", Quantity = Try(row, "quantity", out var q) && q.TryGetDecimal(out var quantity) ? quantity : 1m, AdditionalAmount = link.AdditionalPrice });
            }
        if (Try(configuration, "pizza", out var pizza) && Try(pizza, "fractions", out var fractions) && fractions.ValueKind == JsonValueKind.Array)
        {
            var custom = fractions.EnumerateArray().FirstOrDefault(x => Try(x, "custom", out _));
            if (custom.ValueKind != JsonValueKind.Undefined)
            {
                var projection = await db.Set<OrderItemPizzaFraction>().SingleOrDefaultAsync(x => x.OrderItemId == item.Id && x.IsCustom, ct);
                if (projection is not null) projection.Configuration = custom.GetRawText();
            }
        }
    }

    private static async Task<PricedChange> Price(AppizzaDbContext db, Guid tenant, OrderItem item, JsonElement configuration, CancellationToken ct)
    {
        var state = await db.Set<CatalogState>().AsNoTracking().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct); if (state?.CurrentPublishedRevisionId is not Guid revisionId) return PricedChange.Failure(Error(409, "CATALOG_NOT_PUBLISHED", "Catálogo não publicado.")); var revision = await db.Set<CatalogRevision>().AsNoTracking().SingleAsync(x => x.Id == revisionId && x.EstablishmentId == tenant && x.Status == "published", ct); using var catalog = JsonDocument.Parse(revision.Snapshot);
        var products = await db.Set<ProductAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductId).ToHashSetAsync(ct); var variants = await db.Set<ProductVariantAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.ProductVariantId).ToHashSetAsync(ct); var ingredients = await db.Set<IngredientAvailability>().Where(x => x.EstablishmentId == tenant && !x.EffectivelyAvailable).Select(x => x.IngredientId).ToHashSetAsync(ct);
        Guid? variant = item.ProductVariantId; if (Try(configuration, "productVariantId", out var variantNode) && variantNode.ValueKind == JsonValueKind.String && Guid.TryParse(variantNode.GetString(), out var parsed)) variant = parsed;
        var intent = new CartIntentItem(item.LocalCartItemId, item.ProductId, variant, item.Quantity, "", null, configuration.Clone()); var result = Phase4Pricing.Simulate(catalog.RootElement, new CartSimulationRequest((await db.Set<Order>().Where(x => x.Id == item.OrderId).Select(x => x.TableSessionId).SingleAsync(ct)), Guid.NewGuid(), state.CatalogVersion, state.AvailabilityVersion, [intent]), products, variants, ingredients); if (!result.CanSubmit || result.Items.Count != 1) { var issue = result.Issues.Count == 0 ? null : result.Issues[0]; return PricedChange.Failure(Error(409, issue?.ErrorCode ?? "INVALID_CONFIGURATION", issue?.Message ?? "Configuração inválida.")); }
        var authoritative = result.Items[0]; var reviewPayload = JsonSerializer.Serialize(new { authoritative.ProductId, authoritative.ProductVariantId, authoritative.UnitAmount, authoritative.TotalAmount, authoritative.ConfigurationVersion, configuration = authoritative.Configuration }); var reviewHash = Phase4Pricing.Hash(Phase4Pricing.Canonicalize(reviewPayload)); return new(authoritative, revision.Id, state.CatalogVersion, state.AvailabilityVersion, reviewHash, null);
    }

    private static async Task<decimal> EffectiveUnit(AppizzaDbContext db, OrderItem item, CancellationToken ct) => item.CurrentRevisionNumber == 0 ? item.UnitAmount : await db.Set<OrderItemRevision>().Where(x => x.OrderItemId == item.Id && x.RevisionNumber == item.CurrentRevisionNumber).Select(x => x.UnitAmount).SingleAsync(ct);
    private static ChangeAuthority Authority(string? status) => status switch { null or "awaiting_acceptance" or "accepted" or "awaiting_preparation" => ChangeAuthority.Automatic, "in_preparation" or "paused" => ChangeAuthority.Kitchen, _ => ChangeAuthority.Forbidden };
    private static string Response(OrderItemRequest request, PricedChange priced, OrderItemRevision? revision, Order order, TableSession session) => JsonSerializer.Serialize(new { requestId = request.Id, requestVersion = request.RequestVersion, status = request.Status, requiresCustomerReview = request.Status == "pending_customer_confirmation", authoritativeConfiguration = priced.Item!.Configuration, authoritativeAmounts = new { unitAmount = priced.Item.UnitAmount, totalAmount = priced.Item.TotalAmount }, priceDifference = request.PriceDifference, catalogVersion = priced.CatalogVersion, availabilityVersion = priced.AvailabilityVersion, configurationVersion = priced.Item.ConfigurationVersion, reviewHash = request.ReviewHash, revisionNumber = revision?.RevisionNumber, totals = new { totalAmount = order.TotalAmount, sessionTotalAmount = session.TotalAmount }, version = request.Version });
    private static void AddEvent(AppizzaDbContext db, Guid tenant, string type, string name, OrderItemRequest request, OrderItem item, DateTimeOffset now, string? action) { var eventId = Guid.NewGuid(); db.Add(new OutboxMessage { Id = eventId, EstablishmentId = tenant, EventType = type, SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId, eventType = name, schemaVersion = 1, occurredAtUtc = now, establishmentId = tenant, data = new { requestId = request.Id, requestVersion = request.RequestVersion, orderId = request.OrderId, orderItemId = item.Id, revisionNumber = item.CurrentRevisionNumber, productionAction = action } }), OccurredAt = now }); }
    private static bool Try(JsonElement value, string name, out JsonElement result) { if (value.ValueKind == JsonValueKind.Object) foreach (var property in value.EnumerateObject()) if (property.Name.Equals(name, StringComparison.OrdinalIgnoreCase)) { result = property.Value; return true; } result = default; return false; }
    private static string Hash(object value) => Phase4Pricing.Hash(JsonSerializer.Serialize(value));
    private static async Task LockCommercial(AppizzaDbContext db, Guid session, Guid order, Guid item, CancellationToken ct) { await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM tables.table_session WHERE id = {session} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.customer_order WHERE id = {order} FOR UPDATE", ct); await db.Database.ExecuteSqlInterpolatedAsync($"SELECT 1 FROM ordering.order_item WHERE id = {item} FOR UPDATE", ct); }
    private static async Task<IdempotencyRecord?> Begin(AppizzaDbContext db, Guid tenant, string op, Guid key, string hash, CancellationToken ct) { await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({tenant.ToString("N") + "|" + op + "|" + key.ToString("N")}, 0))", ct); var replay = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == op && x.IdempotencyKey == key.ToString(), ct); if (replay is not null && replay.RequestHash != hash) return new IdempotencyRecord { IdempotencyKey = key.ToString(), OperationType = op, RequestHash = hash, ResponseStatus = 409, ResponsePayload = JsonSerializer.Serialize(new { type = "about:blank", title = "A chave foi usada com outro request.", status = 409, detail = "A chave foi usada com outro request.", errorCode = "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST" }) }; return replay; }
    private static async Task<IResult> Replay(Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction tx, IdempotencyRecord row, CancellationToken ct) { await tx.CommitAsync(ct); return Results.Content(row.ResponsePayload!, row.ResponseStatus == 409 ? "application/problem+json" : "application/json", statusCode: row.ResponseStatus); }
    private static async Task Record(AppizzaDbContext db, Guid tenant, string op, Guid key, string hash, int status, string payload, DateTimeOffset now, CancellationToken ct) { db.Add(new IdempotencyRecord { EstablishmentId = tenant, OperationType = op, IdempotencyKey = key.ToString(), RequestHash = hash, ResponseStatus = status, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); }
    private static async Task<IResult> Conflict(AppizzaDbContext db, Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction tx, Guid tenant, string op, Guid key, string hash, string code, string detail, CancellationToken ct) { var payload = JsonSerializer.Serialize(new { type = "about:blank", title = detail, status = 409, detail, errorCode = code }); await Record(db, tenant, op, key, hash, 409, payload, DateTimeOffset.UtcNow, ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/problem+json", statusCode: 409); }
    private static async Task<(Device? Device, IResult? Error)> Device(ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) { if (!p.IsTokenType("device")) return (null, Error(403, "INVALID_TOKEN_TYPE", "Token de dispositivo necessário.")); var tenant = p.RequiredGuid("establishment_id"); var id = p.RequiredGuid("sub"); var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (device is null) return (null, Results.NotFound()); if (device.Status == "blocked") return (null, Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.")); if (device.Status != "active" || device.CredentialVersion.ToString(System.Globalization.CultureInfo.InvariantCulture) != p.FindFirstValue("credential_version")) return (null, Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.")); return (device, null); }
    private static async Task<IResult?> Authorize(ClaimsPrincipal p, AppizzaDbContext db, string permission, CancellationToken ct) { var user = p.RequiredGuid("sub"); var tenant = p.RequiredGuid("establishment_id"); if (!await db.Set<Appizza.Modules.Identity.User>().AnyAsync(x => x.Id == user && x.EstablishmentId == tenant && x.Status == "active", ct)) return Results.NotFound(); var resolved = await PermissionResolver.ResolveAsync(db, user, DateTimeOffset.UtcNow, ct); return resolved.Contains(permission) ? null : Error(403, "INSUFFICIENT_PERMISSION", "Permissão insuficiente."); }
    private static IResult Error(int status, string code, string detail) => Results.Problem(statusCode: status, title: detail, detail: detail, extensions: new Dictionary<string, object?> { ["errorCode"] = code });
    private enum ChangeAuthority { Automatic, Kitchen, Forbidden }
    private sealed record PricedChange(AuthoritativeCartItem? Item, Guid CatalogRevisionId, long CatalogVersion, long AvailabilityVersion, string? ReviewHash, IResult? Error) { public static PricedChange Failure(IResult error) => new(null, Guid.Empty, 0, 0, null, error); }
    private static Phase5ReviewDiagnostic Diagnostic(string stage, PricedChange value) => new(stage, value.Item!.Configuration.GetRawText(), value.ReviewHash!, value.Item.ConfigurationVersion, value.Item.UnitAmount, value.CatalogVersion, value.AvailabilityVersion);
}
