using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Appizza.Modules.Catalog;
using Appizza.Modules.Identity;
using Appizza.Modules.Media;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.SignalR;

namespace Appizza.Api;

public static class Phase2Endpoints
{
    private const long MaximumMediaBytes = 10 * 1024 * 1024;
    private static readonly HashSet<string> AllowedMediaTypes = new(StringComparer.OrdinalIgnoreCase) { "image/jpeg", "image/png", "image/webp" };

    public static IEndpointRouteBuilder MapPhase2Endpoints(this IEndpointRouteBuilder app)
    {
        var catalog = app.MapGroup("/api/v1/operations/catalog").RequireAuthorization();
        catalog.MapGet("/categories", ListCategories);
        catalog.MapPost("/categories", CreateCategory);
        catalog.MapPut("/categories/{id:guid}", UpdateCategory);
        catalog.MapPost("/categories/{id:guid}/activate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("category", id, "active", p, d, c));
        catalog.MapPost("/categories/{id:guid}/deactivate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("category", id, "inactive", p, d, c));
        catalog.MapPost("/categories/{id:guid}/archive", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("category", id, "archived", p, d, c));
        catalog.MapGet("/products", ListProducts);
        catalog.MapPost("/products", CreateProduct);
        catalog.MapPut("/products/{id:guid}", UpdateProduct);
        catalog.MapPost("/products/{id:guid}/activate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("product", id, "active", p, d, c));
        catalog.MapPost("/products/{id:guid}/deactivate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("product", id, "inactive", p, d, c));
        catalog.MapPost("/products/{id:guid}/archive", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("product", id, "archived", p, d, c));
        catalog.MapPost("/products/{productId:guid}/variants", CreateVariant);
        catalog.MapGet("/product-variants", ListVariants);
        catalog.MapGet("/ingredients", ListIngredients);
        catalog.MapPost("/ingredients", CreateIngredient);
        catalog.MapPut("/ingredients/{id:guid}", UpdateIngredient);
        catalog.MapPost("/ingredients/{id:guid}/activate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("ingredient", id, "active", p, d, c));
        catalog.MapPost("/ingredients/{id:guid}/deactivate", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("ingredient", id, "inactive", p, d, c));
        catalog.MapPost("/ingredients/{id:guid}/archive", (Guid id, ClaimsPrincipal p, AppizzaDbContext d, CancellationToken c) => SetLifecycle("ingredient", id, "archived", p, d, c));
        catalog.MapPut("/products/{productId:guid}/ingredients", ConfigureIngredients);
        catalog.MapPut("/products/{productId:guid}/categories", ConfigureProductCategories);
        catalog.MapPut("/products/{productId:guid}/customization-groups", ConfigureProductCustomizationGroups);
        catalog.MapGet("/customization-groups", ListCustomizationGroups);
        catalog.MapPost("/customization-groups", CreateCustomizationGroup);
        catalog.MapGet("/pizza-sizes", ListPizzaSizes);
        catalog.MapPost("/pizza-sizes", CreatePizzaSize);
        catalog.MapGet("/doughs", ListDoughs);
        catalog.MapPost("/doughs", CreateDough);
        catalog.MapGet("/crusts", ListCrusts);
        catalog.MapPost("/crusts", CreateCrust);
        catalog.MapPut("/products/{productId:guid}/pizza-configuration", ConfigurePizza);
        catalog.MapPut("/products/{productId:guid}/combo-configuration", ConfigureCombo);
        catalog.MapPost("/validate", ValidateCatalog);
        catalog.MapPost("/publish", PublishCatalog);
        catalog.MapGet("/publication", CurrentPublication);
        catalog.MapPost("/availability/ingredients/{ingredientId:guid}/change", SetIngredientAvailability);
        catalog.MapPost("/availability/products/{productId:guid}/change", SetProductAvailability);
        catalog.MapPost("/availability/variants/{variantId:guid}/change", SetVariantAvailability);
        catalog.MapGet("/availability", ListAvailability);

        var media = app.MapGroup("/api/v1/operations/media/assets").RequireAuthorization();
        media.MapPost("/", CreateMediaAsset);
        media.MapPut("/{assetId:guid}/content", UploadMediaAsset).DisableAntiforgery();
        media.MapGet("/{assetId:guid}", GetMediaAsset);
        media.MapGet("/{assetId:guid}/content", DownloadMediaAsset);
        media.MapPost("/{assetId:guid}/archive", ArchiveMediaAsset);
        return app;
    }

    private static async Task<IResult> ListCategories(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied;
        var tenant = Tenant(principal); return Results.Ok(await db.Set<Category>().Where(x => x.EstablishmentId == tenant).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).ToListAsync(ct));
    }

    private static async Task<IResult> CreateCategory(CategoryRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied;
        var tenant = Tenant(principal); if (request.ParentCategoryId is Guid parent && !await db.Set<Category>().AnyAsync(x => x.Id == parent && x.EstablishmentId == tenant, ct)) return Results.NotFound();
        if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta.");
        var now = DateTimeOffset.UtcNow; var entity = new Category { Id = Guid.NewGuid(), EstablishmentId = tenant, ParentCategoryId = request.ParentCategoryId, Name = request.Name.Trim(), Description = request.Description, ImageMediaId = request.ImageMediaId, DisplayOrder = request.DisplayOrder, Status = "active", CreatedAt = now, UpdatedAt = now, CreatedBy = UserId(principal) }; db.Add(entity); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/categories/{entity.Id}", entity);
    }

    private static async Task<IResult> UpdateCategory(Guid id, CategoryUpdateRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var entity = await db.Set<Category>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (entity is null) return Results.NotFound(); if (entity.Status == "archived") return Error(409, "CATALOG_ARCHIVED_IS_TERMINAL", "Entidade arquivada não pode ser editada."); if (entity.Version != request.Version) return Error(409, "CONCURRENCY_CONFLICT", "A entidade foi alterada por outra operação."); if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta."); entity.Name = request.Name.Trim(); entity.Description = request.Description; entity.ParentCategoryId = request.ParentCategoryId; entity.ImageMediaId = request.ImageMediaId; entity.DisplayOrder = request.DisplayOrder; entity.UpdatedAt = DateTimeOffset.UtcNow; entity.UpdatedBy = UserId(principal); await db.SaveChangesAsync(ct); return Results.Ok(entity); }

    private static async Task<IResult> ListProducts(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied;
        var tenant = Tenant(principal); return Results.Ok(await db.Set<Product>().Where(x => x.EstablishmentId == tenant).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).ToListAsync(ct));
    }

    private static async Task<IResult> CreateProduct(ProductRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied;
        var tenant = Tenant(principal); if (!CatalogRules.ProductTypes.Contains(request.ProductType)) return Error(400, "CATALOG_INVALID_PRODUCT_TYPE", "Tipo de produto inválido.");
        if (request.PrimaryCategoryId is Guid category && !await db.Set<Category>().AnyAsync(x => x.Id == category && x.EstablishmentId == tenant, ct)) return Results.NotFound();
        if (!await OwnsReadyMedia(db, tenant, request.PrimaryImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta.");
        var now = DateTimeOffset.UtcNow; var product = new Product { Id = Guid.NewGuid(), EstablishmentId = tenant, ProductType = request.ProductType, Name = request.Name.Trim(), Description = request.Description, InternalCode = request.InternalCode, PrimaryCategoryId = request.PrimaryCategoryId, PrimaryImageMediaId = request.PrimaryImageMediaId, Status = "active", DisplayOrder = request.DisplayOrder, RequiresProduction = request.RequiresProduction, AllowsNotes = request.AllowsNotes, MaximumNoteLength = request.MaximumNoteLength, PreparationStationId = request.PreparationStationId, CreatedAt = now, UpdatedAt = now, CreatedBy = UserId(principal) }; db.Add(product); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/products/{product.Id}", product);
    }

    private static async Task<IResult> UpdateProduct(Guid id, ProductUpdateRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var entity = await db.Set<Product>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (entity is null) return Results.NotFound(); if (entity.Status == "archived") return Error(409, "CATALOG_ARCHIVED_IS_TERMINAL", "Entidade arquivada não pode ser editada."); if (entity.Version != request.Version) return Error(409, "CONCURRENCY_CONFLICT", "A entidade foi alterada por outra operação."); if (!await OwnsReadyMedia(db, tenant, request.PrimaryImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta."); entity.Name = request.Name.Trim(); entity.Description = request.Description; entity.InternalCode = request.InternalCode; entity.PrimaryCategoryId = request.PrimaryCategoryId; entity.PrimaryImageMediaId = request.PrimaryImageMediaId; entity.DisplayOrder = request.DisplayOrder; entity.RequiresProduction = request.RequiresProduction; entity.AllowsNotes = request.AllowsNotes; entity.MaximumNoteLength = request.MaximumNoteLength; entity.PreparationStationId = request.PreparationStationId; entity.UpdatedAt = DateTimeOffset.UtcNow; entity.UpdatedBy = UserId(principal); await db.SaveChangesAsync(ct); return Results.Ok(entity); }

    private static async Task<IResult> CreateVariant(Guid productId, VariantRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal);
        if (!await db.Set<Product>().AnyAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct)) return Results.NotFound();
        if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta.");
        var now = DateTimeOffset.UtcNow; var variant = new ProductVariant { Id = Guid.NewGuid(), ProductId = productId, Name = request.Name.Trim(), InternalCode = request.InternalCode, BasePrice = request.BasePrice, ImageMediaId = request.ImageMediaId, Status = "active", DisplayOrder = request.DisplayOrder, CreatedAt = now, UpdatedAt = now }; db.Add(variant); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/products/{productId}/variants/{variant.Id}", variant);
    }

    private static async Task<IResult> ListVariants(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); return Results.Ok(await (from variant in db.Set<ProductVariant>() join product in db.Set<Product>() on variant.ProductId equals product.Id where product.EstablishmentId == tenant select variant).OrderBy(x => x.ProductId).ThenBy(x => x.DisplayOrder).ToListAsync(ct)); }

    private static async Task<IResult> ListCustomizationGroups(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); return Results.Ok(await db.Set<CustomizationGroup>().Where(x => x.EstablishmentId == tenant).OrderBy(x => x.Name).ToListAsync(ct)); }
    private static async Task<IResult> CreateCustomizationGroup(CustomizationGroupRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; if (request.MinimumSelections < 0 || request.MaximumSelections < request.MinimumSelections) return Error(400, "CATALOG_INVALID_CUSTOMIZATION_LIMITS", "Limites de seleção inválidos."); var tenant = Tenant(principal); var now = DateTimeOffset.UtcNow; var group = new CustomizationGroup { Id = Guid.NewGuid(), EstablishmentId = tenant, Name = request.Name.Trim(), Description = request.Description, SelectionType = request.SelectionType, MinimumSelections = request.MinimumSelections, MaximumSelections = request.MaximumSelections, DisplayType = request.DisplayType, Reusable = request.Reusable, CreatedAt = now, UpdatedAt = now }; db.Add(group); foreach (var option in request.Options ?? []) { if (option.LinkedIngredientId is Guid ingredientId && !await db.Set<Ingredient>().AnyAsync(x => x.Id == ingredientId && x.EstablishmentId == tenant, ct) || option.LinkedProductId is Guid productId && !await db.Set<Product>().AnyAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct)) return Results.NotFound(); db.Add(new CustomizationOption { Id = Guid.NewGuid(), CustomizationGroupId = group.Id, Name = option.Name, Description = option.Description, BaseAdditionalPrice = option.AdditionalPrice, LinkedIngredientId = option.LinkedIngredientId, LinkedProductId = option.LinkedProductId, DisplayOrder = option.DisplayOrder, CreatedAt = now, UpdatedAt = now }); } await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/customization-groups/{group.Id}", group); }

    private static async Task<IResult> ListPizzaSizes(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; return Results.Ok(await db.Set<PizzaSize>().Where(x => x.EstablishmentId == Tenant(principal)).OrderBy(x => x.DisplayOrder).ToListAsync(ct)); }
    private static async Task<IResult> CreatePizzaSize(PizzaSizeRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var now = DateTimeOffset.UtcNow; var size = new PizzaSize { Id = Guid.NewGuid(), EstablishmentId = Tenant(principal), Name = request.Name.Trim(), ShortName = request.ShortName, SliceCount = request.SliceCount, DiameterCm = request.DiameterCm, DisplayOrder = request.DisplayOrder, CreatedAt = now, UpdatedAt = now }; db.Add(size); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/pizza-sizes/{size.Id}", size); }
    private static async Task<IResult> ListDoughs(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; return Results.Ok(await db.Set<Dough>().Where(x => x.EstablishmentId == Tenant(principal)).OrderBy(x => x.Name).ToListAsync(ct)); }
    private static async Task<IResult> CreateDough(DoughRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var now = DateTimeOffset.UtcNow; var dough = new Dough { Id = Guid.NewGuid(), EstablishmentId = Tenant(principal), Name = request.Name.Trim(), Description = request.Description, IsDefault = request.IsDefault, CreatedAt = now, UpdatedAt = now }; db.Add(dough); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/doughs/{dough.Id}", dough); }
    private static async Task<IResult> ListCrusts(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; return Results.Ok(await db.Set<Crust>().Where(x => x.EstablishmentId == Tenant(principal)).OrderBy(x => x.Name).ToListAsync(ct)); }
    private static async Task<IResult> CreateCrust(CrustRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta."); var now = DateTimeOffset.UtcNow; var crust = new Crust { Id = Guid.NewGuid(), EstablishmentId = tenant, Name = request.Name.Trim(), Description = request.Description, ImageMediaId = request.ImageMediaId, CreatedAt = now, UpdatedAt = now }; db.Add(crust); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/crusts/{crust.Id}", crust); }

    private static async Task<IResult> ListIngredients(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); return Results.Ok(await db.Set<Ingredient>().Where(x => x.EstablishmentId == tenant).OrderBy(x => x.Name).ToListAsync(ct)); }

    private static async Task<IResult> CreateIngredient(IngredientRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal);
        if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta.");
        var now = DateTimeOffset.UtcNow; var ingredient = new Ingredient { Id = Guid.NewGuid(), EstablishmentId = tenant, Name = request.Name.Trim(), KitchenName = request.KitchenName, Description = request.Description, DefaultAdditionalPrice = request.DefaultAdditionalPrice, UnitOfMeasure = request.UnitOfMeasure, ImageMediaId = request.ImageMediaId, Status = "active", CreatedAt = now, UpdatedAt = now, CreatedBy = UserId(principal) }; db.Add(ingredient); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/catalog/ingredients/{ingredient.Id}", ingredient);
    }

    private static async Task<IResult> UpdateIngredient(Guid id, IngredientUpdateRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var entity = await db.Set<Ingredient>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct); if (entity is null) return Results.NotFound(); if (entity.Status == "archived") return Error(409, "CATALOG_ARCHIVED_IS_TERMINAL", "Entidade arquivada não pode ser editada."); if (entity.Version != request.Version) return Error(409, "CONCURRENCY_CONFLICT", "A entidade foi alterada por outra operação."); if (!await OwnsReadyMedia(db, tenant, request.ImageMediaId, ct)) return Error(409, "MEDIA_ASSET_NOT_READY", "A mídia não pertence ao estabelecimento ou não está pronta."); entity.Name = request.Name.Trim(); entity.KitchenName = request.KitchenName; entity.Description = request.Description; entity.DefaultAdditionalPrice = request.DefaultAdditionalPrice; entity.UnitOfMeasure = request.UnitOfMeasure; entity.ImageMediaId = request.ImageMediaId; entity.UpdatedAt = DateTimeOffset.UtcNow; entity.UpdatedBy = UserId(principal); await db.SaveChangesAsync(ct); return Results.Ok(entity); }

    private static async Task<IResult> SetLifecycle(string kind, Guid id, string status, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); CatalogEntity? entity = kind switch { "category" => await db.Set<Category>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct), "product" => await db.Set<Product>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct), _ => await db.Set<Ingredient>().SingleOrDefaultAsync(x => x.Id == id && x.EstablishmentId == tenant, ct) }; if (entity is null) return Results.NotFound(); var current = kind switch { "category" => ((Category)entity).Status, "product" => ((Product)entity).Status, _ => ((Ingredient)entity).Status }; if (current == "archived" && status != "archived") return Error(409, "CATALOG_ARCHIVED_IS_TERMINAL", "Entidade arquivada não pode ser reativada."); switch (entity) { case Category category: category.Status = status; break; case Product product: product.Status = status; break; case Ingredient ingredient: ingredient.Status = status; break; } entity.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Results.NoContent();
    }

    private static async Task<IResult> ConfigureIngredients(Guid productId, ProductIngredientsRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal);
        if (!await db.Set<Product>().AnyAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct)) return Results.NotFound();
        var ids = request.Items.Select(x => x.IngredientId).ToArray(); if (await db.Set<Ingredient>().CountAsync(x => ids.Contains(x.Id) && x.EstablishmentId == tenant, ct) != ids.Distinct().Count()) return Results.NotFound();
        var entities = request.Items.Select((item, index) => new ProductIngredient { Id = Guid.NewGuid(), ProductId = productId, IngredientId = item.IngredientId, IncludedByDefault = item.IncludedByDefault, RequiredForRecipe = item.RequiredForRecipe, CanBeRemoved = item.CanBeRemoved, CanBeAdded = item.CanBeAdded, MaximumAdditionalQuantity = item.MaximumAdditionalQuantity, AdditionalPrice = item.AdditionalPrice, DisplayOrder = index, ApplicationScope = item.ApplicationScope, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }).ToList();
        if (entities.Any(x => !CatalogRules.IsValidIngredientRule(x))) return Error(400, "CATALOG_INVALID_INGREDIENT_RULE", "Ingrediente obrigatório deve estar incluído e não pode ser removível.");
        db.RemoveRange(await db.Set<ProductIngredient>().Where(x => x.ProductId == productId).ToListAsync(ct)); db.AddRange(entities); await db.SaveChangesAsync(ct); return Results.NoContent();
    }

    private static async Task<IResult> ConfigureProductCategories(Guid productId, IdListRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); if (!await db.Set<Product>().AnyAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct)) return Results.NotFound(); var ids = request.Ids.Distinct().ToArray(); if (await db.Set<Category>().CountAsync(x => ids.Contains(x.Id) && x.EstablishmentId == tenant, ct) != ids.Length) return Results.NotFound(); db.RemoveRange(await db.Set<ProductCategory>().Where(x => x.ProductId == productId).ToListAsync(ct)); db.AddRange(ids.Select((id, index) => new ProductCategory { ProductId = productId, CategoryId = id, DisplayOrder = index })); await db.SaveChangesAsync(ct); return Results.NoContent(); }

    private static async Task<IResult> ConfigureProductCustomizationGroups(Guid productId, IdListRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); if (!await db.Set<Product>().AnyAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct)) return Results.NotFound(); var ids = request.Ids.Distinct().ToArray(); if (await db.Set<CustomizationGroup>().CountAsync(x => ids.Contains(x.Id) && x.EstablishmentId == tenant, ct) != ids.Length) return Results.NotFound(); db.RemoveRange(await db.Set<ProductCustomizationGroup>().Where(x => x.ProductId == productId).ToListAsync(ct)); var now = DateTimeOffset.UtcNow; db.AddRange(ids.Select((id, index) => new ProductCustomizationGroup { Id = Guid.NewGuid(), ProductId = productId, CustomizationGroupId = id, DisplayOrder = index, CreatedAt = now, UpdatedAt = now })); await db.SaveChangesAsync(ct); return Results.NoContent(); }

    private static async Task<IResult> ConfigurePizza(Guid productId, PizzaConfigurationRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var product = await db.Set<Product>().SingleOrDefaultAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct); if (product is null) return Results.NotFound(); if (product.ProductType is not ("pizza" or "custom_pizza")) return Error(409, "CATALOG_PRODUCT_NOT_PIZZA", "Produto não é uma pizza.");
        var sizeIds = request.Sizes.Select(x => x.PizzaSizeId).Distinct().ToArray(); if (await db.Set<PizzaSize>().CountAsync(x => sizeIds.Contains(x.Id) && x.EstablishmentId == tenant, ct) != sizeIds.Length) return Results.NotFound();
        var doughIds = (request.DoughIds ?? []).Distinct().ToArray(); var crustIds = (request.CrustIds ?? []).Distinct().ToArray(); if (await db.Set<Dough>().CountAsync(x => doughIds.Contains(x.Id) && x.EstablishmentId == tenant, ct) != doughIds.Length || await db.Set<Crust>().CountAsync(x => crustIds.Contains(x.Id) && x.EstablishmentId == tenant, ct) != crustIds.Length) return Results.NotFound();
        db.RemoveRange(await db.Set<PizzaProductSize>().Where(x => x.ProductId == productId).ToListAsync(ct)); db.AddRange(request.Sizes.Select(x => new PizzaProductSize { ProductId = productId, PizzaSizeId = x.PizzaSizeId, MaximumFlavorCount = x.MaximumFlavors, DisplayOrder = x.DisplayOrder }));
        if (product.ProductType == "custom_pizza") { db.RemoveRange(await db.Set<CustomPizzaBasePrice>().Where(x => x.CustomPizzaProductId == productId).ToListAsync(ct)); db.AddRange(request.Sizes.Select(x => new CustomPizzaBasePrice { CustomPizzaProductId = productId, PizzaSizeId = x.PizzaSizeId, BasePrice = x.CustomBasePrice ?? 0 })); }
        else { var flavor = await db.Set<PizzaFlavor>().SingleOrDefaultAsync(x => x.ProductId == productId, ct); if (flavor is null) { flavor = new PizzaFlavor { Id = Guid.NewGuid(), ProductId = productId, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }; db.Add(flavor); } db.RemoveRange(await db.Set<PizzaFlavorPrice>().Where(x => x.PizzaFlavorId == flavor.Id).ToListAsync(ct)); db.AddRange(request.Sizes.Select(x => new PizzaFlavorPrice { Id = Guid.NewGuid(), PizzaFlavorId = flavor.Id, PizzaSizeId = x.PizzaSizeId, Price = x.FlavorPrice ?? 0, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow })); }
        db.RemoveRange(await db.Set<PizzaDough>().Where(x => x.ProductId == productId).ToListAsync(ct)); db.AddRange(doughIds.Select(id => new PizzaDough { ProductId = productId, DoughId = id })); db.RemoveRange(await db.Set<PizzaCrust>().Where(x => x.ProductId == productId).ToListAsync(ct)); db.AddRange(crustIds.Select(id => new PizzaCrust { ProductId = productId, CrustId = id }));
        await db.SaveChangesAsync(ct); return Results.NoContent();
    }

    private static async Task<IResult> ConfigureCombo(Guid productId, ComboConfigurationRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var product = await db.Set<Product>().SingleOrDefaultAsync(x => x.Id == productId && x.EstablishmentId == tenant, ct); if (product is null) return Results.NotFound(); if (product.ProductType != "combo") return Error(409, "CATALOG_PRODUCT_NOT_COMBO", "Produto não é combo.");
        if (request.Groups.Any(x => x.MinimumSelections < 0 || x.MaximumSelections < x.MinimumSelections || x.Items.Count == 0)) return Error(400, "CATALOG_INVALID_COMBO", "Grupos do combo são inválidos.");
        var combo = await db.Set<Combo>().SingleOrDefaultAsync(x => x.ProductId == productId, ct); if (combo is null) { combo = new Combo { Id = Guid.NewGuid(), ProductId = productId }; db.Add(combo); } combo.PricingStrategy = request.PricingMode; combo.FixedPrice = request.FixedPrice;
        var oldGroups = await db.Set<ComboGroup>().Where(x => x.ComboId == combo.Id).ToListAsync(ct); var oldGroupIds = oldGroups.Select(x => x.Id).ToArray(); db.RemoveRange(await db.Set<ComboGroupItem>().Where(x => oldGroupIds.Contains(x.ComboGroupId)).ToListAsync(ct)); db.RemoveRange(oldGroups); foreach (var group in request.Groups) { var groupEntity = new ComboGroup { Id = Guid.NewGuid(), ComboId = combo.Id, Name = group.Name, MinimumItems = group.MinimumSelections, MaximumItems = group.MaximumSelections, DisplayOrder = group.DisplayOrder, Required = group.MinimumSelections > 0 }; db.Add(groupEntity); foreach (var item in group.Items) { if (!await db.Set<Product>().AnyAsync(x => x.Id == item.ProductId && x.EstablishmentId == tenant, ct) || item.ProductVariantId is Guid variantId && !await (from variant in db.Set<ProductVariant>() join owner in db.Set<Product>() on variant.ProductId equals owner.Id where variant.Id == variantId && owner.EstablishmentId == tenant select variant.Id).AnyAsync(ct)) return Results.NotFound(); db.Add(new ComboGroupItem { Id = Guid.NewGuid(), ComboGroupId = groupEntity.Id, ProductId = item.ProductVariantId is null ? item.ProductId : null, ProductVariantId = item.ProductVariantId, AdditionalPrice = item.AdditionalPrice }); } }
        await db.SaveChangesAsync(ct); return Results.NoContent();
    }

    private static async Task<IResult> ValidateCatalog(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var errors = await ValidationErrors(db, Tenant(principal), ct); return Results.Ok(new { valid = errors.Count == 0, errors }); }

    private static async Task<IResult> PublishCatalog(HttpRequest request, ClaimsPrincipal principal, AppizzaDbContext db, IHubContext<Phase1Hub> hub, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.publish", ct); if (denied is not null) return denied; if (!request.Headers.TryGetValue("Idempotency-Key", out var key) || string.IsNullOrWhiteSpace(key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key é obrigatório.");
        var tenant = Tenant(principal); await using var tx = await db.Database.BeginTransactionAsync(ct); await db.Database.ExecuteSqlInterpolatedAsync($"select pg_advisory_xact_lock(hashtextextended({tenant.ToString()}, 0))", ct);
        var existing = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == "catalog.publish" && x.IdempotencyKey == key.ToString(), ct); if (existing is not null) return Results.Content(existing.ResponsePayload ?? "{}", "application/json", Encoding.UTF8, existing.ResponseStatus ?? 200);
        var errors = await ValidationErrors(db, tenant, ct); var snapshot = await BuildSnapshot(db, tenant, ct); var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(snapshot))).ToLowerInvariant(); var now = DateTimeOffset.UtcNow; var state = await db.Set<CatalogState>().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct) ?? new CatalogState { EstablishmentId = tenant, CreatedAt = now, UpdatedAt = now };
        if (errors.Count > 0) { var rejected = new CatalogRevision { Id = Guid.NewGuid(), EstablishmentId = tenant, Status = "rejected", Snapshot = snapshot, SemanticHash = hash, ValidationErrors = JsonSerializer.Serialize(errors), CreatedAt = now, PublishedBy = UserId(principal) }; db.Add(rejected); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Error(422, "CATALOG_VALIDATION_FAILED", "O catálogo contém erros."); }
        var current = state.CurrentPublishedRevisionId is Guid currentId ? await db.Set<CatalogRevision>().SingleAsync(x => x.Id == currentId, ct) : null; if (current?.SemanticHash == hash) return Error(409, "CATALOG_NO_CHANGES_TO_PUBLISH", "Não há alterações semânticas para publicar.");
        if (db.Entry(state).State == EntityState.Detached) db.Add(state); if (current is not null) { current.Status = "superseded"; current.SupersededAt = now; }
        var revision = new CatalogRevision { Id = Guid.NewGuid(), EstablishmentId = tenant, CatalogVersion = state.CatalogVersion + 1, Status = "published", Snapshot = snapshot, SemanticHash = hash, CreatedAt = now, PublishedAt = now, PublishedBy = UserId(principal) }; state.CatalogVersion++; state.CurrentPublishedRevisionId = revision.Id; state.UpdatedAt = now; db.Add(revision); AddOutbox(db, tenant, "catalog-published.v1", new { catalogRevisionId = revision.Id, catalogVersion = state.CatalogVersion, semanticHash = hash }, UserId(principal)); var payload = JsonSerializer.Serialize(new { catalogRevisionId = revision.Id, catalogVersion = state.CatalogVersion, semanticHash = hash, publishedAt = now }); db.Add(new IdempotencyRecord { IdempotencyKey = key.ToString(), EstablishmentId = tenant, OperationType = "catalog.publish", RequestHash = hash, ResponseStatus = 200, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); await hub.Clients.Group($"establishment:{tenant}").SendAsync("CatalogPublished", new { catalogVersion = state.CatalogVersion }, ct); return Results.Content(payload, "application/json");
    }

    private static async Task<IResult> CurrentPublication(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var state = await db.Set<CatalogState>().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct); if (state?.CurrentPublishedRevisionId is not Guid id) return Results.NotFound(); var revision = await db.Set<CatalogRevision>().SingleAsync(x => x.Id == id, ct); return Results.Ok(new { revision.Id, revision.CatalogVersion, revision.PublishedAt, revision.SemanticHash, state.AvailabilityVersion }); }

    private static Task<IResult> SetIngredientAvailability(Guid ingredientId, AvailabilityRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) => ChangeAvailability("ingredient", ingredientId, request, http, principal, db, ct);
    private static Task<IResult> SetProductAvailability(Guid productId, AvailabilityRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) => ChangeAvailability("product", productId, request, http, principal, db, ct);
    private static Task<IResult> SetVariantAvailability(Guid variantId, AvailabilityRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) => ChangeAvailability("variant", variantId, request, http, principal, db, ct);

    private static async Task<IResult> ListAvailability(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "catalog.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var state = await db.Set<CatalogState>().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct); return Results.Ok(new { availabilityVersion = state?.AvailabilityVersion ?? 0, ingredients = await db.Set<IngredientAvailability>().Where(x => x.EstablishmentId == tenant).ToListAsync(ct), products = await db.Set<ProductAvailability>().Where(x => x.EstablishmentId == tenant).ToListAsync(ct), variants = await db.Set<ProductVariantAvailability>().Where(x => x.EstablishmentId == tenant).ToListAsync(ct) }); }

    private static async Task<IResult> ChangeAvailability(string kind, Guid id, AvailabilityRequest request, HttpRequest http, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "catalog.availability.manage", ct); if (denied is not null) return denied; if (!http.Headers.TryGetValue("Idempotency-Key", out var key) || string.IsNullOrWhiteSpace(key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key é obrigatório."); var tenant = Tenant(principal); var exists = kind switch { "ingredient" => await db.Set<Ingredient>().AnyAsync(x => x.Id == id && x.EstablishmentId == tenant, ct), "product" => await db.Set<Product>().AnyAsync(x => x.Id == id && x.EstablishmentId == tenant, ct), _ => await (from variant in db.Set<ProductVariant>() join product in db.Set<Product>() on variant.ProductId equals product.Id where variant.Id == id && product.EstablishmentId == tenant select variant.Id).AnyAsync(ct) }; if (!exists) return Results.NotFound();
        await using var tx = await db.Database.BeginTransactionAsync(ct); await db.Database.ExecuteSqlInterpolatedAsync($"select pg_advisory_xact_lock(hashtextextended({tenant.ToString()}, 1))", ct); var operation = $"catalog.availability.{kind}"; var requestHash = AvailabilityHash(kind, id, request); var previous = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == operation && x.IdempotencyKey == key.ToString(), ct); if (previous is not null) return previous.RequestHash == requestHash ? Results.Content(previous.ResponsePayload ?? "{}", "application/json", Encoding.UTF8, previous.ResponseStatus ?? 200) : Error(409, "IDEMPOTENCY_KEY_REUSED", "Idempotency-Key já utilizado com outro conteúdo."); var now = DateTimeOffset.UtcNow; var changed = false;
        if (kind == "ingredient") { var row = await db.Set<IngredientAvailability>().SingleOrDefaultAsync(x => x.IngredientId == id, ct); if (row is null) { row = new IngredientAvailability { IngredientId = id, EstablishmentId = tenant, UpdatedAt = now }; db.Add(row); } changed = row.ExplicitlyAvailable != request.Available; row.ExplicitlyAvailable = request.Available; row.EffectivelyAvailable = request.Available; row.Reason = request.Reason; row.UpdatedAt = now; row.UpdatedBy = UserId(principal); if (changed) { await db.SaveChangesAsync(ct); await RecalculateProducts(db, tenant, now, ct); } }
        else if (kind == "product") { var row = await db.Set<ProductAvailability>().SingleOrDefaultAsync(x => x.ProductId == id, ct); if (row is null) { row = new ProductAvailability { ProductId = id, EstablishmentId = tenant, UpdatedAt = now }; db.Add(row); } changed = row.ExplicitlyAvailable != request.Available; row.ExplicitlyAvailable = request.Available; row.EffectivelyAvailable = request.Available && !await HasUnavailableRequiredIngredient(db, id, ct); row.DerivedReason = row.EffectivelyAvailable ? null : request.Reason ?? "explicit_or_required_ingredient_unavailable"; row.UpdatedAt = now; row.UpdatedBy = UserId(principal); if (changed) await RecalculateVariants(db, tenant, id, row.EffectivelyAvailable, now, ct); }
        else { var row = await db.Set<ProductVariantAvailability>().SingleOrDefaultAsync(x => x.ProductVariantId == id, ct); if (row is null) { row = new ProductVariantAvailability { ProductVariantId = id, EstablishmentId = tenant, UpdatedAt = now }; db.Add(row); } changed = row.ExplicitlyAvailable != request.Available; var productAvailable = await (from variant in db.Set<ProductVariant>() join availability in db.Set<ProductAvailability>() on variant.ProductId equals availability.ProductId into availabilityRows from availability in availabilityRows.DefaultIfEmpty() where variant.Id == id select availability == null || availability.EffectivelyAvailable).SingleAsync(ct); row.ExplicitlyAvailable = request.Available; row.EffectivelyAvailable = request.Available && productAvailable; row.DerivedReason = row.EffectivelyAvailable ? null : request.Reason ?? "explicit_or_product_unavailable"; row.UpdatedAt = now; row.UpdatedBy = UserId(principal); }
        if (!changed) { var noChangePayload = JsonSerializer.Serialize(new { changed = false }); db.Add(new IdempotencyRecord { IdempotencyKey = key.ToString(), EstablishmentId = tenant, OperationType = operation, RequestHash = AvailabilityHash(kind, id, request), ResponseStatus = 200, ResponsePayload = noChangePayload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(noChangePayload, "application/json"); } var state = await db.Set<CatalogState>().SingleOrDefaultAsync(x => x.EstablishmentId == tenant, ct) ?? new CatalogState { EstablishmentId = tenant, CreatedAt = now, UpdatedAt = now }; if (db.Entry(state).State == EntityState.Detached) db.Add(state); state.AvailabilityVersion++; state.UpdatedAt = now; var effective = kind switch { "ingredient" => db.Set<IngredientAvailability>().Local.Single(x => x.IngredientId == id).EffectivelyAvailable, "product" => db.Set<ProductAvailability>().Local.Single(x => x.ProductId == id).EffectivelyAvailable, _ => db.Set<ProductVariantAvailability>().Local.Single(x => x.ProductVariantId == id).EffectivelyAvailable }; var eventType = kind switch { "ingredient" => "ingredient-availability-changed.v1", "product" => "product-availability-changed.v1", _ => "product-variant-availability-changed.v1" }; AddOutbox(db, tenant, eventType, new { resourceId = id, explicitlyAvailable = request.Available, effectivelyAvailable = effective, reasonCode = request.Reason, availabilityVersion = state.AvailabilityVersion }, UserId(principal)); var payload = JsonSerializer.Serialize(new { changed = true, explicitAvailable = request.Available, effectiveAvailable = effective, availabilityVersion = state.AvailabilityVersion }); db.Add(new IdempotencyRecord { IdempotencyKey = key.ToString(), EstablishmentId = tenant, OperationType = operation, RequestHash = AvailabilityHash(kind, id, request), ResponseStatus = 200, ResponsePayload = payload, CreatedAt = now }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Content(payload, "application/json");
    }

    private static async Task<IResult> CreateMediaAsset(MediaAssetRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "media.write", ct); if (denied is not null) return denied; if (!AllowedMediaTypes.Contains(request.MimeType) || request.FileSize is <= 0 or > MaximumMediaBytes || request.ChecksumSha256.Length != 64 || !request.ChecksumSha256.All(Uri.IsHexDigit)) return Error(400, "MEDIA_INVALID_METADATA", "Metadados de mídia inválidos.");
        var safeName = Path.GetFileName(request.FileName); if (safeName != request.FileName || safeName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0) return Error(400, "MEDIA_INVALID_FILE_NAME", "Nome de arquivo inválido."); var tenant = Tenant(principal); var now = DateTimeOffset.UtcNow; var asset = new MediaAsset { Id = Guid.NewGuid(), EstablishmentId = tenant, FileName = safeName, ObjectKey = $"{tenant:N}/{Guid.NewGuid():N}/{safeName}", MimeType = request.MimeType.ToLowerInvariant(), FileSize = request.FileSize, ChecksumSha256 = request.ChecksumSha256.ToLowerInvariant(), CreatedAt = now, UpdatedAt = now, CreatedBy = UserId(principal) }; db.Add(asset); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/operations/media/assets/{asset.Id}", new { asset.Id, asset.Status, asset.FileName, asset.MimeType, asset.FileSize });
    }

    private static async Task<IResult> UploadMediaAsset(Guid assetId, HttpRequest request, ClaimsPrincipal principal, AppizzaDbContext db, IObjectStorage storage, CancellationToken ct)
    {
        var denied = await Authorize(principal, db, "media.write", ct); if (denied is not null) return denied; if (!request.Headers.TryGetValue("Idempotency-Key", out var key) || string.IsNullOrWhiteSpace(key)) return Error(400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key é obrigatório."); var tenant = Tenant(principal); var operation = $"media.upload.{assetId:N}"; var previous = await db.IdempotencyRecords.SingleOrDefaultAsync(x => x.EstablishmentId == tenant && x.OperationType == operation && x.IdempotencyKey == key.ToString(), ct); if (previous is not null) return Results.Content(previous.ResponsePayload ?? "{}", "application/json", Encoding.UTF8, previous.ResponseStatus ?? 200); var asset = await db.Set<MediaAsset>().SingleOrDefaultAsync(x => x.Id == assetId && x.EstablishmentId == tenant, ct); if (asset is null) return Results.NotFound(); if (asset.Status != "pending_upload") return Error(409, "MEDIA_INVALID_STATE", "Asset não aguarda upload."); if (!string.Equals(request.ContentType, asset.MimeType, StringComparison.OrdinalIgnoreCase) || request.ContentLength != asset.FileSize) return Error(400, "MEDIA_CONTENT_MISMATCH", "Conteúdo não corresponde aos metadados.");
        await using var buffer = new MemoryStream(); await request.Body.CopyToAsync(buffer, ct); var checksum = Convert.ToHexString(SHA256.HashData(buffer.ToArray())).ToLowerInvariant(); if (checksum != asset.ChecksumSha256) { asset.Status = "failed"; asset.FailureReason = "checksum_mismatch"; asset.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); return Error(422, "MEDIA_CHECKSUM_MISMATCH", "Checksum inválido."); } buffer.Position = 0; try { await storage.PutAsync(asset.ObjectKey, buffer, asset.MimeType, ct); } catch { asset.Status = "failed"; asset.FailureReason = "storage_failure"; asset.UpdatedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); throw; } asset.Status = "ready"; asset.ReadyAt = DateTimeOffset.UtcNow; asset.UpdatedAt = asset.ReadyAt.Value; var payload = JsonSerializer.Serialize(new { asset.Id, asset.Status }); db.Add(new IdempotencyRecord { IdempotencyKey = key.ToString(), EstablishmentId = tenant, OperationType = operation, RequestHash = checksum, ResponseStatus = 200, ResponsePayload = payload, CreatedAt = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(ct); return Results.Content(payload, "application/json");
    }

    private static async Task<IResult> GetMediaAsset(Guid assetId, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "media.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var asset = await db.Set<MediaAsset>().SingleOrDefaultAsync(x => x.Id == assetId && x.EstablishmentId == tenant, ct); return asset is null ? Results.NotFound() : Results.Ok(new { asset.Id, asset.FileName, asset.MimeType, asset.FileSize, asset.ChecksumSha256, asset.Status, asset.CreatedAt, asset.ReadyAt }); }

    private static async Task<IResult> DownloadMediaAsset(Guid assetId, ClaimsPrincipal principal, AppizzaDbContext db, IObjectStorage storage, CancellationToken ct)
    { var denied = await Authorize(principal, db, "media.read", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var asset = await db.Set<MediaAsset>().SingleOrDefaultAsync(x => x.Id == assetId && x.EstablishmentId == tenant && x.Status == "ready", ct); if (asset is null) return Results.NotFound(); await using var stored = await storage.GetAsync(asset.ObjectKey, ct); var bytes = new byte[stored.ContentLength]; await stored.Content.ReadExactlyAsync(bytes, ct); return Results.File(bytes, stored.ContentType, asset.FileName); }

    private static async Task<IResult> ArchiveMediaAsset(Guid assetId, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var denied = await Authorize(principal, db, "media.write", ct); if (denied is not null) return denied; var tenant = Tenant(principal); var asset = await db.Set<MediaAsset>().SingleOrDefaultAsync(x => x.Id == assetId && x.EstablishmentId == tenant, ct); if (asset is null) return Results.NotFound(); if (asset.Status != "ready") return Error(409, "MEDIA_INVALID_STATE", "Somente asset pronto pode ser arquivado."); asset.Status = "archived"; asset.ArchivedAt = DateTimeOffset.UtcNow; asset.UpdatedAt = asset.ArchivedAt.Value; await db.SaveChangesAsync(ct); return Results.NoContent(); }

    private static async Task<List<string>> ValidationErrors(AppizzaDbContext db, Guid tenant, CancellationToken ct)
    {
        var errors = new List<string>(); var products = await db.Set<Product>().Where(x => x.EstablishmentId == tenant && x.Status == "active").ToListAsync(ct);
        foreach (var product in products) { if (product.ProductType == "configurable" && !await db.Set<ProductVariant>().AnyAsync(x => x.ProductId == product.Id && x.Status == "active", ct)) errors.Add($"PRODUCT_VARIANT_REQUIRED:{product.Id}"); if (product.ProductType is "pizza" or "custom_pizza" && !await db.Set<PizzaProductSize>().AnyAsync(x => x.ProductId == product.Id, ct)) errors.Add($"PIZZA_SIZE_REQUIRED:{product.Id}"); if (product.ProductType == "pizza" && !await db.Set<PizzaFlavor>().AnyAsync(x => x.ProductId == product.Id && x.Status == "active", ct)) errors.Add($"PIZZA_FLAVOR_REQUIRED:{product.Id}"); if (product.ProductType == "custom_pizza" && !await db.Set<CustomPizzaBasePrice>().AnyAsync(x => x.CustomPizzaProductId == product.Id, ct)) errors.Add($"CUSTOM_PIZZA_BASE_PRICE_REQUIRED:{product.Id}"); if (product.ProductType == "combo") { var groups = await (from c in db.Set<Combo>() join g in db.Set<ComboGroup>() on c.Id equals g.ComboId where c.ProductId == product.Id select g).ToListAsync(ct); if (groups.Count == 0 || groups.Any(g => g.MaximumItems < g.MinimumItems) || await db.Set<ComboGroupItem>().CountAsync(i => groups.Select(g => g.Id).Contains(i.ComboGroupId), ct) < groups.Count) errors.Add($"COMBO_INVALID:{product.Id}"); } }
        return errors;
    }

    private static async Task<string> BuildSnapshot(AppizzaDbContext db, Guid tenant, CancellationToken ct)
    {
        var categoryRows = await db.Set<Category>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        var productRows = await db.Set<Product>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var productIds = productRows.Select(x => x.Id).ToArray();
        var variantRows = await db.Set<ProductVariant>().Where(x => productIds.Contains(x.ProductId) && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        var ingredientRows = await db.Set<Ingredient>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        var productIngredientRows = await db.Set<ProductIngredient>().Where(x => productIds.Contains(x.ProductId)).OrderBy(x => x.Id).ToListAsync(ct);
        var customizationGroups = await db.Set<CustomizationGroup>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var customizationGroupIds = customizationGroups.Select(x => x.Id).ToArray(); var customizationOptions = await db.Set<CustomizationOption>().Where(x => customizationGroupIds.Contains(x.CustomizationGroupId) && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var productCustomizationGroups = await db.Set<ProductCustomizationGroup>().Where(x => productIds.Contains(x.ProductId) && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        var sizeRows = await db.Set<PizzaSize>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        var pizzaProducts = await db.Set<PizzaProductSize>().Where(x => productIds.Contains(x.ProductId)).OrderBy(x => x.ProductId).ThenBy(x => x.PizzaSizeId).ToListAsync(ct);
        var flavorRows = await db.Set<PizzaFlavor>().Where(x => productIds.Contains(x.ProductId) && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var flavorIds = flavorRows.Select(x => x.Id).ToArray();
        var flavorPrices = await db.Set<PizzaFlavorPrice>().Where(x => flavorIds.Contains(x.PizzaFlavorId)).OrderBy(x => x.PizzaFlavorId).ThenBy(x => x.PizzaSizeId).ToListAsync(ct);
        var customBasePrices = await db.Set<CustomPizzaBasePrice>().Where(x => productIds.Contains(x.CustomPizzaProductId)).OrderBy(x => x.CustomPizzaProductId).ThenBy(x => x.PizzaSizeId).ToListAsync(ct);
        var doughs = await db.Set<Dough>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var doughIds = doughs.Select(x => x.Id).ToArray(); var doughPrices = await db.Set<DoughSizePrice>().Where(x => doughIds.Contains(x.DoughId)).OrderBy(x => x.DoughId).ThenBy(x => x.PizzaSizeId).ToListAsync(ct); var pizzaDoughs = await db.Set<PizzaDough>().Where(x => productIds.Contains(x.ProductId)).OrderBy(x => x.ProductId).ThenBy(x => x.DoughId).ToListAsync(ct);
        var crusts = await db.Set<Crust>().Where(x => x.EstablishmentId == tenant && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct); var crustIds = crusts.Select(x => x.Id).ToArray(); var crustPrices = await db.Set<CrustSizePrice>().Where(x => crustIds.Contains(x.CrustId)).OrderBy(x => x.CrustId).ThenBy(x => x.PizzaSizeId).ToListAsync(ct); var pizzaCrusts = await db.Set<PizzaCrust>().Where(x => productIds.Contains(x.ProductId)).OrderBy(x => x.ProductId).ThenBy(x => x.CrustId).ToListAsync(ct);
        var comboRows = await db.Set<Combo>().Where(x => productIds.Contains(x.ProductId)).OrderBy(x => x.ProductId).ToListAsync(ct); var comboIds = comboRows.Select(x => x.Id).ToArray();
        var comboGroups = await db.Set<ComboGroup>().Where(x => comboIds.Contains(x.ComboId)).OrderBy(x => x.ComboId).ThenBy(x => x.DisplayOrder).ToListAsync(ct); var groupIds = comboGroups.Select(x => x.Id).ToArray();
        var comboItems = await db.Set<ComboGroupItem>().Where(x => groupIds.Contains(x.ComboGroupId) && x.Status == "active").OrderBy(x => x.Id).ToListAsync(ct);
        return JsonSerializer.Serialize(new
        {
            schemaVersion = 1,
            categories = categoryRows.Select(x => new { x.Id, x.ParentCategoryId, x.Name, x.Description, x.ImageMediaId, x.DisplayOrder }),
            products = productRows.Select(x => new { x.Id, x.ProductType, x.Name, x.ShortName, x.Description, x.InternalCode, x.PrimaryCategoryId, x.PrimaryImageMediaId, x.DisplayOrder, x.RequiresProduction, x.RequiresOperationalAcceptance, x.AllowsNotes, x.MaximumNoteLength, x.PreparationStationId, x.EstimatedPreparationMinutes }),
            variants = variantRows.Select(x => new { x.Id, x.ProductId, x.Name, x.ShortName, x.InternalCode, x.Barcode, x.BasePrice, x.ImageMediaId, x.DisplayOrder }),
            ingredients = ingredientRows.Select(x => new { x.Id, x.Name, x.KitchenName, x.Description, x.DefaultAdditionalPrice, x.UnitOfMeasure, x.ImageMediaId }),
            productIngredients = productIngredientRows.Select(x => new { x.Id, x.ProductId, x.IngredientId, x.IncludedByDefault, x.RequiredForRecipe, x.CanBeRemoved, x.CanBeAdded, x.DefaultQuantity, x.MaximumAdditionalQuantity, x.AdditionalPrice, x.ApplicationScope, x.DisplayOrder }),
            customization = new { groups = customizationGroups.Select(x => new { x.Id, x.Name, x.Description, x.SelectionType, x.MinimumSelections, x.MaximumSelections, x.DisplayType, x.Reusable }), options = customizationOptions.Select(x => new { x.Id, x.CustomizationGroupId, x.Name, x.Description, x.PriceRuleType, x.BaseAdditionalPrice, x.LinkedIngredientId, x.LinkedProductId, x.DisplayOrder }), products = productCustomizationGroups.Select(x => new { x.Id, x.ProductId, x.CustomizationGroupId, x.RequiredOverride, x.MinimumOverride, x.MaximumOverride, x.DisplayOrder }) },
            pizza = new { sizes = sizeRows.Select(x => new { x.Id, x.Name, x.SliceCount, x.DiameterCm, x.DisplayOrder }), products = pizzaProducts, flavors = flavorRows.Select(x => new { x.Id, x.ProductId }), flavorPrices = flavorPrices.Select(x => new { x.Id, x.PizzaFlavorId, x.PizzaSizeId, x.Price }), customBasePrices, doughs = doughs.Select(x => new { x.Id, x.Name, x.Description, x.IsDefault }), doughPrices, pizzaDoughs, crusts = crusts.Select(x => new { x.Id, x.Name, x.Description, x.ImageMediaId }), crustPrices, pizzaCrusts },
            combos = new { definitions = comboRows.Select(x => new { x.Id, x.ProductId, x.PricingStrategy, x.FixedPrice, x.DiscountType, x.DiscountValue }), groups = comboGroups.Select(x => new { x.Id, x.ComboId, x.Name, x.Description, x.MinimumItems, x.MaximumItems, x.AllowRepetition, x.Required, x.DisplayOrder }), items = comboItems.Select(x => new { x.Id, x.ComboGroupId, x.ProductId, x.ProductVariantId, x.CategoryId, x.InclusionType, x.AdditionalPrice, x.FixedQuantity }) }
        });
    }

    private static async Task RecalculateProducts(AppizzaDbContext db, Guid tenant, DateTimeOffset now, CancellationToken ct)
    { var products = await db.Set<Product>().Where(x => x.EstablishmentId == tenant).ToListAsync(ct); foreach (var product in products) { var row = await db.Set<ProductAvailability>().SingleOrDefaultAsync(x => x.ProductId == product.Id, ct); if (row is null) { row = new ProductAvailability { ProductId = product.Id, EstablishmentId = tenant, UpdatedAt = now }; db.Add(row); } var unavailable = await HasUnavailableRequiredIngredient(db, product.Id, ct); row.EffectivelyAvailable = row.ExplicitlyAvailable && !unavailable; row.DerivedReason = unavailable ? "required_ingredient_unavailable" : null; row.UpdatedAt = now; await RecalculateVariants(db, tenant, product.Id, row.EffectivelyAvailable, now, ct); } }
    private static async Task RecalculateVariants(AppizzaDbContext db, Guid tenant, Guid productId, bool productAvailable, DateTimeOffset now, CancellationToken ct)
    { foreach (var variant in await db.Set<ProductVariant>().Where(x => x.ProductId == productId).ToListAsync(ct)) { var row = await db.Set<ProductVariantAvailability>().SingleOrDefaultAsync(x => x.ProductVariantId == variant.Id, ct); if (row is null) { row = new ProductVariantAvailability { ProductVariantId = variant.Id, EstablishmentId = tenant, UpdatedAt = now }; db.Add(row); } row.EffectivelyAvailable = row.ExplicitlyAvailable && productAvailable; row.DerivedReason = row.EffectivelyAvailable ? null : "product_unavailable"; row.UpdatedAt = now; } }
    private static Task<bool> HasUnavailableRequiredIngredient(AppizzaDbContext db, Guid productId, CancellationToken ct) => (from link in db.Set<ProductIngredient>() join availability in db.Set<IngredientAvailability>() on link.IngredientId equals availability.IngredientId where link.ProductId == productId && link.RequiredForRecipe && !availability.EffectivelyAvailable select link.Id).AnyAsync(ct);
    private static async Task<bool> OwnsReadyMedia(AppizzaDbContext db, Guid tenant, Guid? assetId, CancellationToken ct) => assetId is null || await db.Set<MediaAsset>().AnyAsync(x => x.Id == assetId && x.EstablishmentId == tenant && x.Status == "ready", ct);
    private static Guid Tenant(ClaimsPrincipal principal) => Guid.Parse(principal.FindFirstValue("establishment_id")!);
    private static Guid UserId(ClaimsPrincipal principal) => Guid.Parse(principal.FindFirstValue("sub")!);
    private static string AvailabilityHash(string kind, Guid id, AvailabilityRequest request) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{kind}|{id:N}|{request.Available}|{request.Reason}"))).ToLowerInvariant();
    private static async Task<IResult?> Authorize(ClaimsPrincipal principal, AppizzaDbContext db, string permission, CancellationToken ct) { if (!principal.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var permissions = await PermissionResolver.ResolveAsync(db, UserId(principal), DateTimeOffset.UtcNow, ct); return permissions.Contains(permission) ? null : Error(403, "INSUFFICIENT_PERMISSION", "Permissão insuficiente."); }
    private static void AddOutbox(AppizzaDbContext db, Guid tenant, string eventType, object data, Guid userId) => db.Add(new OutboxMessage { Id = Guid.NewGuid(), EstablishmentId = tenant, EventType = eventType, SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId = Guid.NewGuid(), eventType, schemaVersion = 1, occurredAtUtc = DateTimeOffset.UtcNow, establishmentId = tenant, actor = new { userId }, data }), OccurredAt = DateTimeOffset.UtcNow });
    private static IResult Error(int status, string code, string detail) => Results.Problem(statusCode: status, title: detail, detail: detail, extensions: new Dictionary<string, object?> { ["errorCode"] = code });
}

public sealed record CategoryRequest(string Name, string? Description, Guid? ParentCategoryId, Guid? ImageMediaId, int DisplayOrder);
public sealed record CategoryUpdateRequest(string Name, string? Description, Guid? ParentCategoryId, Guid? ImageMediaId, int DisplayOrder, long Version);
public sealed record ProductRequest(string ProductType, string Name, string? Description, string? InternalCode, Guid? PrimaryCategoryId, Guid? PrimaryImageMediaId, int DisplayOrder, bool RequiresProduction, bool AllowsNotes, int? MaximumNoteLength, Guid? PreparationStationId);
public sealed record ProductUpdateRequest(string Name, string? Description, string? InternalCode, Guid? PrimaryCategoryId, Guid? PrimaryImageMediaId, int DisplayOrder, bool RequiresProduction, bool AllowsNotes, int? MaximumNoteLength, Guid? PreparationStationId, long Version);
public sealed record VariantRequest(string Name, string? InternalCode, decimal BasePrice, Guid? ImageMediaId, int DisplayOrder);
public sealed record CustomizationOptionRequest(string Name, string? Description, decimal AdditionalPrice, Guid? LinkedIngredientId, Guid? LinkedProductId, int DisplayOrder);
public sealed record CustomizationGroupRequest(string Name, string? Description, string SelectionType, int MinimumSelections, int? MaximumSelections, string DisplayType, bool Reusable, IReadOnlyList<CustomizationOptionRequest>? Options);
public sealed record PizzaSizeRequest(string Name, string? ShortName, int? SliceCount, decimal? DiameterCm, int DisplayOrder);
public sealed record DoughRequest(string Name, string? Description, bool IsDefault);
public sealed record CrustRequest(string Name, string? Description, Guid? ImageMediaId);
public sealed record IngredientRequest(string Name, string? KitchenName, string? Description, decimal DefaultAdditionalPrice, string? UnitOfMeasure, Guid? ImageMediaId);
public sealed record IngredientUpdateRequest(string Name, string? KitchenName, string? Description, decimal DefaultAdditionalPrice, string? UnitOfMeasure, Guid? ImageMediaId, long Version);
public sealed record ProductIngredientItem(Guid IngredientId, bool IncludedByDefault, bool RequiredForRecipe, bool CanBeRemoved, bool CanBeAdded, decimal? MaximumAdditionalQuantity, decimal AdditionalPrice, string ApplicationScope);
public sealed record ProductIngredientsRequest(IReadOnlyList<ProductIngredientItem> Items);
public sealed record IdListRequest(IReadOnlyList<Guid> Ids);
public sealed record PizzaSizeConfiguration(Guid PizzaSizeId, int MaximumFlavors, int DisplayOrder, decimal? CustomBasePrice, decimal? FlavorPrice);
public sealed record PizzaConfigurationRequest(IReadOnlyList<PizzaSizeConfiguration> Sizes, IReadOnlyList<Guid>? DoughIds, IReadOnlyList<Guid>? CrustIds);
public sealed record ComboItemRequest(Guid ProductId, Guid? ProductVariantId, decimal AdditionalPrice, int DisplayOrder);
public sealed record ComboGroupRequest(string Name, int MinimumSelections, int MaximumSelections, int DisplayOrder, IReadOnlyList<ComboItemRequest> Items);
public sealed record ComboConfigurationRequest(string PricingMode, decimal? FixedPrice, IReadOnlyList<ComboGroupRequest> Groups);
public sealed record AvailabilityRequest(bool Available, string? ReasonCode)
{
    internal string? Reason => ReasonCode;
}
public sealed record MediaAssetRequest(string FileName, string MimeType, long FileSize, string ChecksumSha256);
