using System.Security.Claims;
using System.Text.Json;
using Appizza.Modules.Devices;
using Appizza.Modules.Establishments;
using Appizza.Modules.Identity;
using Appizza.Modules.Tables;
using Appizza.Persistence;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Appizza.Api;

#pragma warning disable CS8602 // Device is non-null whenever ValidateDevice returns no error.
#pragma warning disable CA1305 // Persisted/token values use digit-only invariant representations.

public static class Phase1Endpoints
{
    public static IEndpointRouteBuilder MapPhase1Endpoints(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/v1/auth/sign-in", SignIn).RequireRateLimiting("authentication");
        app.MapPost("/api/v1/auth/token/refresh", RefreshUser).RequireRateLimiting("authentication");
        app.MapPost("/api/v1/auth/sign-out", SignOut).RequireAuthorization();
        app.MapGet("/api/v1/auth/me", CurrentUser).RequireAuthorization();
        app.MapPost("/api/v1/table-devices/register", RegisterDevice).RequireRateLimiting("authentication");
        app.MapGet("/api/v1/table-devices/configuration/available-tables", AvailableTables).RequireAuthorization();
        app.MapPost("/api/v1/table-devices/{deviceId:guid}/bind", BindDevice).RequireAuthorization();
        app.MapGet("/api/v1/table-devices/me", CurrentDevice).RequireAuthorization();
        app.MapPost("/api/v1/table-devices/token/refresh", RefreshDevice).RequireRateLimiting("authentication");
        app.MapPost("/api/v1/table-devices/heartbeat", Heartbeat).RequireAuthorization();
        app.MapGet("/api/v1/table-device/session", CurrentSession).RequireAuthorization();
        app.MapPost("/api/v1/table-device/session/open-or-get", OpenOrGetSession).RequireAuthorization();
        app.MapPost("/api/v1/table-device/session/customer-identification", ProvideIdentification).RequireAuthorization();
        app.MapPost("/api/v1/table-device/session/customer-identification/skip", SkipIdentification).RequireAuthorization();
        app.MapGet("/api/v1/table-device/session/snapshot", SessionSnapshot).RequireAuthorization();
        app.MapPost("/api/v1/operations/table-devices/{deviceId:guid}/unbind", UnbindDevice).RequireAuthorization();
        app.MapPost("/api/v1/operations/table-devices/{deviceId:guid}/revoke-configuration", RevokeDevice).RequireAuthorization();
        app.MapPost("/api/v1/operations/table-devices/{deviceId:guid}/block", BlockDevice).RequireAuthorization();
        app.MapPost("/api/v1/operations/table-devices/{deviceId:guid}/unblock", UnblockDevice).RequireAuthorization();
        app.MapPost("/api/v1/operations/tables/{tableId:guid}/confirm-cleaning", ConfirmCleaning).RequireAuthorization();
        return app;
    }

    private static async Task<IResult> SignIn(SignInRequest request, AppizzaDbContext db, IPasswordHasher<User> hasher, Phase1TokenService tokens, Phase1SecurityOptions options, HttpContext http, CancellationToken ct)
    {
        var code = request.EstablishmentCode.Trim().ToUpperInvariant(); var login = request.Login.Trim().ToLowerInvariant();
        var user = await (from u in db.Set<User>() join e in db.Set<Establishment>() on u.EstablishmentId equals e.Id where e.PublicCode == code && u.Login == login select u).SingleOrDefaultAsync(ct);
        if (user is null || user.Status != "active" || hasher.VerifyHashedPassword(user, user.PasswordHash, request.Password) == PasswordVerificationResult.Failed) return Error(401, "INVALID_CREDENTIALS", "Credenciais inválidas.");
        var refresh = Phase1TokenService.NewRefreshToken(); var session = new UserSession { Id = Guid.NewGuid(), UserId = user.Id, RefreshTokenHash = Phase1TokenService.HashToken(refresh), StartedAt = DateTimeOffset.UtcNow, ExpiresAt = DateTimeOffset.UtcNow.AddDays(options.RefreshTokenDays), IpAddress = http.Connection.RemoteIpAddress?.ToString(), UserAgent = http.Request.Headers.UserAgent.ToString() };
        user.LastLoginAt = DateTimeOffset.UtcNow; var permissions = await PermissionResolver.ResolveAsync(db, user.Id, DateTimeOffset.UtcNow, ct); db.Add(session); await db.SaveChangesAsync(ct); var access = tokens.IssueUser(user, session.Id, permissions);
        return Results.Ok(new { accessToken = access.AccessToken, refreshToken = refresh, expiresInSeconds = access.ExpiresInSeconds, user = new { user.Id, user.Name } });
    }

    private static async Task<IResult> RefreshUser(RefreshRequest request, AppizzaDbContext db, Phase1TokenService tokens, Phase1SecurityOptions options, CancellationToken ct)
    {
        var hash = Phase1TokenService.HashToken(request.RefreshToken); await using var transaction = await db.Database.BeginTransactionAsync(ct);
        var old = await db.Set<UserSession>().FromSqlInterpolated($"select * from identity.user_session where refresh_token_hash = {hash} for update").SingleOrDefaultAsync(ct);
        if (old is null || old.RevokedAt is not null || old.ExpiresAt <= DateTimeOffset.UtcNow) return Error(401, "INVALID_REFRESH_TOKEN", "Refresh token inválido.");
        var user = await db.Set<User>().SingleAsync(x => x.Id == old.UserId, ct); if (user.Status != "active") return Error(403, "USER_INACTIVE", "Usuário indisponível.");
        var refresh = Phase1TokenService.NewRefreshToken(); var next = new UserSession { Id = Guid.NewGuid(), UserId = user.Id, RefreshTokenHash = Phase1TokenService.HashToken(refresh), StartedAt = DateTimeOffset.UtcNow, ExpiresAt = DateTimeOffset.UtcNow.AddDays(options.RefreshTokenDays) };
        old.RevokedAt = DateTimeOffset.UtcNow; old.ReplacedBySessionId = next.Id; db.Add(next); var permissions = await PermissionResolver.ResolveAsync(db, user.Id, DateTimeOffset.UtcNow, ct); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); var access = tokens.IssueUser(user, next.Id, permissions); return Results.Ok(new { accessToken = access.AccessToken, refreshToken = refresh, expiresInSeconds = access.ExpiresInSeconds });
    }

    private static async Task<IResult> SignOut(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var sessionId = principal.RequiredGuid("session_id"); var session = await db.Set<UserSession>().SingleOrDefaultAsync(x => x.Id == sessionId, ct); if (session is not null && session.RevokedAt is null) { session.RevokedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); } return Results.NoContent(); }

    private static async Task<IResult> CurrentUser(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { if (!principal.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var userId = principal.RequiredGuid("sub"); var user = await db.Set<User>().SingleOrDefaultAsync(x => x.Id == userId, ct); if (user is null) return Results.NotFound(); var permissions = await PermissionResolver.ResolveAsync(db, user.Id, DateTimeOffset.UtcNow, ct); return Results.Ok(new { user.Id, user.Name, user.EstablishmentId, permissions = permissions.Order() }); }

    private static async Task<IResult> RegisterDevice(RegisterDeviceRequest request, AppizzaDbContext db, Phase1TokenService tokens, CancellationToken ct)
    { var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.InstallationId == request.InstallationId, ct); if (device is null) { var now = DateTimeOffset.UtcNow; device = new Device { Id = Guid.NewGuid(), InstallationId = request.InstallationId, Name = request.DeviceName, Platform = request.Platform, Model = request.Model, OperatingSystemVersion = request.OperatingSystemVersion, AppVersion = request.ApplicationVersion, RegisteredAt = now, CreatedAt = now, UpdatedAt = now }; db.Add(device); await db.SaveChangesAsync(ct); } if (device.Status == "blocked") return Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado."); return Results.Created($"/api/v1/table-devices/{device.Id}", new { deviceId = device.Id, status = "awaitingConfiguration", configurationToken = tokens.IssueConfiguration(device), expiresAt = DateTimeOffset.UtcNow.AddMinutes(30) }); }

    private static async Task<IResult> AvailableTables(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var auth = await RequirePermission(principal, db, "devices.table.configure", ct); if (auth is not null) return auth; var establishmentId = principal.RequiredGuid("establishment_id"); var maximum = await DeviceLimit(db, establishmentId, ct); var rows = await (from table in db.Set<DiningTable>() join sector in db.Set<Sector>() on table.SectorId equals sector.Id into sectors from sector in sectors.DefaultIfEmpty() where table.EstablishmentId == establishmentId && table.Status != "inactive" select new { table.Id, table.Name, SectorName = sector == null ? null : sector.Name, ActiveDeviceCount = db.Set<DeviceTableBinding>().Count(binding => binding.DiningTableId == table.Id && binding.UnboundAt == null) }).ToListAsync(ct); return Results.Ok(new { tables = rows.Select(x => new { x.Id, x.Name, x.SectorName, x.ActiveDeviceCount, maximumDeviceCount = maximum, canBindAnotherDevice = x.ActiveDeviceCount < maximum }) }); }

    private static async Task<IResult> BindDevice(Guid deviceId, BindDeviceRequest request, ClaimsPrincipal principal, AppizzaDbContext db, Phase1TokenService tokens, Phase1SecurityOptions options, CancellationToken ct)
    {
        var auth = await RequirePermission(principal, db, "devices.table.configure", ct); if (auth is not null) return auth; var establishmentId = principal.RequiredGuid("establishment_id"); var userId = principal.RequiredGuid("sub");
        ClaimsPrincipal config; try { config = tokens.ValidateConfiguration(request.ConfigurationToken); } catch { return Error(401, "CONFIGURATION_TOKEN_EXPIRED", "Token de configuração inválido ou expirado."); }
        if (config.RequiredGuid("sub") != deviceId) return Error(403, "DEVICE_NOT_REGISTERED", "Token não pertence ao dispositivo.");
        await using var transaction = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.ReadCommitted, ct); var table = await db.Set<DiningTable>().FromSqlInterpolated($"select * from tables.dining_table where id = {request.TableId} for update").SingleOrDefaultAsync(ct); if (table is null || table.EstablishmentId != establishmentId) return Results.NotFound(); if (table.Status is "inactive" or "blocked") return Error(409, "TABLE_NOT_AVAILABLE", "Mesa indisponível.");
        var device = await db.Set<Device>().FromSqlInterpolated($"select * from devices.device where id = {deviceId} for update").SingleOrDefaultAsync(ct); if (device is null) return Results.NotFound(); if (device.Status == "blocked") return Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado."); if (device.EstablishmentId is not null && device.EstablishmentId != establishmentId) return Results.NotFound();
        if (await db.Set<DeviceTableBinding>().AnyAsync(x => x.DeviceId == device.Id && x.UnboundAt == null, ct)) return Error(409, "DEVICE_ALREADY_BOUND", "Dispositivo já vinculado.");
        Device? replacedDevice = null;
        if (request.ReplaceDeviceId is Guid replacedDeviceId)
        {
            replacedDevice = await db.Set<Device>().FromSqlInterpolated($"select * from devices.device where id = {replacedDeviceId} for update").SingleOrDefaultAsync(ct);
            if (replacedDevice is null || replacedDevice.EstablishmentId != establishmentId) return Results.NotFound();
            var replacedBinding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == replacedDeviceId && x.DiningTableId == table.Id && x.UnboundAt == null, ct);
            if (replacedBinding is null) return Error(409, "DEVICE_ALREADY_BOUND", "Dispositivo indicado para substituição não possui vínculo ativo nesta mesa.");
            var replacedAt = DateTimeOffset.UtcNow; replacedBinding.UnboundAt = replacedAt; replacedBinding.UnboundByUserId = userId; replacedBinding.UnbindReason = request.Reason ?? "replacement"; replacedDevice.Status = "revoked"; replacedDevice.CredentialVersion++; replacedDevice.UpdatedAt = replacedAt;
            foreach (var replacedSession in await db.Set<DeviceSession>().Where(x => x.DeviceId == replacedDeviceId && x.RevokedAt == null).ToListAsync(ct)) replacedSession.RevokedAt = replacedAt;
        }
        var maximum = await DeviceLimit(db, establishmentId, ct); var activeCount = await db.Set<DeviceTableBinding>().CountAsync(x => x.DiningTableId == table.Id && x.UnboundAt == null, ct) - (replacedDevice is null ? 0 : 1); if (activeCount >= maximum) return Error(409, "TABLE_DEVICE_LIMIT_REACHED", "Limite de dispositivos atingido.");
        var now = DateTimeOffset.UtcNow; device.EstablishmentId = establishmentId; device.Status = "active"; device.UpdatedAt = now; var binding = new DeviceTableBinding { Id = Guid.NewGuid(), DeviceId = device.Id, DiningTableId = table.Id, BoundAt = now, BoundByUserId = userId, CreatedAt = now }; var refresh = Phase1TokenService.NewRefreshToken(); var session = new DeviceSession { Id = Guid.NewGuid(), DeviceId = device.Id, RefreshTokenHash = Phase1TokenService.HashToken(refresh), CredentialVersion = device.CredentialVersion, StartedAt = now, ExpiresAt = now.AddDays(options.RefreshTokenDays) }; db.AddRange(binding, session); AddOutbox(db, establishmentId, replacedDevice is null ? "device-bound-to-table.v1" : "device-replaced.v1", new { deviceId, tableId = table.Id, bindingId = binding.Id, replacedDeviceId = replacedDevice?.Id }, userId, deviceId);
        try { await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); }
        catch (DbUpdateException exception) when (IsUniqueViolation(exception)) { await transaction.RollbackAsync(ct); return Error(409, "DEVICE_ALREADY_BOUND", "Dispositivo já vinculado."); }
        var access = tokens.IssueDevice(device, session.Id); return Results.Ok(new { deviceId, bindingId = binding.Id, table = new { table.Id, table.Name }, deviceAccessToken = access.AccessToken, refreshToken = refresh, accessTokenExpiresInSeconds = access.ExpiresInSeconds });
    }

    private static async Task<IResult> RefreshDevice(RefreshRequest request, AppizzaDbContext db, Phase1TokenService tokens, Phase1SecurityOptions options, CancellationToken ct)
    { var hash = Phase1TokenService.HashToken(request.RefreshToken); await using var tx = await db.Database.BeginTransactionAsync(ct); var old = await db.Set<DeviceSession>().FromSqlInterpolated($"select * from devices.device_session where refresh_token_hash = {hash} for update").SingleOrDefaultAsync(ct); if (old is null || old.RevokedAt is not null || old.ExpiresAt <= DateTimeOffset.UtcNow) return Error(401, "INVALID_REFRESH_TOKEN", "Refresh token inválido."); var device = await db.Set<Device>().SingleAsync(x => x.Id == old.DeviceId, ct); if (device.Status != "active" || old.CredentialVersion != device.CredentialVersion) return Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada."); var refresh = Phase1TokenService.NewRefreshToken(); var next = new DeviceSession { Id = Guid.NewGuid(), DeviceId = device.Id, RefreshTokenHash = Phase1TokenService.HashToken(refresh), CredentialVersion = device.CredentialVersion, StartedAt = DateTimeOffset.UtcNow, ExpiresAt = DateTimeOffset.UtcNow.AddDays(options.RefreshTokenDays) }; old.RevokedAt = DateTimeOffset.UtcNow; old.ReplacedBySessionId = next.Id; db.Add(next); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); var access = tokens.IssueDevice(device, next.Id); return Results.Ok(new { accessToken = access.AccessToken, refreshToken = refresh, expiresInSeconds = access.ExpiresInSeconds }); }

    private static async Task<IResult> CurrentDevice(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; var binding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == validation.Device!.Id && x.UnboundAt == null, ct); var session = binding is null ? null : await db.Set<TableSession>().SingleOrDefaultAsync(x => x.DiningTableId == binding.DiningTableId && ActiveSessionStatuses.Contains(x.Status), ct); return Results.Ok(new { device = new { validation.Device.Id, validation.Device.Status, validation.Device.EstablishmentId, validation.Device.Version }, binding, session = session is null ? null : new { session.Id, session.SessionNumber, session.Status, session.Version } }); }

    private static async Task<IResult> Heartbeat(HeartbeatRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; var now = DateTimeOffset.UtcNow; validation.Device!.LastSeenAt = now; var heartbeat = await db.Set<DeviceHeartbeat>().FindAsync([validation.Device.Id], ct); if (heartbeat is null) { heartbeat = new DeviceHeartbeat { DeviceId = validation.Device.Id }; db.Add(heartbeat); } heartbeat.ReceivedAt = now; heartbeat.BatteryPercentage = request.BatteryPercentage; heartbeat.NetworkStatus = request.NetworkStatus; heartbeat.KioskModeActive = request.KioskModeActive; heartbeat.LastCatalogSyncAt = request.LastCatalogSyncAt; await db.SaveChangesAsync(ct); return Results.NoContent(); }

    private static async Task<IResult> CurrentSession(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) => await SessionResult(principal, db, false, ct);
    private static async Task<IResult> SessionSnapshot(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct) => await SessionResult(principal, db, true, ct);

    private static async Task<IResult> OpenOrGetSession(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; var binding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == validation.Device!.Id && x.UnboundAt == null, ct); if (binding is null) return Error(409, "DEVICE_NOT_BOUND", "Dispositivo sem vínculo ativo."); await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.ReadCommitted, ct); var table = await db.Set<DiningTable>().FromSqlInterpolated($"select * from tables.dining_table where id = {binding.DiningTableId} for update").SingleAsync(ct); if (table.Status is "blocked" or "inactive" or "awaiting_cleaning") return Error(409, "TABLE_BLOCKED", "Mesa indisponível."); var session = await db.Set<TableSession>().SingleOrDefaultAsync(x => x.DiningTableId == table.Id && ActiveSessionStatuses.Contains(x.Status), ct); var created = false; if (session is null) { var sequence = await db.Database.SqlQuery<long>($"select nextval('tables.table_session_number_seq') as \"Value\"").SingleAsync(ct); var localDate = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, ResolveTimeZone(await db.Set<Establishment>().Where(x => x.Id == table.EstablishmentId).Select(x => x.Timezone).SingleAsync(ct))).ToString("yyyyMMdd"); var now = DateTimeOffset.UtcNow; session = new TableSession { Id = Guid.NewGuid(), EstablishmentId = table.EstablishmentId, DiningTableId = table.Id, SessionNumber = $"{localDate}-{sequence:D6}", OpenedAt = now, OpenedByDeviceId = validation.Device.Id, CreatedAt = now, UpdatedAt = now }; table.Status = "occupied"; table.UpdatedAt = now; db.Add(session); db.Add(new TableSessionStatusHistory { Id = Guid.NewGuid(), TableSessionId = session.Id, NewStatus = "open", ChangedByDeviceId = validation.Device.Id, ChangedAt = now }); AddOutbox(db, table.EstablishmentId, "table-session-opened.v1", new { tableSessionId = session.Id, diningTableId = table.Id, sessionNumber = session.SessionNumber, openingMode = "on_start_ordering", openedByDeviceId = validation.Device.Id }, null, validation.Device.Id); await db.SaveChangesAsync(ct); created = true; } await tx.CommitAsync(ct); return Results.Ok(new { session = new { session.Id, number = session.SessionNumber, session.Status, session.OpenedAt, createdNow = created, session.Version }, nextStep = session.CustomerIdentificationStatus == "pending" ? "customerIdentification" : "session" }); }

    private static async Task<IResult> ProvideIdentification(CustomerIdentificationRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CpfProtector protector, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; var binding = await db.Set<DeviceTableBinding>().SingleAsync(x => x.DeviceId == validation.Device!.Id && x.UnboundAt == null, ct); await using var tx = await db.Database.BeginTransactionAsync(ct); var session = await db.Set<TableSession>().FromSqlInterpolated($"select * from tables.table_session where id = {request.SessionId} for update").SingleOrDefaultAsync(ct); if (session is null || session.EstablishmentId != validation.Device!.EstablishmentId || session.DiningTableId != binding.DiningTableId) return Results.NotFound(); ProtectedCpf protectedCpf; try { protectedCpf = protector.Protect(request.Value); } catch { return Error(400, "INVALID_CUSTOMER_IDENTIFICATION", "CPF inválido."); } if (session.CustomerIdentificationStatus == "provided") { var currentHash = await db.Set<SessionCustomerIdentification>().Where(x => x.TableSessionId == session.Id && x.Purpose == "session_identification").Select(x => x.ValueHash).SingleAsync(ct); return currentHash == protectedCpf.Hash ? Results.Ok(new { status = "provided" }) : Error(409, "CUSTOMER_IDENTIFICATION_ALREADY_RESOLVED", "Identificação já resolvida."); } if (session.CustomerIdentificationStatus != "pending") return Error(409, "CUSTOMER_IDENTIFICATION_ALREADY_RESOLVED", "Identificação já resolvida."); var retention = await CpfRetentionDays(db, session.EstablishmentId, ct); if (retention is null) return Error(409, "CUSTOMER_IDENTIFICATION_DISABLED", "Política de retenção não configurada."); var now = DateTimeOffset.UtcNow; db.Add(new SessionCustomerIdentification { Id = Guid.NewGuid(), TableSessionId = session.Id, EncryptedValue = protectedCpf.Ciphertext, EncryptionNonce = protectedCpf.Nonce, EncryptionTag = protectedCpf.Tag, ValueHash = protectedCpf.Hash, MaskedValue = protectedCpf.Masked, Purpose = "session_identification", CollectedAt = now, DeviceId = validation.Device.Id, RetentionUntil = now.AddDays(retention.Value) }); session.CustomerIdentificationStatus = "provided"; session.CustomerIdentificationResolvedAt = now; await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Ok(new { status = "provided", maskedValue = protectedCpf.Masked }); }

    private static async Task<IResult> SkipIdentification(SkipIdentificationRequest request, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; await using var tx = await db.Database.BeginTransactionAsync(ct); var session = await db.Set<TableSession>().FromSqlInterpolated($"select * from tables.table_session where id = {request.SessionId} for update").SingleOrDefaultAsync(ct); if (session is null || session.EstablishmentId != validation.Device!.EstablishmentId) return Results.NotFound(); if (session.CustomerIdentificationStatus != "pending") return session.CustomerIdentificationStatus == "skipped" ? Results.Ok(new { status = "skipped" }) : Error(409, "CUSTOMER_IDENTIFICATION_ALREADY_RESOLVED", "Identificação já resolvida."); session.CustomerIdentificationStatus = "skipped"; session.CustomerIdentificationResolvedAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Ok(new { status = "skipped" }); }

    private static async Task<IResult> UnbindDevice(Guid deviceId, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) => await ChangeDevice(deviceId, p, db, "devices.table.configure", "unbind", ct);
    private static async Task<IResult> RevokeDevice(Guid deviceId, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) => await ChangeDevice(deviceId, p, db, "devices.configuration.revoke", "revoke", ct);
    private static async Task<IResult> BlockDevice(Guid deviceId, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) => await ChangeDevice(deviceId, p, db, "devices.block", "block", ct);
    private static async Task<IResult> UnblockDevice(Guid deviceId, ClaimsPrincipal p, AppizzaDbContext db, CancellationToken ct) => await ChangeDevice(deviceId, p, db, "devices.block", "unblock", ct);

    private static async Task<IResult> ChangeDevice(Guid deviceId, ClaimsPrincipal principal, AppizzaDbContext db, string permission, string action, CancellationToken ct)
    { var auth = await RequirePermission(principal, db, permission, ct); if (auth is not null) return auth; var establishmentId = principal.RequiredGuid("establishment_id"); var userId = principal.RequiredGuid("sub"); await using var tx = await db.Database.BeginTransactionAsync(ct); var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == deviceId && x.EstablishmentId == establishmentId, ct); if (device is null) return Results.NotFound(); var now = DateTimeOffset.UtcNow; if (action is "unbind" or "revoke") { var binding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == deviceId && x.UnboundAt == null, ct); if (binding is not null) { binding.UnboundAt = now; binding.UnboundByUserId = userId; binding.UnbindReason = action; } } if (action == "revoke") { device.Status = "revoked"; device.CredentialVersion++; foreach (var session in await db.Set<DeviceSession>().Where(x => x.DeviceId == deviceId && x.RevokedAt == null).ToListAsync(ct)) session.RevokedAt = now; } else if (action == "block") { device.Status = "blocked"; device.BlockedAt = now; device.CredentialVersion++; foreach (var session in await db.Set<DeviceSession>().Where(x => x.DeviceId == deviceId && x.RevokedAt == null).ToListAsync(ct)) session.RevokedAt = now; } else if (action == "unblock") { device.Status = "revoked"; device.BlockedAt = null; } AddOutbox(db, establishmentId, $"device-{action}.v1", new { deviceId }, userId, null); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.NoContent(); }

    private static async Task<IResult> ConfirmCleaning(Guid tableId, ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { var auth = await RequirePermission(principal, db, "tables.cleaning.confirm", ct); if (auth is not null) return auth; var establishmentId = principal.RequiredGuid("establishment_id"); var table = await db.Set<DiningTable>().SingleOrDefaultAsync(x => x.Id == tableId && x.EstablishmentId == establishmentId, ct); if (table is null) return Results.NotFound(); if (table.Status == "available") return Results.NoContent(); if (table.Status != "awaiting_cleaning") return Error(409, "TABLE_NOT_AWAITING_CLEANING", "Mesa não aguarda limpeza."); table.Status = "available"; table.UpdatedAt = DateTimeOffset.UtcNow; AddOutbox(db, establishmentId, "table-cleaning-confirmed.v1", new { tableId }, principal.RequiredGuid("sub"), null); AddOutbox(db, establishmentId, "table-released.v1", new { tableId }, principal.RequiredGuid("sub"), null); await db.SaveChangesAsync(ct); return Results.NoContent(); }

    private static async Task<IResult> SessionResult(ClaimsPrincipal principal, AppizzaDbContext db, bool snapshot, CancellationToken ct)
    { var validation = await ValidateDevice(principal, db, ct); if (validation.Error is not null) return validation.Error; var binding = await db.Set<DeviceTableBinding>().SingleOrDefaultAsync(x => x.DeviceId == validation.Device!.Id && x.UnboundAt == null, ct); if (binding is null) return Results.Ok(new { session = (object?)null }); var session = await db.Set<TableSession>().SingleOrDefaultAsync(x => x.DiningTableId == binding.DiningTableId && ActiveSessionStatuses.Contains(x.Status), ct); return Results.Ok(new { tableId = binding.DiningTableId, session = session is null ? null : new { session.Id, number = session.SessionNumber, session.Status, session.CustomerIdentificationStatus, session.OpenedAt, session.Version }, serverTime = snapshot ? DateTimeOffset.UtcNow : (DateTimeOffset?)null }); }

    private static async Task<(Device? Device, IResult? Error)> ValidateDevice(ClaimsPrincipal principal, AppizzaDbContext db, CancellationToken ct)
    { if (!principal.IsTokenType("device")) return (null, Error(403, "INVALID_TOKEN_TYPE", "Token de dispositivo necessário.")); var deviceId = principal.RequiredGuid("sub"); var establishmentId = principal.RequiredGuid("establishment_id"); var device = await db.Set<Device>().SingleOrDefaultAsync(x => x.Id == deviceId && x.EstablishmentId == establishmentId, ct); if (device is null) return (null, Results.NotFound()); if (device.Status == "blocked") return (null, Error(403, "DEVICE_BLOCKED", "Dispositivo bloqueado.")); if (device.Status != "active" || device.CredentialVersion.ToString() != principal.FindFirstValue("credential_version")) return (null, Error(403, "DEVICE_CREDENTIAL_REVOKED", "Credencial revogada.")); return (device, null); }

    private static async Task<IResult?> RequirePermission(ClaimsPrincipal principal, AppizzaDbContext db, string permission, CancellationToken ct)
    { if (!principal.IsTokenType("user")) return Error(403, "INVALID_TOKEN_TYPE", "Token de funcionário necessário."); var permissions = await PermissionResolver.ResolveAsync(db, principal.RequiredGuid("sub"), DateTimeOffset.UtcNow, ct); return permissions.Contains(permission) ? null : Error(403, "INSUFFICIENT_PERMISSION", "Permissão insuficiente."); }
    private static async Task<int> DeviceLimit(AppizzaDbContext db, Guid establishmentId, CancellationToken ct) => int.TryParse(await db.Set<EstablishmentSetting>().Where(x => x.EstablishmentId == establishmentId && x.SettingKey == Phase1SettingKeys.MaximumTableDevices).Select(x => x.SettingValue).SingleOrDefaultAsync(ct), out var value) && value > 0 ? value : 1;
    private static async Task<int?> CpfRetentionDays(AppizzaDbContext db, Guid establishmentId, CancellationToken ct) => int.TryParse(await db.Set<EstablishmentSetting>().Where(x => x.EstablishmentId == establishmentId && x.SettingKey == Phase1SettingKeys.CpfRetentionDays).Select(x => x.SettingValue).SingleOrDefaultAsync(ct), out var value) && value >= 0 ? value : null;
    private static readonly string[] ActiveSessionStatuses = ["open", "closing", "awaiting_payment", "partially_paid", "paid", "suspended"];
    private static bool IsUniqueViolation(DbUpdateException exception) => exception.InnerException is Npgsql.PostgresException { SqlState: Npgsql.PostgresErrorCodes.UniqueViolation };
    private static TimeZoneInfo ResolveTimeZone(string id) { try { return TimeZoneInfo.FindSystemTimeZoneById(id); } catch { return TimeZoneInfo.Utc; } }
    private static void AddOutbox(AppizzaDbContext db, Guid establishmentId, string eventType, object data, Guid? userId, Guid? deviceId) => db.Add(new OutboxMessage { Id = Guid.NewGuid(), EstablishmentId = establishmentId, EventType = eventType, SchemaVersion = 1, Payload = JsonSerializer.Serialize(new { eventId = Guid.NewGuid(), eventType, schemaVersion = 1, occurredAtUtc = DateTimeOffset.UtcNow, establishmentId, actor = new { userId, deviceId }, data }), OccurredAt = DateTimeOffset.UtcNow, RetryCount = 0 });
    private static IResult Error(int status, string code, string detail) => Results.Problem(statusCode: status, title: detail, detail: detail, extensions: new Dictionary<string, object?> { ["errorCode"] = code });
}

public sealed record SignInRequest(string EstablishmentCode, string Login, string Password);
public sealed record RefreshRequest(string RefreshToken);
public sealed record RegisterDeviceRequest(Guid InstallationId, string DeviceName, string Platform, string? Model, string? OperatingSystemVersion, string ApplicationVersion);
public sealed record BindDeviceRequest(Guid TableId, string ConfigurationToken, Guid? ReplaceDeviceId, string? Reason);
public sealed record HeartbeatRequest(string ApplicationVersion, int? BatteryPercentage, string? NetworkStatus, bool? KioskModeActive, DateTimeOffset? LastCatalogSyncAt);
public sealed record CustomerIdentificationRequest(Guid SessionId, string IdentificationType, string Value, bool PurposeAcknowledged);
public sealed record SkipIdentificationRequest(Guid SessionId);
