// <auto-generated />
using System;
using Appizza.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Appizza.Persistence.Migrations
{
    [DbContext(typeof(AppizzaDbContext))]
    [Migration("20260810173759_Foundation")]
    partial class Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Appizza.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operation_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("IdempotencyKey", "OperationType");

                    b.ToTable("idempotency_record", "integration");
                });

            modelBuilder.Entity("Appizza.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("consumer_name");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Result")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("result");

                    b.HasKey("EventId", "ConsumerName");

                    b.ToTable("inbox_message", "integration");
                });

            modelBuilder.Entity("Appizza.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("ix_outbox_event_occurred");

                    b.HasIndex("ProcessedAt", "NextRetryAt")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_message", "integration");
                });
#pragma warning restore 612, 618
        }
    }
}
