using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
#pragma warning disable CA1707, CA1861
namespace Appizza.Persistence.Migrations;
public partial class Phase7_PaymentsFoundation : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("create schema if not exists payments;");
        migrationBuilder.Sql("create table payments.payment_plan (id uuid primary key, establishment_id uuid not null, table_session_id uuid not null references tables.table_session(id) on delete restrict, version bigint not null, mode varchar(30) not null check (mode in ('total','equal_split','by_participant','by_item','custom_amount')), created_at timestamptz not null, updated_at timestamptz not null);");
        migrationBuilder.Sql("create table payments.payment_plan_allocation (id uuid primary key, establishment_id uuid not null, payment_plan_id uuid not null references payments.payment_plan(id) on delete restrict, participant_id uuid null, order_item_id uuid null, stable_order integer not null, amount numeric(14,2) not null check (amount >= 0), created_at timestamptz not null);");
        migrationBuilder.Sql("create table payments.payment_attempt (id uuid primary key, establishment_id uuid not null, table_session_id uuid not null references tables.table_session(id) on delete restrict, payment_plan_id uuid null references payments.payment_plan(id) on delete restrict, payment_plan_version bigint null, method varchar(30) not null check (method in ('pix','cash','credit','debit','soft_pos')), status varchar(40) not null check (status in ('created','awaiting_customer_action','processing','approved','declined','expired','cancelled','unknown')), amount numeric(14,2) not null check (amount >= 0), reserved_amount numeric(14,2) not null check (reserved_amount >= 0), provider varchar(80) null, provider_reference varchar(200) null, plan_snapshot jsonb null, idempotency_key varchar(200) null, correlation_id uuid null, causation_id uuid null, created_at timestamptz not null, updated_at timestamptz not null, approved_at timestamptz null, version bigint not null);");
        migrationBuilder.Sql("create table payments.refund (id uuid primary key, establishment_id uuid not null, payment_attempt_id uuid not null references payments.payment_attempt(id) on delete restrict, amount numeric(14,2) not null check (amount >= 0), status varchar(30) not null check (status in ('created','processing','completed','failed','cancelled')), provider_reference varchar(200) null, reason varchar(1000) not null, idempotency_key varchar(200) null, created_at timestamptz not null, updated_at timestamptz not null, version bigint not null);");
        migrationBuilder.Sql("create unique index ix_payment_plan_establishment_id_table_session_id_id on payments.payment_plan(establishment_id, table_session_id, id); create index ix_payment_plan_establishment_id_table_session_id_version on payments.payment_plan(establishment_id, table_session_id, version); create unique index ix_payment_plan_allocation_payment_plan_id_stable_order on payments.payment_plan_allocation(payment_plan_id, stable_order); create index ix_payment_attempt_establishment_id_table_session_id_status on payments.payment_attempt(establishment_id, table_session_id, status); create unique index ix_payment_attempt_provider_provider_reference on payments.payment_attempt(provider, provider_reference) where provider_reference is not null; create unique index ix_payment_attempt_establishment_id_idempotency_key on payments.payment_attempt(establishment_id, idempotency_key) where idempotency_key is not null; create index ix_refund_establishment_id_payment_attempt_id on payments.refund(establishment_id, payment_attempt_id); create unique index ix_refund_establishment_id_idempotency_key on payments.refund(establishment_id, idempotency_key) where idempotency_key is not null;");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("drop table if exists payments.refund; drop table if exists payments.payment_attempt; drop table if exists payments.payment_plan_allocation; drop table if exists payments.payment_plan;");
    }
}
