<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AuthContext } from '../services/auth'
import { ClosingApi, type SessionBalance, type SessionPaymentDetails } from '../services/closingApi'
import { refundCapability } from '../services/refundCapabilities'
const auth = new AuthContext(); const api = new ClosingApi(auth); const route = useRoute(); const sessionId = ref(''); const balance = ref<SessionBalance | null>(null); const payments = ref<SessionPaymentDetails | null>(null); const error = ref(''); const loading = ref(false); const cancelling = ref(false); const cancelKey = ref<string | null>(null); const refundAmount = ref<number | null>(null); const refundReason = ref(''); const refundLoading = ref(false); const refundKey = ref<string | null>(null); const confirmLoading = ref<string | null>(null)
async function load() { error.value = ''; balance.value = null; payments.value = null; loading.value = true; try { if (!auth.user && auth.token) await api.me(); const id = sessionId.value.trim(); balance.value = await api.balance(id); payments.value = await api.paymentDetails(id) } catch (e) { error.value = e instanceof Error ? e.message : 'Falha ao consultar sessão' } finally { loading.value = false } }
async function cancelClosing() { if (!balance.value) return; cancelling.value = true; error.value = ''; cancelKey.value ??= crypto.randomUUID(); try { await api.cancelClosing(sessionId.value.trim(), balance.value.version, 'Cancelamento solicitado pelo operador', cancelKey.value); cancelKey.value = null; await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Falha ao cancelar fechamento' } finally { cancelling.value = false } }
function canRefund() { return auth.has('payments.refund') }
function beginRefund() { refundKey.value ??= crypto.randomUUID() }
async function createRefund(attemptId: string) { if (!refundAmount.value || !refundReason.value.trim() || !canRefund()) return; refundLoading.value = true; error.value = ''; beginRefund(); try { await api.createRefund(attemptId, refundAmount.value, refundReason.value.trim(), refundKey.value!); refundAmount.value = null; refundReason.value = ''; refundKey.value = null; await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Falha ao criar refund'; await load() } finally { refundLoading.value = false } }
async function confirmCash(refundId: string) { if (!canRefund() || !window.confirm('Confirmar devolução em dinheiro?')) return; confirmLoading.value = refundId; error.value = ''; try { await api.confirmCash(refundId); await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Falha ao confirmar Cash'; await load() } finally { confirmLoading.value = null } }
onMounted(() => { const routed = route.query.sessionId; if (typeof routed === 'string' && routed.trim()) { sessionId.value = routed; void load() } })
</script>
<template><v-container><h1>Closing e pagamentos</h1><v-text-field v-model="sessionId" label="Session ID" /><v-btn :loading="loading" :disabled="!sessionId" @click="load">{{ balance ? 'Atualizar' : 'Consultar' }}</v-btn><v-btn v-if="balance && (balance.status === 'closing' || balance.status === 'awaiting_payment')" :loading="cancelling" @click="cancelClosing">Cancelar fechamento</v-btn><v-progress-circular v-if="loading" indeterminate /><v-alert v-if="error" type="warning">{{ error }}</v-alert><v-card v-if="balance" class="mt-4"><v-card-text>Status: {{ balance.status }}<br>Total: {{ balance.totalAmount }}<br>Pago: {{ balance.paidAmount }}<br>Reservado: {{ balance.reservedAmount }}<br>Saldo pendente: {{ balance.outstandingAmount }}<br>Versão: {{ balance.version }}</v-card-text></v-card><v-card v-if="payments" class="mt-4" data-testid="payment-detail"><v-card-text><div v-for="plan in payments.paymentPlans" :key="plan.id">PaymentPlan {{ plan.id }} ({{ plan.mode }}, v{{ plan.version }})<div v-for="allocation in plan.allocations" :key="allocation.id">Allocation {{ allocation.stableOrder }}: {{ allocation.amount }} ({{ allocation.id }})</div></div><div v-for="attempt in payments.paymentAttempts" :key="attempt.id" class="payment-attempt" :data-testid="`payment-attempt-${attempt.method}`"><h3>Pagamento {{ attempt.id }}</h3><div>{{ attempt.method }} / {{ attempt.status }} / {{ attempt.amount }}</div><div>Reembolsado: {{ attempt.refundSummary.completedAmount }} | Em processamento: {{ attempt.refundSummary.inFlightAmount }} | Disponível: {{ attempt.refundSummary.availableAmount }}</div><div v-for="refund in attempt.refunds" :key="refund.refundId" class="refund-row">{{ refund.amount }} — {{ refund.reason }} — {{ refund.status }}<span v-if="refund.reconciliationRequired"> — Reconciliação necessária</span><v-btn v-if="refund.status === 'Created' && refundCapability(attempt.method).manualConfirmation && canRefund()" :loading="confirmLoading === refund.refundId" @click="confirmCash(refund.refundId)">Confirmar Cash</v-btn></div><div v-if="canRefund() && attempt.status === 'Approved' && attempt.refundSummary.availableAmount > 0"><v-text-field v-model="refundAmount" label="Valor do refund" type="number" /><v-text-field v-model="refundReason" label="Motivo" /><v-btn :loading="refundLoading" :disabled="refundLoading || !refundAmount || !refundReason.trim()" @click="createRefund(attempt.id)">Criar refund</v-btn></div></div></v-card-text></v-card></v-container></template>
