import { flushPromises, mount } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import ClosingSessionsView from './ClosingSessionsView.vue'

const push = vi.fn()
vi.mock('vue-router', () => ({ useRouter: () => ({ push }) }))
const stubs = { 'v-container': { template: '<div><slot /></div>' }, 'v-btn': { props: { loading: Boolean }, emits: ['click'], template: '<button @click="$emit(\'click\')"><slot /></button>' }, 'v-alert': { template: '<div><slot /></div>' }, 'v-card': { template: '<div><slot /></div>' }, 'v-card-text': { template: '<div><slot /></div>' }, 'v-progress-circular': true }
const session = (id: string, status: string) => ({ sessionId: id, status, version: 2, openedAt: '2026-01-01T00:00:00Z', closingStartedAt: null, diningTableId: `table-${id}` })

describe('ClosingSessionsView', () => {
  it('loads authoritative closing sessions and lifecycle states', async () => { const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify([session('a', 'closing'), session('b', 'awaiting_payment')]), { status: 200 })); vi.stubGlobal('fetch', fetchMock); const w = mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); expect(fetchMock).toHaveBeenCalledWith('/api/v1/operations/sessions/closing', { headers: { Authorization: 'Bearer ' } }); expect(w.text()).toContain('a'); expect(w.text()).toContain('awaiting_payment') })
  it('renders empty state', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('[]', { status: 200 }))); const w = mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); expect(w.text()).toContain('Nenhuma sessão em fechamento') })
  it('navigates selected session to closing payments', async () => { push.mockReset(); vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify([session('known', 'closing')]), { status: 200 }))); const w = mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); await w.findAll('button')[1].trigger('click'); expect(push).toHaveBeenCalledWith({ name: 'closing-payments', query: { sessionId: 'known' } }) })
  it('replaces list on refresh', async () => { const f = vi.fn().mockImplementationOnce(() => new Response(JSON.stringify([session('a', 'closing'), session('b', 'closing')]), { status: 200 })).mockImplementationOnce(() => new Response(JSON.stringify([session('c', 'awaiting_payment')]), { status: 200 })); vi.stubGlobal('fetch', f); const w = mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); await w.find('button').trigger('click'); await flushPromises(); expect(w.text()).toContain('c'); expect(w.text()).not.toContain('table-a'); expect(f).toHaveBeenCalledTimes(2) })
  it('clears stale list on failed refresh without mutation', async () => { const f = vi.fn().mockImplementationOnce(() => new Response(JSON.stringify([session('a', 'closing')]), { status: 200 })).mockImplementationOnce(() => new Response('', { status: 503 })); vi.stubGlobal('fetch', f); const w = mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); await w.find('button').trigger('click'); await flushPromises(); expect(w.text()).not.toContain('table-a'); expect(w.text()).toContain('503'); expect(f.mock.calls.every((c: any[]) => !c[1]?.method || c[1].method === 'GET')).toBe(true) })
  it('sends no establishment id or mutation', async () => { const f = vi.fn().mockResolvedValue(new Response('[]', { status: 200 })); vi.stubGlobal('fetch', f); mount(ClosingSessionsView, { global: { stubs } }); await flushPromises(); const [url, init] = f.mock.calls[0]; expect(url).not.toContain('establishment'); expect(init.method).toBeUndefined(); expect(init.body).toBeUndefined() })
})
