using Appizza.BuildingBlocks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Appizza.Modules.Catalog;

#pragma warning disable CA1725

public sealed class PizzaSize : CatalogEntity { public Guid EstablishmentId { get; set; } public string Name { get; set; } = null!; public string? ShortName { get; set; } public int? SliceCount { get; set; } public decimal? DiameterCm { get; set; } public int DisplayOrder { get; set; } public string Status { get; set; } = "active"; }
public sealed class PizzaFlavor : CatalogEntity { public Guid ProductId { get; set; } public string Status { get; set; } = "active"; public int DisplayOrder { get; set; } }
public sealed class PizzaFlavorPrice : CatalogEntity { public Guid PizzaFlavorId { get; set; } public Guid PizzaSizeId { get; set; } public decimal Price { get; set; } public bool Available { get; set; } = true; public int? EstimatedPreparationMinutes { get; set; } }
public sealed class Dough : CatalogEntity { public Guid EstablishmentId { get; set; } public string Name { get; set; } = null!; public string? Description { get; set; } public string Status { get; set; } = "active"; public bool IsDefault { get; set; } }
public sealed class DoughSizePrice { public Guid DoughId { get; set; } public Guid PizzaSizeId { get; set; } public decimal AdditionalPrice { get; set; } public bool Available { get; set; } = true; }
public sealed class Crust : CatalogEntity { public Guid EstablishmentId { get; set; } public string Name { get; set; } = null!; public string? Description { get; set; } public Guid? ImageMediaId { get; set; } public string Status { get; set; } = "active"; }
public sealed class CrustSizePrice { public Guid CrustId { get; set; } public Guid PizzaSizeId { get; set; } public decimal AdditionalPrice { get; set; } public bool Available { get; set; } = true; }
public sealed class PizzaProductSize { public Guid ProductId { get; set; } public Guid PizzaSizeId { get; set; } public bool Available { get; set; } = true; public int? MaximumFlavorCount { get; set; } public int DisplayOrder { get; set; } }
public sealed class PizzaDough { public Guid ProductId { get; set; } public Guid DoughId { get; set; } public bool Available { get; set; } = true; }
public sealed class PizzaCrust { public Guid ProductId { get; set; } public Guid CrustId { get; set; } public bool Available { get; set; } = true; }
public sealed class CustomPizzaBasePrice { public Guid CustomPizzaProductId { get; set; } public Guid PizzaSizeId { get; set; } public decimal BasePrice { get; set; } public bool Available { get; set; } = true; }
public sealed class Combo : CatalogEntity { public Guid ProductId { get; set; } public string PricingStrategy { get; set; } = "fixed"; public decimal? FixedPrice { get; set; } public string? DiscountType { get; set; } public decimal? DiscountValue { get; set; } }
public sealed class ComboGroup : CatalogEntity { public Guid ComboId { get; set; } public string Name { get; set; } = null!; public string? Description { get; set; } public int MinimumItems { get; set; } public int MaximumItems { get; set; } public bool AllowRepetition { get; set; } public bool Required { get; set; } public int DisplayOrder { get; set; } }
public sealed class ComboGroupItem : CatalogEntity { public Guid ComboGroupId { get; set; } public Guid? ProductId { get; set; } public Guid? ProductVariantId { get; set; } public Guid? CategoryId { get; set; } public string InclusionType { get; set; } = "specific"; public decimal AdditionalPrice { get; set; } public int? FixedQuantity { get; set; } public string Status { get; set; } = "active"; }
public sealed class ComboItemRestriction { public Guid Id { get; set; } public Guid ComboGroupItemId { get; set; } public string RestrictionType { get; set; } = null!; public Guid? ReferencedEntityId { get; set; } public string? Value { get; set; } public DateTimeOffset CreatedAt { get; set; } }

public static class PizzaPricing
{
    public static decimal EqualFractionBasePrice(IEnumerable<decimal> flavorPrices)
    {
        var prices = flavorPrices.ToArray();
        if (prices.Length == 0) throw new ArgumentException("At least one flavor is required.", nameof(flavorPrices));
        if (prices.Any(price => price < 0)) throw new ArgumentOutOfRangeException(nameof(flavorPrices));
        return decimal.Round(prices.Average(), 2, MidpointRounding.AwayFromZero);
    }
}

public sealed class PizzaSizeConfiguration : IEntityTypeConfiguration<PizzaSize> { public void Configure(EntityTypeBuilder<PizzaSize> b) { b.ToTable("pizza_size", "catalog", t => { t.HasCheckConstraint("ck_pizza_size_status", "status in ('active','inactive','archived')"); t.HasCheckConstraint("ck_pizza_size_values", "(slice_count is null or slice_count > 0) and (diameter_cm is null or diameter_cm > 0)"); }); b.HasKey(x => x.Id); b.Property(x => x.DiameterCm).HasPrecision(8, 2); b.HasIndex(x => new { x.EstablishmentId, x.Status, x.DisplayOrder }); } }
public sealed class PizzaFlavorConfiguration : IEntityTypeConfiguration<PizzaFlavor> { public void Configure(EntityTypeBuilder<PizzaFlavor> b) { b.ToTable("pizza_flavor", "catalog", t => t.HasCheckConstraint("ck_pizza_flavor_status", "status in ('active','inactive','archived')")); b.HasKey(x => x.Id); b.HasIndex(x => x.ProductId).IsUnique(); } }
public sealed class PizzaFlavorPriceConfiguration : IEntityTypeConfiguration<PizzaFlavorPrice> { public void Configure(EntityTypeBuilder<PizzaFlavorPrice> b) { b.ToTable("pizza_flavor_price", "catalog", t => t.HasCheckConstraint("ck_pizza_flavor_price", "price >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Price).HasPrecision(14, 2); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => new { x.PizzaFlavorId, x.PizzaSizeId }).IsUnique(); } }
public sealed class DoughConfiguration : IEntityTypeConfiguration<Dough> { public void Configure(EntityTypeBuilder<Dough> b) { b.ToTable("dough", "catalog", t => t.HasCheckConstraint("ck_dough_status", "status in ('active','inactive','archived')")); b.HasKey(x => x.Id); b.HasIndex(x => new { x.EstablishmentId, x.Status }); } }
public sealed class DoughSizePriceConfiguration : IEntityTypeConfiguration<DoughSizePrice> { public void Configure(EntityTypeBuilder<DoughSizePrice> b) { b.ToTable("dough_size_price", "catalog", t => t.HasCheckConstraint("ck_dough_size_price", "additional_price >= 0")); b.HasKey(x => new { x.DoughId, x.PizzaSizeId }); b.Property(x => x.AdditionalPrice).HasPrecision(14, 2); } }
public sealed class CrustConfiguration : IEntityTypeConfiguration<Crust> { public void Configure(EntityTypeBuilder<Crust> b) { b.ToTable("crust", "catalog", t => t.HasCheckConstraint("ck_crust_status", "status in ('active','inactive','archived')")); b.HasKey(x => x.Id); b.HasIndex(x => new { x.EstablishmentId, x.Status }); } }
public sealed class CrustSizePriceConfiguration : IEntityTypeConfiguration<CrustSizePrice> { public void Configure(EntityTypeBuilder<CrustSizePrice> b) { b.ToTable("crust_size_price", "catalog", t => t.HasCheckConstraint("ck_crust_size_price", "additional_price >= 0")); b.HasKey(x => new { x.CrustId, x.PizzaSizeId }); b.Property(x => x.AdditionalPrice).HasPrecision(14, 2); } }
public sealed class PizzaProductSizeConfiguration : IEntityTypeConfiguration<PizzaProductSize> { public void Configure(EntityTypeBuilder<PizzaProductSize> b) { b.ToTable("pizza_product_size", "catalog", t => t.HasCheckConstraint("ck_pizza_product_size_flavors", "maximum_flavor_count is null or maximum_flavor_count > 0")); b.HasKey(x => new { x.ProductId, x.PizzaSizeId }); } }
public sealed class PizzaDoughConfiguration : IEntityTypeConfiguration<PizzaDough> { public void Configure(EntityTypeBuilder<PizzaDough> b) { b.ToTable("pizza_dough", "catalog"); b.HasKey(x => new { x.ProductId, x.DoughId }); } }
public sealed class PizzaCrustConfiguration : IEntityTypeConfiguration<PizzaCrust> { public void Configure(EntityTypeBuilder<PizzaCrust> b) { b.ToTable("pizza_crust", "catalog"); b.HasKey(x => new { x.ProductId, x.CrustId }); } }
public sealed class CustomPizzaBasePriceConfiguration : IEntityTypeConfiguration<CustomPizzaBasePrice> { public void Configure(EntityTypeBuilder<CustomPizzaBasePrice> b) { b.ToTable("custom_pizza_base_price", "catalog", t => t.HasCheckConstraint("ck_custom_pizza_base_price", "base_price >= 0")); b.HasKey(x => new { x.CustomPizzaProductId, x.PizzaSizeId }); b.Property(x => x.BasePrice).HasPrecision(14, 2); } }
public sealed class ComboConfiguration : IEntityTypeConfiguration<Combo> { public void Configure(EntityTypeBuilder<Combo> b) { b.ToTable("combo", "catalog", t => { t.HasCheckConstraint("ck_combo_prices", "(fixed_price is null or fixed_price >= 0) and (discount_value is null or discount_value >= 0)"); t.HasCheckConstraint("ck_combo_fixed", "pricing_strategy <> 'fixed' or fixed_price is not null"); }); b.HasKey(x => x.Id); b.Property(x => x.FixedPrice).HasPrecision(14, 2); b.Property(x => x.DiscountValue).HasPrecision(14, 2); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => x.ProductId).IsUnique(); } }
public sealed class ComboGroupConfiguration : IEntityTypeConfiguration<ComboGroup> { public void Configure(EntityTypeBuilder<ComboGroup> b) { b.ToTable("combo_group", "catalog", t => t.HasCheckConstraint("ck_combo_group_limits", "minimum_items >= 0 and maximum_items >= minimum_items and maximum_items > 0")); b.HasKey(x => x.Id); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => new { x.ComboId, x.DisplayOrder }); } }
public sealed class ComboGroupItemConfiguration : IEntityTypeConfiguration<ComboGroupItem> { public void Configure(EntityTypeBuilder<ComboGroupItem> b) { b.ToTable("combo_group_item", "catalog", t => { t.HasCheckConstraint("ck_combo_group_item_selector", "((product_id is not null)::int + (product_variant_id is not null)::int + (category_id is not null)::int) = 1"); t.HasCheckConstraint("ck_combo_group_item_price", "additional_price >= 0"); t.HasCheckConstraint("ck_combo_group_item_quantity", "fixed_quantity is null or fixed_quantity > 0"); t.HasCheckConstraint("ck_combo_group_item_status", "status in ('active','inactive','archived')"); }); b.HasKey(x => x.Id); b.Property(x => x.AdditionalPrice).HasPrecision(14, 2); b.HasIndex(x => x.ComboGroupId); } }
public sealed class ComboItemRestrictionConfiguration : IEntityTypeConfiguration<ComboItemRestriction> { public void Configure(EntityTypeBuilder<ComboItemRestriction> b) { b.ToTable("combo_item_restriction", "catalog"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.ComboGroupItemId, x.RestrictionType }); } }
